### ISSUE TITLE
I'm trying to use wifi-pumpkin on kali-rolling installed via linux-deploy at android + usb wifi

### ISSUE THREAD

**Issue by userdsp** [P0cL4bs/WiFi-Pumpkin-deprecated#100]
#### Please tell us details about your environment.
- Card wireless adapters name (please check if support AP/mode): yes wn722n
- Version used tool: 0.8.3
- Virtual Machine (yes or no and which): linux-deploy on android
- Operating System and version: 
  ![screenshot_20161019-001259](https://cloud.githubusercontent.com/assets/7585552/19496599/e1df6a16-9590-11e6-85a6-8e33d4553bac.png)

Linux kali 3.4.111-nethunter-hlte-eur-M-7.1.1
1 SMP PREEMPT Sun Apr 17 18:32:10 EDT 2016 armv7l GNU/Linux

Adding following line to ~/.profile file. (ie: system env var) 
QT_X11_NO_MITSHM=1

doesn't work to me.

**Comment by mh4x0f** [comment]
I think that wifi-pumpkin not work fine in this system. I don't know how fix this bug in system linux-deploy. i just found  this solution that you mentioned above. also I don't have an android phone for do some tests and some still do not intend to do any type, My suggestion is search on google apparently there are many solutions for this type of error.
