### ISSUE TITLE
Error !!!! Interface Wireless

### ISSUE THREAD

**Issue by andreatripoli** [P0cL4bs/WiFi-Pumpkin-deprecated#105]
Error Network Card : You are connected with interface wireless, try again with local connection

Hi, I have two wireless cards. Integrated chipset , and a USB Wi-Fi adapter. 
I have tried both wlan0 and wlan1 and still receive the following error;
" You are connected with interface wireless, try again with local connection" .

how can I do? Why can not I use the LAN. Do not use a virtual machine, I Kali Linux installed in the partition.

Find me a solution, please. If I have to change some code in the program to inhibit the error and allow you to simultaneously use two wireless devices, whatever ... Waiting for your news

Yours sincerely

**Comment by mh4x0f** [comment]
https://github.com/P0cL4bs/WiFi-Pumpkin/wiki/Installation#2-wifi-wireless-adapter
