### ISSUE TITLE
Connect to fake AP automatically. 

### ISSUE THREAD

**Issue by jeretc** [P0cL4bs/WiFi-Pumpkin-deprecated#107]
## What's the problem (or question)?

*hi, this is not exactly an issue but is it possible for clients to force connect to rogue/fake ap? *

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: 
* Virtual Machine (yes or no and which): 
* Operating System and version:

**Comment by mh4x0f** [comment]
No.
