### ISSUE TITLE
Internet interface  set up bridge ppp0 

### ISSUE THREAD

**Issue by marvinfisher9** [P0cL4bs/WiFi-Pumpkin-deprecated#109]
## What's the problem (or question)?

You plan to do support other interfaces, except eth0? Or, please tell me how to set up bridge ppp0 to eth0. 
p.s.: sorry for my English

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): wn722n
* Version used tool: 0.8.3
* Virtual Machine (yes or no and which): no
* Operating System and version: kali linux 2016.2 w43

**Comment by mh4x0f** [comment]
I added some improvements for get interface 'ppp', thank's for issue.

**Comment by marvinfisher9** [comment]
Thank you very much

**Comment by marvinfisher9** [comment]
ppp0 does not work again
