### ISSUE TITLE
AP does not show.

### ISSUE THREAD

**Issue by jeretc** [P0cL4bs/WiFi-Pumpkin-deprecated#110]
## What's the problem (or question)?

*wifi-pumpkin does not show access point. installation was fine, startup without errors. wlan0 is connected to internet and wlan1 is free for wifi-pumpkin.* No error output to screenshot and show you.

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): Tp-Link WN722N
* Version used tool: 0.83
* Virtual Machine (yes or no and which): No
* Operating System and version: Parrot Os 3

**Comment by mh4x0f** [comment]
This an #69  were the same.
