### ISSUE TITLE
DNS Spoof not showing cloned website.

### ISSUE THREAD

**Issue by jeretc** [P0cL4bs/WiFi-Pumpkin-deprecated#111]
![screenshot at 2016-11-09 13-40-46](https://cloud.githubusercontent.com/assets/20941239/20128679/c60e919a-a684-11e6-864b-ca8533de2712.png)
![screenshot at 2016-11-09 13-45-02](https://cloud.githubusercontent.com/assets/20941239/20128684/ce8f42d8-a684-11e6-9fbb-b4359e3d5ac9.png)

## What's the problem (or question)?

*im trying to use the dns spoof attack, with the AP and phishing manager, clone website option.
cannot get the cloned website to show up. on the victim browser page cannot be displayed but there is internet connection.

on the dns spoof i tried with and without the url and ip, it can only access the fake page using ip address.*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): tp 722n
* Version used tool: 0.83
* Virtual Machine (yes or no and which): no
* Operating System and version: parrot os 3

**Comment by mh4x0f** [comment]
dns spoof only work for HTTP website
