### ISSUE TITLE
DNS Spoof Attack - Not working.

### ISSUE THREAD

**Issue by ap0l0** [P0cL4bs/WiFi-Pumpkin-deprecated#113]
## What's the problem (or question)?

*The DNS Spoof attack is not redirecting any traffic. Also, how can I redirect traffic from all domains to the Phishing Local Server?*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): TP Link
* Version used tool: 0.8.3
* Virtual Machine (yes or no and which): Kali 2.0 VMware Fusion
* Operating System and version:  Kali 2.0

**Comment by mh4x0f** [comment]
https://github.com/P0cL4bs/WiFi-Pumpkin/wiki/Bug-reporting
