### ISSUE TITLE
Wifi-Pumpkin & Facebook Creds (HSTS, SSLstrip 2016)

### ISSUE THREAD

**Issue by maiksir** [P0cL4bs/WiFi-Pumpkin-deprecated#114]
<h3>Hello Guys! Since I'm literally in the middle of the connection when setting up a fake AP shouldn't I be seeing https creds Like Facebook's as well?</h3>

It seems like I can only see the creds posted in HTTP sites only,  and after a couple hours of searching I found out what HSTS is.. Well I tried to find a tutorial or something on google but no luck.

Is is possible to capture facebook's creds as well?

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): - It's working fine
* Version used tool: - WiFi-Pumpkin v0.8.3
* Virtual Machine (yes or no and which): no, Main OS on laptop.
* Operating System and version: kali linux 2.0 Rolling 64 bit

**Comment by mh4x0f** [comment]
No
