### ISSUE TITLE
Multiple Issues with Wifi-Pumpkin

### ISSUE THREAD

**Issue by denux** [P0cL4bs/WiFi-Pumpkin-deprecated#115]
1) Everything seems fine,but sometimes the AP is not visible and a restart of network-manager or Laptop does the task.

2) I can make an AP but when I remove the '###' from host-apd tab in settings menu, the AP becomes invisible to devices.

3) With two wifi-interfaces (both of them supports AP mode) the AP was created without errors but wasn't visible unless it was set wlan1(that is the softAP interface) to unmanaged-devices in Network manager. So everytime I work with a dual wifi combo, I have to make the SoftAP interface(wlan1) unmanaged in Network-manager.(Maybe this is the same issue in kali where the network-manager interferes with the device config, so I switched to parrot but it had the same issue so this unmanaged trick worked out on parrot).
It would be nice if you could set the rouge AP interface to unmanaged mode on software bootup and back to managed by network-manager as we exit the software.

PS.With an Ethernet and Wireless combo Wifi-Pumpkin works fine.

please seek to these 3 issue.
Thank you.

* Card wireless adapters name : Netgear WNA1100 (supports AP mode)
* Virtual Machine (yes or no and which): No
* Operating System and version: 4.7.0-parrot-amd64

**Comment by mh4x0f** [comment]
> Everything seems fine,but sometimes the AP is not visible and a restart of network-manager or Laptop does the task.

you can fix  the network-manager config, see in this comment issue [solution](https://github.com/P0cL4bs/WiFi-Pumpkin/issues/89#issuecomment-254022958)

>  can make an AP but when I remove the '###' from host-apd tab in settings menu, the AP becomes invisible to devices.

I think that you are doing something wrong, you need remove only this lines that one "#".  as can see in screenshot bellow.
![kali rolling1dsadsa](https://cloud.githubusercontent.com/assets/6795613/20495893/b60d1a4c-b001-11e6-9c9c-4ac534b22e0b.png)

> With two wifi-interfaces (both of them supports AP mode) the AP was created without errors but wasn't visible unless it was set to unmanaged-devices in Network manager. So everytime I work with a dual wifi combo, I have to make the SoftAP unmanaged in Network-manager.(Maybe this is the same issue in kali where the network-manager interferes with the device config,so I switched to parrot but it had the same issue so this unmanaged trick worked out)

you can fix  the network-manager config, see in this comment issue [solution](https://github.com/P0cL4bs/WiFi-Pumpkin/issues/89#issuecomment-254022958)
