### ISSUE TITLE
Tools not found

### ISSUE THREAD

**Issue by shivgori** [P0cL4bs/WiFi-Pumpkin-deprecated#118]
## 1) when i clicked ettercap and driftnet tool it show popup ettercap or driftnet not found?
      2)When i use monitor net creds then it only catch url not see credentials?

*answer here*

#### Please tell us details about your environment.
* Tp-Link TL-WN722N (please check if support AP/mode):
* Version used tool: 0.8.3
* Virtual Machine (yes or no and which): no
* Operating System and version: Ubuntu 16.10

**Comment by mh4x0f** [comment]
![artworks-000111261210-x9qzrr-t500x500](https://cloud.githubusercontent.com/assets/6795613/20640358/8be8cfd8-b3ba-11e6-9d75-ea7b9d44c69c.jpg)
