### ISSUE TITLE
Credentials are not monitored

### ISSUE THREAD

**Issue by shivgori** [P0cL4bs/WiFi-Pumpkin-deprecated#119]
## When i use monitor netcreds then it only catch url not see credentials?

*answer here*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):Tp-Link TL-WN722N 
* Version used tool: 0.8.3
* Virtual Machine (yes or no and which): no
* Operating System and version: Ubuntu 16.10

**Comment by mh4x0f** [comment]
netcreds only capture HTTP traffic

**Comment by shivgori** [comment]
It means credentials of gmail fb or other https sites can not be capture
