### ISSUE TITLE
Phising Manager - set directory problem

### ISSUE THREAD

**Issue by jeretc** [P0cL4bs/WiFi-Pumpkin-deprecated#122]
## What's the problem (or question)?

*Phising manager set to set directory option, and under setEnvPATH: var/www/ 
i have a website-fake portal. already set my local ip address but the website not starting up or showing on webpage*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: 
* Virtual Machine (yes or no and which): no
* Operating System and version: kali 2016.2

**Comment by mh4x0f** [comment]
I don't find any problem with this module, i try in my lab with different OS and all working fine. maybe you are doing something wrong.
