### ISSUE TITLE
Error while using two wifi interfaces

### ISSUE THREAD

**Issue by denux** [P0cL4bs/WiFi-Pumpkin-deprecated#123]
![Uploading Screenshot at 2016-12-03 17-20-00.png…]()

I have enabled ignored usb adapter setting then I get this error.
but when I edit my network config in network manager and unmanage my card, hostapd can create an AP.
 
* Card wireless adapters name (please check if support AP/mode): tp link wn722n
* Version used tool: 
* Virtual Machine (yes or no and which): 
* Operating System and version:

**Comment by mh4x0f** [comment]
you can fix  the network-manager config, see in this comment issue [solution](https://github.com/P0cL4bs/WiFi-Pumpkin/issues/89#issuecomment-254022958)
