### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by jeretc** [P0cL4bs/WiFi-Pumpkin-deprecated#126]
## What's the problem (or question)?

*libpng warning: iCCP: known incorrect sRGB profile, but wifi-pumpkin still runs fine.*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: 
* Virtual Machine (yes or no and which): no
* Operating System and version: parrot

**Comment by mh4x0f** [comment]
this is just a warning, nothing is wrong
