### ISSUE TITLE
failed to initiate accesss point.

### ISSUE THREAD

**Issue by jeretc** [P0cL4bs/WiFi-Pumpkin-deprecated#127]
## What's the problem (or question)?

*have attached the image file. in my hostapd.conf is this :

interface=wlan1
ssid=PumpAP
channel=11
driver=nl80211
*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):tplink 722n

* Version used tool: 0.8.3
* Virtual Machine (yes or no and which): no
* Operating System and version: parrotsec 3
![screenshot at 2016-12-04 23-18-44](https://cloud.githubusercontent.com/assets/20941239/20867135/6c02e48c-ba78-11e6-8882-888bd4c3bdc2.png)

**Comment by mh4x0f** [comment]
see in this comment issue [solution](https://github.com/P0cL4bs/WiFi-Pumpkin/issues/89#issuecomment-254022958)

**Comment by jeretc** [comment]
hi using wicd solved the issue.

**Comment by jeretc** [comment]
Hi is there a manual for wifi-pumpkin.

Thanks.
