### ISSUE TITLE
Responder - Error starting TCP server on port 443

### ISSUE THREAD

**Issue by userdsp** [P0cL4bs/WiFi-Pumpkin-deprecated#130]
## What's the problem (or question)?

*answer here*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):wn722n and AWUS036H
* Version used tool: 0.8.3
* Virtual Machine (yes or no and which): yes kali linux 2016.2 64bit
* Operating System and version: Linux kali 4.8.0-kali1-amd64 #1 SMP Debian 4.8.5-1kali1 (2016-11-04) x86_64 GNU/Linux
root@kali:~/handshakes# responder -i mon0
                                         __
  .----.-----.-----.-----.-----.-----.--|  |.-----.----.
  |   _|  -__|__ --|  _  |  _  |     |  _  ||  -__|   _|
  |__| |_____|_____|   __|_____|__|__|_____||_____|__|
                   |__|

           NBT-NS, LLMNR & MDNS Responder 2.3.3.1

  Author: Laurent Gaffie (laurent.gaffie@gmail.com)
  To kill this script hit CRTL-C

Error: -I <if> mandatory option is missing
root@kali:~/handshakes# responder -I mon0
                                         __
  .----.-----.-----.-----.-----.-----.--|  |.-----.----.
  |   _|  -__|__ --|  _  |  _  |     |  _  ||  -__|   _|
  |__| |_____|_____|   __|_____|__|__|_____||_____|__|
                   |__|

           NBT-NS, LLMNR & MDNS Responder 2.3.3.1

  Author: Laurent Gaffie (laurent.gaffie@gmail.com)
  To kill this script hit CRTL-C

[+] Poisoners:
    LLMNR                      [ON]
    NBT-NS                     [ON]
    DNS/MDNS                   [ON]

[+] Servers:
    HTTP server                [ON]
    HTTPS server               [ON]
    WPAD proxy                 [OFF]
    Auth proxy                 [OFF]
    SMB server                 [ON]
    Kerberos server            [ON]
    SQL server                 [ON]
    FTP server                 [ON]
    IMAP server                [ON]
    POP3 server                [ON]
    SMTP server                [ON]
    DNS server                 [ON]
    LDAP server                [ON]

[+] HTTP Options:
    Always serving EXE         [OFF]
    Serving EXE                [OFF]
    Serving HTML               [OFF]
    Upstream Proxy             [OFF]

[+] Poisoning Options:
    Analyze Mode               [OFF]
    Force WPAD auth            [OFF]
    Force Basic Auth           [OFF]
    Force LM downgrade         [OFF]
    Fingerprint hosts          [OFF]

[+] Generic Options:
    Responder NIC              [mon0]
    Responder IP               [192.168.1.106]
    Challenge set              [1122334455667788]
    Don't Respond To Names     ['ISATAP']

[+] Listening for events...
====================================================

 WiFi-Pumpkin Report Logger

Session information::

[*] ESSID AP: 
[*] AP Create at: Mon Dec  5 11:47:45 2016
[*] AP Down   at: Mon Dec  5 11:50:30 2016

Report Generated at::Mon Dec  5 14:16:54 2016

-[ responder Logger ]-
SessionID[NDA4ODE=] 2016-12-05 11:47:53,997 :                                          __
SessionID[NDA4ODE=] 2016-12-05 11:47:53,998 :   .----.-----.-----.-----.-----.-----.--|  |.-----.----.
SessionID[NDA4ODE=] 2016-12-05 11:47:53,999 :   |   _|  -__|__ --|  _  |  _  |     |  _  ||  -__|   _|
SessionID[NDA4ODE=] 2016-12-05 11:47:54,000 :   |__| |_____|_____|   __|_____|__|__|_____||_____|__|
SessionID[NDA4ODE=] 2016-12-05 11:47:54,001 :                    |__|
SessionID[NDA4ODE=] 2016-12-05 11:47:54,002 : 
SessionID[NDA4ODE=] 2016-12-05 11:47:54,008 :            NBT-NS, LLMNR & MDNS  Responder 2.3.3.0 
SessionID[NDA4ODE=] 2016-12-05 11:47:54,009 : 
SessionID[NDA4ODE=] 2016-12-05 11:47:54,010 :   Author: Laurent Gaffie (laurent.gaffie@gmail.com)
SessionID[NDA4ODE=] 2016-12-05 11:47:54,011 :   To kill this script hit CRTL-C
SessionID[NDA4ODE=] 2016-12-05 11:47:54,012 : 
SessionID[NDA4ODE=] 2016-12-05 11:47:54,016 : 
SessionID[NDA4ODE=] 2016-12-05 11:47:54,018 : [+] Poisoners:
SessionID[NDA4ODE=] 2016-12-05 11:47:54,019 :     LLMNR                      [ON]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,021 :     NBT-NS                     [ON]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,023 :     DNS/MDNS                   [ON]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,024 : 
SessionID[NDA4ODE=] 2016-12-05 11:47:54,028 : [+] Servers:
SessionID[NDA4ODE=] 2016-12-05 11:47:54,030 :     HTTP server                [ON]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,031 :     HTTPS server               [ON]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,032 :     WPAD proxy                 [ON]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,036 :     Auth proxy                 [OFF]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,038 :     SMB server                 [ON]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,043 :     Kerberos server            [ON]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,044 :     SQL server                 [ON]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,050 :     FTP server                 [ON]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,051 :     IMAP server                [ON]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,053 :     POP3 server                [ON]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,057 :     SMTP server                [ON]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,059 :     DNS server                 [ON]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,064 :     LDAP server                [ON]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,066 : 
SessionID[NDA4ODE=] 2016-12-05 11:47:54,067 : [+] HTTP Options:
SessionID[NDA4ODE=] 2016-12-05 11:47:54,071 :     Always serving EXE         [OFF]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,080 :     Serving EXE                [OFF]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,085 :     Serving HTML               [OFF]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,087 :     Upstream Proxy             [OFF]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,093 : 
SessionID[NDA4ODE=] 2016-12-05 11:47:54,097 : [+] Poisoning Options:
SessionID[NDA4ODE=] 2016-12-05 11:47:54,100 :     Analyze Mode               [OFF]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,105 :     Force WPAD auth            [ON]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,107 :     Force Basic Auth           [ON]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,113 :     Force LM downgrade         [OFF]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,115 :     Fingerprint hosts          [OFF]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,121 : 
SessionID[NDA4ODE=] 2016-12-05 11:47:54,123 : [+] Generic Options:
SessionID[NDA4ODE=] 2016-12-05 11:47:54,127 :     Responder NIC              [wlan0mon]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,134 :     Responder IP               [10.0.0.1]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,136 :     Challenge set              [1122334455667788]
SessionID[NDA4ODE=] 2016-12-05 11:47:54,142 :     Don't Respond To Names     ['ISATAP']
SessionID[NDA4ODE=] 2016-12-05 11:47:54,148 : 
SessionID[NDA4ODE=] 2016-12-05 11:47:54,152 : 
SessionID[NDA4ODE=] 2016-12-05 11:47:54,155 : 
SessionID[NDA4ODE=] 2016-12-05 11:47:54,162 : [!] Error starting SSL server on port 443, check permissions or other servers running.
SessionID[NDA4ODE=] 2016-12-05 11:47:54,165 : [+] Listening for events...
SessionID[NDA4ODE=] 2016-12-05 11:47:54,169 : 
SessionID[NDA4ODE=] 2016-12-05 11:55:28,396 :                                          __
SessionID[NDA4ODE=] 2016-12-05 11:55:28,397 :   .----.-----.-----.-----.-----.-----.--|  |.-----.----.
SessionID[NDA4ODE=] 2016-12-05 11:55:28,398 :   |   _|  -__|__ --|  _  |  _  |     |  _  ||  -__|   _|
SessionID[NDA4ODE=] 2016-12-05 11:55:28,398 :   |__| |_____|_____|   __|_____|__|__|_____||_____|__|
SessionID[NDA4ODE=] 2016-12-05 11:55:28,399 :                    |__|
SessionID[NDA4ODE=] 2016-12-05 11:55:28,400 : 
SessionID[NDA4ODE=] 2016-12-05 11:55:28,418 :            NBT-NS, LLMNR & MDNS  Responder 2.3.3.0 
SessionID[NDA4ODE=] 2016-12-05 11:55:28,419 : 
SessionID[NDA4ODE=] 2016-12-05 11:55:28,421 :   Author: Laurent Gaffie (laurent.gaffie@gmail.com)
SessionID[NDA4ODE=] 2016-12-05 11:55:28,422 :   To kill this script hit CRTL-C
SessionID[NDA4ODE=] 2016-12-05 11:55:28,423 : 
SessionID[NDA4ODE=] 2016-12-05 11:55:28,424 : 
SessionID[NDA4ODE=] 2016-12-05 11:55:28,425 : [+] Poisoners:
SessionID[NDA4ODE=] 2016-12-05 11:55:28,426 :     LLMNR                      [ON]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,427 :     NBT-NS                     [ON]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,428 :     DNS/MDNS                   [ON]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,429 : 
SessionID[NDA4ODE=] 2016-12-05 11:55:28,431 : [+] Servers:
SessionID[NDA4ODE=] 2016-12-05 11:55:28,432 :     HTTP server                [ON]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,433 :     HTTPS server               [ON]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,434 :     WPAD proxy                 [ON]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,436 :     Auth proxy                 [OFF]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,437 :     SMB server                 [ON]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,439 :     Kerberos server            [ON]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,440 :     SQL server                 [ON]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,442 :     FTP server                 [ON]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,444 :     IMAP server                [ON]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,445 :     POP3 server                [ON]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,447 :     SMTP server                [ON]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,449 :     DNS server                 [ON]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,451 :     LDAP server                [ON]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,452 : 
SessionID[NDA4ODE=] 2016-12-05 11:55:28,454 : [+] HTTP Options:
SessionID[NDA4ODE=] 2016-12-05 11:55:28,456 :     Always serving EXE         [OFF]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,458 :     Serving EXE                [OFF]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,460 :     Serving HTML               [OFF]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,463 :     Upstream Proxy             [OFF]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,465 : 
SessionID[NDA4ODE=] 2016-12-05 11:55:28,467 : [+] Poisoning Options:
SessionID[NDA4ODE=] 2016-12-05 11:55:28,471 :     Analyze Mode               [OFF]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,473 :     Force WPAD auth            [ON]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,476 :     Force Basic Auth           [ON]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,478 :     Force LM downgrade         [OFF]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,480 :     Fingerprint hosts          [OFF]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,483 : 
SessionID[NDA4ODE=] 2016-12-05 11:55:28,485 : [+] Generic Options:
SessionID[NDA4ODE=] 2016-12-05 11:55:28,487 :     Responder NIC              [wlan0mon]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,490 :     Responder IP               [10.0.0.1]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,492 :     Challenge set              [1122334455667788]
SessionID[NDA4ODE=] 2016-12-05 11:55:28,495 :     Don't Respond To Names     ['ISATAP']
SessionID[NDA4ODE=] 2016-12-05 11:55:28,497 : 
SessionID[NDA4ODE=] 2016-12-05 11:55:28,502 : 
SessionID[NDA4ODE=] 2016-12-05 11:55:28,505 : 
SessionID[NDA4ODE=] 2016-12-05 11:55:28,507 : [!] Error starting TCP server on port 80, check permissions or other servers running.
SessionID[NDA4ODE=] 2016-12-05 11:55:28,510 : [!] Error starting SSL server on port 443, check permissions or other servers running.
SessionID[NDA4ODE=] 2016-12-05 11:55:28,513 : [+] Listening for events...
SessionID[NDA4ODE=] 2016-12-05 11:55:28,516 :

**Comment by mh4x0f** [comment]
![](http://images.virgula.uol.com.br/2015/11/01.gif)

**Comment by userdsp** [comment]
The problem is [!] Error starting SSL server on port 443, check, but port 443 is not used by any other service!
