### ISSUE TITLE
exclude a domain on DNS Spoof

### ISSUE THREAD

**Issue by jeretc** [P0cL4bs/WiFi-Pumpkin-deprecated#132]
## What's the problem (or question)?

*hi is it possible while doing an attack, on dns spoof to exclude a domain?*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):tplink722n
* Version used tool: 0.8.3
* Virtual Machine (yes or no and which): no
* Operating System and version: parrotsec

**Comment by mh4x0f** [comment]
No.
