### ISSUE TITLE
This doesn't work in my linux mint rosa (ubuntu 14.04)

### ISSUE THREAD

**Issue by merlinnusr** [P0cL4bs/WiFi-Pumpkin-deprecated#138]
I use this command 
>sudo  wifi-pumpkin

this message is displayed 

>PyQt4 app looks different when running with root, because of that the GUI not work 100%, some features not work. I don't find anything code or settings for fix this bug (if you have any solution for this send me feedback :D).
if you want keep the normal user style, run app with "sudo".

**Comment by merlinnusr** [comment]
>CPU~Dual core Intel Celeron N2830 (-MCP-) speed/max~1199/2415 MHz Kernel~3.19.0-32-generic x86_64 Up~32 min Mem~1095.5/1884.5MB HDD~500.1GB(13.6% used) Procs~170 Client~Shell inxi~2.2.28

**Comment by merlinnusr** [comment]
CPU~Dual core Intel Celeron N2830 (-MCP-) speed/max~1199/2415 MHz Kernel~3.19.0-32-generic x86_64 Up~32 min Mem~1095.5/1884.5MB HDD~500.1GB(13.6% used) Procs~170 Client~Shell inxi~2.2.28

**Comment by merlinnusr** [comment]
CPU Dual core Intel Celeron N2830 (-MCP-) speed/max 1199/2415 MHz Kernel 3.19.0-32-generic x86_64 Up 32 min Mem 1095.5/1884.5MB HDD 500.1GB(13.6% used) Procs 170 Client Shell inxi 2.2.28

**Comment by timschumi** [comment]
What happens if you start it by using the Desktop Icon? Also, wifi-pumpkin should show the sudo prompt automatically, so there is no need to do "sudo wifi-pumpkin". Just "wifi-pumpkin" should be enough.

**Comment by merlinnusr** [comment]
@TimSchumi This request me a password but doesn't happen after

**Comment by merlinnusr** [comment]
@TimSchumi This request me a password but nothing happens

**Comment by timschumi** [comment]
And what happens if you put in the password of your account? If this doesn't work, there is something wrong with your system

**Comment by mh4x0f** [comment]
@merlinnusr go to directory the WiF-Pumpkin (**/usr/share/WiFi-Pumpkin/**) and remove this [line](https://github.com/P0cL4bs/WiFi-Pumpkin/blob/master/wifi-pumpkin.py#L48) from the file wifi-pumpkin.py

**Comment by merlinnusr** [comment]
I know what is the problem I have three versions of pip I modify the script to force pip2 

>	pip install -r requirements.txt


>	pip2 install -r requirements.txt

**Comment by merlinnusr** [comment]
https://github.com/P0cL4bs/WiFi-Pumpkin/blob/master/installer.sh
