### ISSUE TITLE
Disconnect device under "stations"

### ISSUE THREAD

**Issue by jeretc** [P0cL4bs/WiFi-Pumpkin-deprecated#141]
## What's the problem (or question)?

*hi is it possible to make a disconnect button under stations to disconnect unwanted devices? *

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: 
* Virtual Machine (yes or no and which): 
* Operating System and version:

**Comment by mh4x0f** [comment]
No.
