### ISSUE TITLE
wifi-pumpkin port to nethunter?

### ISSUE THREAD

**Issue by jeretc** [P0cL4bs/WiFi-Pumpkin-deprecated#142]
## What's the problem (or question)?

*Hi this is not an issue. Will there be a nethunter version ? would be great on nethunter. thanks.*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: 
* Virtual Machine (yes or no and which): 
* Operating System and version:

**Comment by timschumi** [comment]
If python and all the other dependencies are available for NetHunter, the program will most likely work too. The only thing that needs to be checked, is if a external WiFi Card is needed

**Comment by jeretc** [comment]
Yes it requires a compatible external wifi card. I have that too.  Would
like yo test it out.

Thanks

**Comment by mh4x0f** [comment]
No.
