### ISSUE TITLE
Unable to connect to the AP Ubuntu 16.04

### ISSUE THREAD

**Issue by ghost** [P0cL4bs/WiFi-Pumpkin-deprecated#143]
## What's the problem (or question)?

Everything is working fine, I can set up the AP and it shows up, however if I try to connect to it, it my android and Windows phone are not able to get the IP, they keep trying endless. 

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): AP is supported
* Version used tool: 
* Virtual Machine (yes or no and which): no
* Operating System and version: Ubuntu 16.04

**Comment by mh4x0f** [comment]
try to change in Settings-General -> DNSServer to "isc dhcp server (dhcpd)" option and if you receive the error msg  "dhcpd is not installed" type in terminal this command:
``` sh
sudo apt-get install isc-dhcp-server
```
after that you can to run again the AP.
