### ISSUE TITLE
imei identification

### ISSUE THREAD

**Issue by iambattmann** [P0cL4bs/WiFi-Pumpkin-deprecated#145]
## What's the problem (or question)?

Hello, this is not an issue. Do you plan to imei identification, if it present in the traffic?

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: 
* Virtual Machine (yes or no and which): 
* Operating System and version:

**Comment by timschumi** [comment]
AFAIK, the IMEI is not sent via WiFi, because this would be a huge security hole
