### ISSUE TITLE
ImportError : No module named mitmproxy.models 

### ISSUE THREAD

**Issue by shivgori** [P0cL4bs/WiFi-Pumpkin-deprecated#147]
## What's the problem (or question)?

*After update this tool and restart again it show import error:no module named mitmproxy.models*
i tried to install mitmproxy but it not solved 
![screenshot from 2016-12-22 23-00-50](https://cloud.githubusercontent.com/assets/16605439/21434715/fe8f6b96-c89b-11e6-86c5-8794fa735f2d.png)

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):TL-WN722N
* Version used tool: 0.8.4
* Virtual Machine (yes or no and which): NO
* Operating System and version: Ubuntu 16.10

**Comment by mh4x0f** [comment]
you need to install the version 0.17 the mitmproxy
``` sh
sudo pip install mitmproxy==0.17
```
