### ISSUE TITLE
Popup, then nothing happens when running with sudo or gksudo

### ISSUE THREAD

**Issue by Coehill** [P0cL4bs/WiFi-Pumpkin-deprecated#151]
## What's the problem (or question)?

When I run wifi-pumpkin from terminal with sudo or gksudo, I receive a popup titled "`warning: bug GUI Qt :: style`" with the following message:

> 
> PyQt4 app looks different when running with root, because of that the GUI does not work 100%, some features not work. I don't find anything code or settings for fix this bug (if you have any solution for this send me feedback :D).
> 
> if you want keep the normal user style, run app with "sudo".

Upon clicking "OK", nothing happens. When I run it without sudo, I get the following output:

> $ wifi-pumpkin
> Traceback (most recent call last):
>   File "wifi-pumpkin.py", line 41, in <module>
>     check_dep_pumpkin()
>   File "/usr/share/wifi-pumpkin/core/loaders/checker/check_depen.py", line 18, in check_dep_pumpkin
>     copy('settings/source.tar.gz','templates/')
>   File "/usr/lib/python2.7/shutil.py", line 119, in copy
>     copyfile(src, dst)
>   File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
>     with open(dst, 'wb') as fdst:
> IOError: [Errno 13] Permission denied: 'templates/source.tar.gz'

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
> Network:   Card-1: Intel Wireless 7260 driver: iwlwifi bus-ID: 08:00.0
>            IF: wlp8s0 state: up mac: <filter>
>            Card-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller port: 3000 bus-ID: 09:00.0
>            IF: N/A state: N/A speed: N/A duplex: N/A mac: N/A

* Version used tool: 
> blackarch/wifi-pumpkin 156.f8f224d-1
* Virtual Machine (yes or no and which):  
> no
* Operating System and version:  
> $ uname -a
> Linux username-linux 4.9.0-0-MANJARO #1 SMP PREEMPT Mon Dec 12 21:51:38 UTC 2016 x86_64 GNU/Linux

**Comment by mh4x0f** [comment]
@DistantParadox this will solve the problem
