### ISSUE TITLE
Python DNS Server improvements 

### ISSUE THREAD

**Issue by mh4x0f** [P0cL4bs/WiFi-Pumpkin-deprecated#165]
I need help for do test the new pyDNS Server implementation. the current version 0.8.4 is running the dns2proxy because i had some problems with DNS server and i was forced to solve this problem temporarily last commit. so i doing new test with new version the DNS server for add new features.

**Comment by cbogithub** [comment]
DNS lookup failed : address 'wpad' not found 

![dns_error](https://cloud.githubusercontent.com/assets/9572613/21750602/ba37b3bc-d5e9-11e6-8722-d3b83c838316.png)


#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): TP-link  model WN821N
* Version used tool: 0.8.4
* Virtual Machine (yes or no and which): WMware
* Operating System and version: Kali linux 2016.2

**Comment by mh4x0f** [comment]
@TimSchumi Could you do some tests in your systems?

**Comment by timschumi** [comment]
Of course

By the way, could we message through something other, e.g. directly by E-Mail? This would be much easier than through the Issues

**Comment by mh4x0f** [comment]
ok, I'll send the version .zip with pydns server implementation coming soon.

**Comment by mh4x0f** [comment]
I add the version BETA test in Release tab, **wifi-pumpkin_0.8.4.2Beta_all.deb** I think it's best to use the same issue. check if AP share internet and look DNS Query logger in terminal.

**Comment by timschumi** [comment]
DNS Logger and Network Access work!

**Comment by mh4x0f** [comment]
ok, did you try with which OS ?

**Comment by timschumi** [comment]
Ubuntu 16.04 and Kali Linux 2016.2

**Comment by mh4x0f** [comment]
nice, thank's brown. I'll add news features coming soon. 
if you do some test with another system, send me please

**Comment by mh4x0f** [comment]
@TimSchumi Did you succeed install mitmproxy 0.17 normally on Kali Linux 2016.2. because a lot of people are reporting this bug.

**Comment by timschumi** [comment]
I had to install it on the dirty way, not sure hiw I made it

**Comment by mh4x0f** [comment]
ok, I'll download the Kali 2016.2 and make somes test.
