### ISSUE TITLE
Copy HTTP-Requests

### ISSUE THREAD

**Issue by GGGunrunner** [P0cL4bs/WiFi-Pumpkin-deprecated#167]
Thanks for updating WIFI-Pumpkin!

A quick question: Is it possible to copy/save HTTP Requests from the Monitor window?

Right-click and other ways dont do anything. Thanks!

**Comment by mh4x0f** [comment]
the all data in HTTP Requests are saved in **logs/AccessPoint/urls.log**. but  I'll add this option for edit line with two clicks.
