### ISSUE TITLE
support python3

### ISSUE THREAD

**Issue by blshkv** [P0cL4bs/WiFi-Pumpkin-deprecated#174]
It's getting more and more difficult to support tools which are python2.7 only. In particular, the latest version of mitmproxy runs on python3 and above. Please support a more decent version as well
Thank you.

**Comment by mh4x0f** [comment]
I think that is not possible to implement, the project got too very bigger for change of that type. also, most plugin has been implemented python2.

**Comment by blshkv** [comment]
It's never too late especially for small projects like yours.  Python 2 is the dead end which will happen  in 2020 (supposed to come in 2015 initially)

**Comment by mh4x0f** [comment]
AFAIK, the python 2 will receive security updates until 2020 when its support will be discontinued. only this.

**Comment by blshkv** [comment]
I still think you should change your mind and made an effort to migrate.

There are more and more dependences which you use support python3. Some of them, like mitmproxy (which is the main dep) does not even support python2 anymore.

**Comment by blshkv** [comment]
https://pythonclock.org/
