### ISSUE TITLE
Can't start "/etc/NetworkManager/NetworkManager.conf"

### ISSUE THREAD

**Issue by CaptainStony** [P0cL4bs/WiFi-Pumpkin-deprecated#180]
I can't start the AP , I get the error with header "Network Information". I don't get what it means

I am using 2 random wireless cards, but I don't think those are the problem. As OS I am using the latest kali linux.

Thanks for reading and please send help...

**Comment by timschumi** [comment]
Try it first with one Wifi Card (https://github.com/P0cL4bs/WiFi-Pumpkin/wiki/Installation#2-wifi-wireless-adapter)
