### ISSUE TITLE
Wifi-Pumpkin not working  on Parrot Sec Os  3.4.1 ## edit: manually initialize wireless card for AP in monitor mode first.. works perfect

### ISSUE THREAD

**Issue by killheart1** [P0cL4bs/WiFi-Pumpkin-deprecated#181]
## What's the problem (or question)?

Hello Wifi-Pumpkin  Dev team :smiley:   I greatly appreciate the work and effort,  however
  Can't get it to run on  Pentesting linux operating system **Parrot Sec Os**...

I  always get this message::

WiFi-Pumpkin/settings/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started

  I have spent much time trying to fix this with no succes and other software that uses the hostapd nl80211 driver works fine on Parrot Sec Os...

#### My environment.
*
wireless card fully support AP mode 
(Qualcom Atheros QCA9565 / AR9565)
 driver=ath9k        driver version=4.8.0-parrot-amd64

* wifi-pumpkin works fine on kali linux using the same hardware configuration, whether it be in a VM or otherwise... just wont work on Parrot Sec Os

* Operating System and version: 
   Parrot Sec Os 3.4.1  amd64

**Comment by killheart1** [comment]
Wifi-Pumpkin seems  to be working fine  on Parrot Sec Os 3.4.1  
 just need to manually  initialize wireless card for AP in monitor mode first..

**Comment by mh4x0f** [comment]
I'll add fix for this bug coming soon

**Comment by killheart1** [comment]
Awesome :smiley:  thank you

**Comment by mh4x0f** [comment]
@killheart1 Which method did you use for set card in AP monitor? airmon-ng check kill ?

**Comment by killheart1** [comment]
I did not use airmon-ng check kill ... (should i?)

the method  i used for set card  in  AP  to monitor mode was : airmon-ng start  (card-for-AP)
   example: airmon-ng start wlan0

![screenshot at 2017-02-01 13-53-14](https://cloud.githubusercontent.com/assets/25432585/22525819/765cc53a-e88e-11e6-94c0-1815c266433f.png)


Then i initialize Wifi-Pumpkin (or refresh network adapter selection menu if Wifi-Pumpkin was already initialized before putting card for AP in monitor mode)


![screenshot at 2017-02-01 13-55-00](https://cloud.githubusercontent.com/assets/25432585/22526037/4e5cd452-e88f-11e6-83ea-f1435aec6ef0.png)


Works great :smiley:
