### ISSUE TITLE
Fonts are too big

### ISSUE THREAD

**Issue by GGGunrunner** [P0cL4bs/WiFi-Pumpkin-deprecated#183]
Ubuntu Mate on Razzie Pi 3

When connecting over VNC, the fonts and boxes are too big to fit.

Is it Pumpkin, or smth is wrong with window manager?

![untitled](https://cloud.githubusercontent.com/assets/19638286/22653328/9c4c7106-ecbb-11e6-9c30-2ef0dd2393df.png)

**Comment by mh4x0f** [comment]
which command you are running?

**Comment by GGGunrunner** [comment]
Sorry, I didnt quite get the question. Command?

./wifi-pumpkin

**Comment by mh4x0f** [comment]
Are you running with root or user ?

**Comment by GGGunrunner** [comment]
You were right on that - i was running it via "su", and it was the cause of problem.

With "sudo" everything works fine. Solved.
