### ISSUE TITLE
gui of wifi-pumpkin not visible

### ISSUE THREAD

**Issue by Treco-one** [P0cL4bs/WiFi-Pumpkin-deprecated#185]
## What's the problem (or question)?

i m not able to see anyting for except the wifi-pumpkin window n that too with a black screen with nothing visible

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: wifi-pumpkin-0.8.3 it happens on every version
* Virtual Machine (yes or no and which): no dual boot kali and windows 7
* Operating System and version: kali 2.2016 rolling 
![wifi-pumpkin](https://cloud.githubusercontent.com/assets/25605626/22682774/b791a952-ed3a-11e6-8285-c0fb28d60010.png)

**Comment by timschumi** [comment]
Uninstall Version 0.8.3 and install 0.8.4 through the installer script. There may be some missing dependencies

**Comment by Treco-one** [comment]
I'll  try this one, 
but I've tried most of the previous versions and it met the same problem 
Still I'll try 
Regards

**Comment by Treco-one** [comment]
i installed 0.8.4 through the installer script but it showed the same error
Loading GUI...
WiFi-Pumpkin Running!
X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    130 (MIT-SHM)
  Minor opcode: 1 (X_ShmAttach)
  Resource id:  0x141
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 5 (X_ShmCreatePixmap)
  Resource id:  0x1000019
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x100001a
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x100001a
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x100001a
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x100001a
i tried the fix shown in 
BadDrawable (invalid Pixmap or Window parameter) #53
by adding 
export QT_X11_NO_MITSHM=1 in 
~/.profile file
but still the error remains the same
Regards

**Comment by Treco-one** [comment]
Help me guyz

**Comment by timschumi** [comment]
Did you try this: http://www.stackoverflow.com/questions/18429484/pyqt4-x-errors-when-starting-aplication
?

**Comment by Treco-one** [comment]
Thanks for the reply,   
I tried it but i didn't helped 
Is there any other way?  Help me out guyz

**Comment by timschumi** [comment]
Then it's a specific problem with your setup

**Comment by mh4x0f** [comment]
run the app without gksudo command. execute "sudo wifi-pumpkin".

**Comment by Treco-one** [comment]
With sudo i can see the above error as u can see in the screenshot I've mentioned 
But wether i use gksudo or sudo the interface doesn't seems to work
Regards

**Comment by godrockz** [comment]
i had the same issues with the vncserver. solved with(not recommend): 
[root@alarmpi alarm]# /usr/bin/vncserver -geometry 1440x900 -alwaysshared -fg
after login: xhost + and now start wifi-pumpkin

note: QT can't elevate permission to access some shared memory, because X is running with user privileges - start X as root and it will work

**Comment by SaulAgui** [comment]
getting the exact same error, tryed all the same options. plz help

**Comment by becare** [comment]
sudo nano /etc/environment

Add this line
QT_X11_NO_MITSHM=1

Enjoy!

**Comment by ArnoldSkylake** [comment]
> sudo nano /etc/environment
> 
> Add this line
> QT_X11_NO_MITSHM=1
> 
> Enjoy!

BRO, THIS HELP ME !!!!
Thaaaaanks

**Comment by u666sa** [comment]
> sudo nano /etc/environment
> 
> Add this line
> QT_X11_NO_MITSHM=1
> 
> Enjoy!

Thank you so much for this one! Fedora 30 is running pumpkin!

**Comment by Arturo0x90** [comment]
yoooo thanks this fix helps!! i have try to run in ubuntu/kali 64 and it works:)
