### ISSUE TITLE
Use of external wifi usb adapter

### ISSUE THREAD

**Issue by shivgori** [P0cL4bs/WiFi-Pumpkin-deprecated#190]
## What's the problem (or question)?

*I want to use wlan0 (internal card) to connect to Internet (with my phone as a Wi-Fi Hotspot) and a second physical Wifi adapter (tplink WN722N) to create the fake AP and make all stuff provided by wifi-pumpkin.*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):tplink WN722N
* Version used tool: 0.8.4
* Virtual Machine (yes or no and which): no
* Operating System and version: ubuntu 16.10

**Comment by timschumi** [comment]
This is already built into the Program.
In the Settings Dialog, there should be a drop-down box where you can select your Adapter

**Comment by shivgori** [comment]
it show this error
![screenshot from 2017-02-21 11-26-34](https://cloud.githubusercontent.com/assets/16605439/23152596/f630b650-f828-11e6-9e7b-85e46bb31116.png)

**Comment by timschumi** [comment]
You might try installing the aircrack-ng suite and run
"(sudo) airmon-ng check kill"
But make sure you have connected your wlan0 to your WiFi-Hotspot because this command will probably kill NetworkManager

**Comment by syira7** [comment]
do you need external wireless adapter for you to use Wifi pumpkin? if so how ?
thanks.
