### ISSUE TITLE
Wifi-pumpkin does not start completely 

### ISSUE THREAD

**Issue by Bee1To** [P0cL4bs/WiFi-Pumpkin-deprecated#193]
## What's the problem (or question)?
Wifi-pumpkin does not start completely and cannot detect when I connect to ap with cellphone I have kali 2.0 rolling and using awus036nh usb adapter for wlan1 as fake ap and eth0 for internet access 
*answer here*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: 
* Virtual Machine (yes or no and which): 
* Operating System and version:

**Comment by Bee1To** [comment]
No vm, kali rolling 2016.1, wifi-pumpkin version  0.8.4

**Comment by Bee1To** [comment]
![screenshot from 2017-02-23 17-35-14](https://cloud.githubusercontent.com/assets/5317088/23289414/3f1bee30-f9fe-11e6-9971-7c12b1ec5ee2.png)

**Comment by mh4x0f** [comment]
it needs mitmproxy 0.17
``` sh
sudo pip install mitmproxy==0.17
```
