### ISSUE TITLE
unable to connect to pumkin wifi 

### ISSUE THREAD

**Issue by kunz398** [P0cL4bs/WiFi-Pumpkin-deprecated#194]
## i have successfully started Wifi-pumkin and it is showing up in my phone but when i try to connect it it cant connect 
i was able to do it before but i had to install a brand new linuxs
this is the error i get in the terminal

Traceback (most recent call last):
  File "/root/WiFi-Pumpkin/core/main.py", line 1433, in Start_PumpAP
    thread.start()
  File "/root/WiFi-Pumpkin/core/utility/threads.py", line 265, in start
    config = proxy.ProxyConfig(port=8080,mode='transparent')
TypeError: __init__() got an unexpected keyword argument 'mode'
^CTraceback (most recent call last):
  File "/root/WiFi-Pumpkin/core/utility/threads.py", line 217, in read_OutputCommand
    @pyqtSlot()
KeyboardInterrupt

#### Please tell us details about your environment.
* VirtualBox Version 5.1.14 r112924 (Qt5.6.2)

**Comment by mh4x0f** [comment]
VirtualBox got some bugs, try with Vmware.

**Comment by ghost** [comment]
I have the same problem 
OS: Parrot OS

**Comment by kunz398** [comment]
I will change the virtual box then update
