### ISSUE TITLE
update version mitmproxy 0.17 to 0.18.2

### ISSUE THREAD

**Issue by mh4x0f** [P0cL4bs/WiFi-Pumpkin-deprecated#195]
I'm receive a lot report bug the version **mitmproxy 0.17** is default on **WP 0.8.4**. because of this, I 'll update for version 0.18.2 but for make this i need to do some test in different OS based in Debian (**Kali Linux 2016.2**,Parrot 3.4 e etc). OBS: I already did the implementation the code for support mitmproxy 18.2.

**Comment by jeretc** [comment]
└──╼ $sudo pip install mitmproxy==0.18.2
[sudo] password for parrot: 
Requirement already satisfied: mitmproxy==0.18.2 in /usr/lib/python2.7/dist-packages
Requirement already satisfied: enum34<2,>=1.0.4 in /usr/lib/python2.7/dist-packages (from mitmproxy==0.18.2)
Requirement already satisfied: ipaddress<1.1,>=1.0.15 in /usr/lib/python2.7/dist-packages (from mitmproxy==0.18.2)
Requirement already satisfied: typing==3.5.2.2 in /usr/lib/python2.7/dist-packages (from mitmproxy==0.18.2)


Traceback (most recent call last):
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 1433, in Start_PumpAP
    thread.start()
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 265, in start
    config = proxy.ProxyConfig(port=8080,mode='transparent')
TypeError: __init__() got an unexpected keyword argument 'mode'

**Comment by mh4x0f** [comment]
- mitmproxy 0.18.2 installation 

| OS | Description |
| --- | --- |
| Parrot OS 3.4.1 | supported |
| Ubuntu 15.10 | supported |
| WifiSlax 4.11 | supported |
| Kali Linux 2016.1  | supported |
| Kali Linux 2016.2  | supported |

**Comment by mh4x0f** [comment]
@TimSchumi could you try install mitmproxy 0.18.2 on kali 2016.2?

**Comment by shivgori** [comment]
after update it gives error
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 45, in <module>
    from core.main import Initialize
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 31, in <module>
    from core.widgets.tabmodels import (
  File "/usr/share/WiFi-Pumpkin/core/widgets/tabmodels.py", line 7, in <module>
    from core.utility.threads import ThreadPopen
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 19, in <module>
    from core.servers.proxy.controller.handler import MasterHandler
  File "/usr/share/WiFi-Pumpkin/core/servers/proxy/controller/handler.py", line 43, in <module>
    class MasterHandler(flow.FlowMaster):
  File "/usr/share/WiFi-Pumpkin/core/servers/proxy/controller/handler.py", line 87, in MasterHandler
    @controller.handler
AttributeError: 'module' object has no attribute 'handler'

**Comment by mh4x0f** [comment]
@shivgori Update mitmproxy to 0.18.2.
``` sh
sudo pip install mitmproxy==0.18.2 
```

**Comment by jeretc** [comment]
@mh4x0f re-installed it working fine now. thanks

**Comment by shivgori** [comment]
thanks after reinstalled it works perfect

**Comment by BarAluf** [comment]
hi everyone.
i want to upgrade mitm from version 2.0.2 to version 4.
this is the error module 'mitmproxy.controller' has no attribute 'handler'.
how can i easily convert this.
