### ISSUE TITLE
MITMPROXY and PumpkinProxy Error

### ISSUE THREAD

**Issue by ghost** [P0cL4bs/WiFi-Pumpkin-deprecated#196]
## What's the problem (or question)?

when i installed wifi pumpkin i got this error:
  Failed building wheel for cryptography

  Failed building wheel for pillow

and

Can't rollback cryptography, nothing uninstalled.
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Rc6x83/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-gqHQ93-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Rc6x83/cryptography/

and when i start the program it says on Pumpkin Proxy it says:
Traceback (most recent call last):
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 1433, in Start_PumpAP
    thread.start()
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 265, in start
    config = proxy.ProxyConfig(port=8080,mode='transparent')
TypeError: __init__() got an unexpected keyword argument 'mode'

Thank you for your help.

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):TP-LINK TL-WN722N
* Version used tool: V0.8.4
* Virtual Machine (yes or no and which): No 
* Operating System and version: Parrot Security OS 3.4.1

**Comment by mh4x0f** [comment]
try this:
```sh 
sudo apt-get install python-pip python-dev libffi-dev libssl-dev libxml2-dev libxslt1-dev
```
and now install mitmproxy.
``` sh 
sudo pip install mitmproxy==0.17
```

**Comment by ghost** [comment]
Tried the first command and this comes up:
sudo apt-get install python-pip python-dev libffi-dev libssl-dev libxml2-dev libxslt1-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libffi-dev is already the newest version (3.2.1-6).
libssl-dev is already the newest version (1.1.0e-1).
libxml2-dev is already the newest version (2.9.4+dfsg1-2.2).
libxslt1-dev is already the newest version (1.1.29-2).
python-dev is already the newest version (2.7.13-2).
python-pip is already the newest version (9.0.1-2).
0 upgraded, 0 newly installed, 0 to remove and 1235 not upgraded.

and i still have the same error.

**Comment by jeretc** [comment]
└──╼ $sudo apt-get install python-pip python-dev libffi-dev libssl-dev libxml2-dev libxslt1-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libffi-dev is already the newest version (3.2.1-6).
libssl-dev is already the newest version (1.1.0d-2).
libxml2-dev is already the newest version (2.9.4+dfsg1-2.2).
libxslt1-dev is already the newest version (1.1.29-2).
python-dev is already the newest version (2.7.13-2).
python-pip is already the newest version (9.0.1-2).
0 upgraded, 0 newly installed, 0 to remove and 1025 not upgraded.

yes, same here.. no difference problem still persist.

**Comment by mh4x0f** [comment]
try install the version 0.18.2 the mitmproxy.
``` sh
sudo pip install mitmproxy==0.18.2
```
if work fine I 'll add the version with mitmproxy updated.

**Comment by jeretc** [comment]
$sudo pip install mitmproxy==0.18.2
[sudo] password for parrot: 
Requirement already satisfied: mitmproxy==0.18.2 in /usr/lib/python2.7/dist-packages
Requirement already satisfied: enum34<2,>=1.0.4 in /usr/lib/python2.7/dist-packages (from mitmproxy==0.18.2)
Requirement already satisfied: ipaddress<1.1,>=1.0.15 in /usr/lib/python2.7/dist-packages (from mitmproxy==0.18.2)
Requirement already satisfied: typing==3.5.2.2 in /usr/lib/python2.7/dist-packages (from mitmproxy==0.18.2)

**Comment by mh4x0f** [comment]
OK, Parrot OS already support mitmproxy 0.18.2 by default. now I need to try install this module in Kali Linux 2016.2 and if work fine I'll update this.

**Comment by jeretc** [comment]
but the error still remains.

**Comment by mh4x0f** [comment]
@jeretc Logic, as I said above I will still add the new version with support for mitmproxy 0.18.2 wait

**Comment by jeretc** [comment]
right ..

**Comment by nedege** [comment]
problem pupkin-proxy not working in kali-linux-xfce-W07-amd64
removed in requierments.txt
mitmproxy==0.17
and install wifi-pumpkin 
remove mitmproxy from kali
apt-get autoremove mitmproxy
install this
apt-get install libpq-dev python-dev libxml2-dev libxslt1-dev libldap2-dev libsasl2-dev libffi-dev libtiff5-dev libjpeg62-turbo-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk
download from https://github.com/mitmproxy/mitmproxy/releases
mitmproxy 0.17 unzip and install
this will fail but dont worry 
reinstall mitmproxy
apt-get install mitmproxy
now pupkin proxy is working

why i don`t know

**Comment by ghost** [comment]
I fixed the problem by doing:

sudo apt-get install python3-dev python3-pip libffi-dev libssl-dev
sudo pip3 install mitmproxy  # or pip3 install -- user mitmproxy

which installed mitmproxy v2.0 and it works :)

**Comment by nedege** [comment]
verified working on kali-linux-xfce-2016.2-amd64
still have removed 
mitmproxy==0.17
thanks

**Comment by jeretc** [comment]
@PhantomXMT i get this error

└──╼ $sudo pip3 install mitmproxy
Collecting mitmproxy
  Using cached mitmproxy-2.0.0-py3-none-any.whl
Collecting h2<3,>=2.5.1 (from mitmproxy)
  Using cached h2-2.6.0-py2.py3-none-any.whl
Collecting certifi>=2015.11.20.1 (from mitmproxy)
  Using cached certifi-2017.1.23-py2.py3-none-any.whl
Requirement already satisfied: pyasn1<0.3,>=0.1.9 in /usr/lib/python3/dist-packages (from mitmproxy)
Collecting tornado<4.5,>=4.3 (from mitmproxy)
  Using cached tornado-4.4.2.tar.gz
Collecting cssutils<1.1,>=1.0.1 (from mitmproxy)
  Using cached cssutils-1.0.1.tar.gz
Collecting watchdog<0.9,>=0.8.3 (from mitmproxy)
  Using cached watchdog-0.8.3.tar.gz
Collecting pyperclip<1.6,>=1.5.22 (from mitmproxy)
  Using cached pyperclip-1.5.27.zip
    Complete output from command python setup.py egg_info:
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code -11 in /tmp/pip-build-q0ul_530/pyperclip/

**Comment by ghost** [comment]
Well idk for me it worked

**Comment by mh4x0f** [comment]
#195 solved now.

**Comment by erfirojsiddiki** [comment]
> try install the version 0.18.2 the mitmproxy.
> 
> ```shell
> sudo pip install mitmproxy==0.18.2
> ```
> 
> if work fine I 'll add the version with mitmproxy updated.

Thanks alot you guys!!! IT WORKED
1. sudo apt install python3-pip
2. sudo apt-get install python-pip python-dev libffi-dev libssl-dev libxml2-dev libxslt1-dev
3. sudo pip install mitmproxy==0.18.2
