### ISSUE TITLE
DNS Spoofer Page Redirection 

### ISSUE THREAD

**Issue by jeretc** [P0cL4bs/WiFi-Pumpkin-deprecated#199]
## What's the problem (or question)?

*Just checking if the dns spoofer page redirection still working? i'm running the phishing manager and dns spoofer but i can't seem to redirect non-https sites to a fake page.

Secondly when device connects to wifi-pumpkin AP, it is not showing under Home or Stations *

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): TP_722N
* Version used tool:  8.4
* Virtual Machine (yes or no and which): no
* Operating System and version: parrotsec 3.5

**Comment by timschumi** [comment]
The Device not showing up is a problem of the DHCP Server. Try switching it in the Settings

**Comment by mh4x0f** [comment]
>  i can't seem to redirect non-https sites to a fake page

![1062](https://cloud.githubusercontent.com/assets/6795613/23613791/9d4244c8-025f-11e7-8d2a-d80967ee65fa.gif)

**Comment by jeretc** [comment]
hmmm.. not sure what it's suppose to mean tho i'm a fan of star wars.

**Comment by timschumi** [comment]
In the move he screams "Nooooooooooooooo"

**Comment by jeretc** [comment]
yesssss!!!

**Comment by jeretc** [comment]
@TimSchumi thanks. it solved both issues.

**Comment by timschumi** [comment]
I don't really know if I added valuable information to solve this but... Ok

**Comment by shivgori** [comment]
hey jeretc, i am also facing same problem how it can be solve

**Comment by jeretc** [comment]
Change the dhcp server under the settings.

**Comment by shivgori** [comment]
what should i change

**Comment by shivgori** [comment]
after select python dhcp server, connected device do not show in home

**Comment by jeretc** [comment]
the dhcp server options, you can select a different dhcp server.

**Comment by jeretc** [comment]
choose another not the python dhcp server. It should work.

**Comment by shivgori** [comment]
k it's work. But only http sites redirect on fake page. HTTPS sites not open

**Comment by jeretc** [comment]
of course, it won't work on https because all modern web browsers has HSTS.

**Comment by andrewjgoss1** [comment]
Hello jeretc and Wifi-Pumpkin dev!
Is there anyway to defeat HSTS of browser?
Wifi-Pumpkin dev said "added new bypass HSTS by LeonardoNve sslstrip feature".
I don't know if I can use dnsspoof and sslstrip at a same time?

**Comment by jeretc** [comment]
I have not tried that. You can get it to work with bettercap and
wifi-pumpkin.

**Comment by andrewjgoss1** [comment]
Hello jeretc,I don't know how to redirect with DNSSpoof.
First,I start AP,then start Phising and DNSSpoof.I check Redirect for all sites,but only when I go  10.0.0.1,the page show the index.html.When I go google.comor all other sitse the page doesn't return.

**Comment by andrewjgoss1** [comment]
I want to use evil twin(fluxion with SSL)to hack wifi,but Chrome has HSTS.
So I'm trying to make Wifi-Pumpkin to redirect to my evil twin page because Wifi-Pumpkin can defeat HSTS

**Comment by jeretc** [comment]
It should work for google.com. Try changing the dhcp server under settings.

**Comment by andrewjgoss1** [comment]
Thanks jeretc!

**Comment by andrewjgoss1** [comment]
Hello admins,
When the victim go to HTTPS website,the redirection does not work.So I want Dnsspoofer redirect only HTTP and when victim go to HTTPS website,victim can still access that website.
Can you help me config Wifi-Pumpkin and Dnsspoofer to redirect with only HTTP?
Thanks you so much!
