### ISSUE TITLE
Object has no attribute...

### ISSUE THREAD

**Issue by kkar** [P0cL4bs/WiFi-Pumpkin-deprecated#204]
## What's the problem (or question)?

After running wifi-pumpkin via sudo, i get an **AttributeError: 'module' object has no attribute 'OP_NO_TLSv1_1'** at **line 45** of wifi-pumpkin.py.

Any ideas?

**Comment by mh4x0f** [comment]
try update pyopenssl module this:

``` sh 
pip install --upgrade pyopenssl
```
