### ISSUE TITLE
Hint I update the software after the installation is complete, updated open like this again

### ISSUE THREAD

**Issue by wirelessice** [P0cL4bs/WiFi-Pumpkin-deprecated#207]
## What's the problem (or question)?
![_20170330161712](https://cloud.githubusercontent.com/assets/15224281/24494521/21808264-1565-11e7-923f-9f7f0a00f15a.png)
   @controller.handler
AttributeError: 'module' object has no attribute 'handler'

*answer here*
ubuntu 14.04

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: 
* Virtual Machine (yes or no and which): 
* Operating System and version:

**Comment by wirelessice** [comment]
Service_identity has been installed

**Comment by mh4x0f** [comment]
solution: https://github.com/P0cL4bs/WiFi-Pumpkin/issues/195#issuecomment-284147071
