### ISSUE TITLE
network adapter not detected on wifi pumpkin

### ISSUE THREAD

**Issue by madisonbennett** [P0cL4bs/WiFi-Pumpkin-deprecated#209]
## What's the problem (or question)?

*parrot not detecting any interfaces but my guest virtual machine parrot detects both network interfaces. I have one external usb supported wifi card and an internal wifi. i have tried both NAT & Bridge method. The results the same, network adapter not detected under wifi pumpkin.*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):TL722N
* Version used tool: 8.4
* Virtual Machine (yes or no and which): yes
* Operating System and version:  parrot 3.4.1
![parrot-1](https://cloud.githubusercontent.com/assets/27149615/24850528/02f4d9f2-1e03-11e7-811d-b4454c05bf62.png)
![parrot-2](https://cloud.githubusercontent.com/assets/27149615/24850529/03367092-1e03-11e7-9480-5ff52755c24d.png)

**Comment by mh4x0f** [comment]
> parrot not detecting any interfaces but my guest virtual machine parrot detects both network interfaces.

This problem has nothing to do with the tool. if ifconfig command is not detecting interface, the tool also will not detect either.
