### ISSUE TITLE
after device connected in home menu no device show

### ISSUE THREAD

**Issue by shivgori** [P0cL4bs/WiFi-Pumpkin-deprecated#212]
## What's the problem (or question)?
I change both dhcp server but device not show

*answer here*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): tp lnk722n
* Version used tool: latest
* Virtual Machine (yes or no and which): no
* Operating System and version: ubuntu

**Comment by mh4x0f** [comment]
if you try with dhcp server and doesn't work, probably the problem is you device. did you try connect another device on AP?

**Comment by shivgori** [comment]
yes i also used another device but problem not solve

**Comment by mh4x0f** [comment]
ok, try this: 
using the options dhcp-server start PumpAP, connect the device and execute this command on terminal:
``` sh
cat /var/lib/dhcp/dhcpd.leases
```
send-me the output

**Comment by shivgori** [comment]
I uninstall first and again install this tool and now it's working fine.

sorry for late reply
