### ISSUE TITLE
SSID not visible

### ISSUE THREAD

**Issue by raulpresa** [P0cL4bs/WiFi-Pumpkin-deprecated#213]
## What's the problem (or question)?

USB card is ok, and support AP, I run wifi-pumpkin but cant find the SSID in the list of available access points

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):ENCORE (USB) N150 adapter.  Supports AP/mode
* Version used tool: 0.8.4
* Virtual Machine (yes or no and which): yes, KALI 2017
* Operating System and version: kali 2017

**Comment by mh4x0f** [comment]
> Virtual Machine (yes or no and which): yes, KALI 2017

What software are you using?

**Comment by raulpresa** [comment]
Oracle Virtual box

Enviado desde mi iPhone

El 27 abr. 2017, a las 21:42, Marcos Nesster <notifications@github.com<mailto:notifications@github.com>> escribió:


Virtual Machine (yes or no and which): yes, KALI 2017

do you using which software for create Virtual Machine ?

**Comment by mh4x0f** [comment]
maybe, this is the problem "Oracle Virtual box". I had some bugs this type when I use this software and  I don't know how to solve this problem. I recommend that you use VMware.

**Comment by raulpresa** [comment]
Ok. I'll try with a fresh ubuntu vm and if it fail, I'll try VMware.
Thank you for your help
Kind regards,

Enviado desde mi iPhone

El 27 abr. 2017, a las 22:47, Marcos Nesster <notifications@github.com<mailto:notifications@github.com>> escribió:


maybe, this is the problem "Oracle Virtual box". I had some bugs this type when I use this software and I don't know how to solve this problem. I recommend that you use VMware.
