### ISSUE TITLE
Error | Help

### ISSUE THREAD

**Issue by samirelatabeh** [P0cL4bs/WiFi-Pumpkin-deprecated#224]
## What's the problem (or question)?
Hi , I'm Samir and I am facing a problem regarding the internet connection created by wifi-pumpkin , everytime I connect to the internet for penetration testing I dont have internet connection but it says that my phone was connected

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): None
* Version used tool: idk
* Virtual Machine (yes or no and which): no
* Operating System and version: Kali Linux

**Comment by mh4x0f** [comment]
try this : [#187 comment change DHCP option](https://github.com/P0cL4bs/WiFi-Pumpkin/issues/187#issuecomment-280879650)
