### ISSUE TITLE
Issues with gui

### ISSUE THREAD

**Issue by Jinovas** [P0cL4bs/WiFi-Pumpkin-deprecated#225]
For whatever reason, keep getting errors spammed in my terminal after trying to run it as regular user and root. All depancies are met. Tried just about everything I could find online related to the issue. Something wrong with the QT engine or something. Keep getter blank window popping up and that's as much as I see. It looks to be a popular issue with some memory sharing error. I'll try to post it in a bit. 

Running latest kali build 4.9.0-kali4/update.

**Comment by mh4x0f** [comment]
Based on a google search this looks like a Qt/KDE problem. Alternatively, if possible, try a different OS/distro.
