### ISSUE TITLE
Not DNSSpoof with HTTPS

### ISSUE THREAD

**Issue by andrewjgoss1** [P0cL4bs/WiFi-Pumpkin-deprecated#227]
## What's the problem (or question)?
Because HTTPS does not work with DNSSpoof,I want to use DNSSpoof redirect only HTTP site
(when victim go to HTTPS website,victim can access that website)
Admin,can you please walkthrough?
* Virtual Machine (yes or no and which): No
* Operating System and version: Wifislax

**Comment by mh4x0f** [comment]
![kkk](http://3.bp.blogspot.com/-v4PxJXZ8Yu4/Tnuoe9bItCI/AAAAAAAAATU/Nmtsf8kPjuQ/s400/eu-rindo.gif)
