### ISSUE TITLE
maybe a bug?

### ISSUE THREAD

**Issue by nemew** [P0cL4bs/WiFi-Pumpkin-deprecated#241]
Ok so I will try to recreate the problem as best as I can.

-I installed wifi-pumpkin on kali on VM.
-I start the AP and run phishing manager + dns spoofer after setting up a mysql database with fake authent site.
-on class-A-address my device won't show up on my station list, but dns spoofer detects it? on Class-B-address it shows up under stations and client number =1. 
- with class-A-address when I use the fake-auth to sign in nothing appears under activity monitor's credential list
-I tried class-B-address but the dns spoofer doesnt work
-I switch back to class-A-address and start the ap + phishing manager server + dns spoofer. It works but does not detect credentials
-So I though I could find it somewhere in the server files. I used Nikto through Burpsuite proxy to scan the phishing manager server. This caused Wifi-pumpkin to crash while scanning.
-I stop Nikto and burpsuite. I restart wifi-pumpkin
-Now it starts the AP but phishing manager has an error "[Fri Jun 16 00:55:50 2017] Failed to listen on 10.0.0.1:80 (reason: Address already in use)"
-DNS Spoofer gives me an error also 
"Traceback (most recent call last):
  File "core/packets/dnsspoofNF.py", line 96, in <module>
    dnsspoof.main()
  File "core/packets/dnsspoofNF.py", line 91, in main
    self.q.bind(0, self.callback)
  File "netfilterqueue.pyx", line 182, in netfilterqueue.NetfilterQueue.bind (netfilterqueue.c:4388)
OSError: Failed to create queue 0."
- I reinstall Wifi-Pumpkin but has the same errors.

My main questions are:
Why will it not detect the credentials while everything is setup ok and the fake-auth is working fine?
How can I resolve the errors and have Wifi-pumpkin working ok again?

Thank you

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): Alfa AWUS036NHA
* Version used tool: 0.8.5
* Virtual Machine (yes or no and which): Yes VMware 
* Operating System and version: Kali Rolling

**Comment by mh4x0f** [comment]
> Now it starts the AP but phishing manager has an error "[Fri Jun 16 00:55:50 2017] Failed to listen on 10.0.0.1:80 (reason: Address already in use)"

this message say everything, there is a another process using this port 80. 

> File "netfilterqueue.pyx", line 182, in netfilterqueue.NetfilterQueue.bind (netfilterqueue.c:4388)
OSError: Failed to create queue 0."
 
same problem here.
