### ISSUE TITLE
为什么我这里不显示网关呢，不能输入

### ISSUE THREAD

**Issue by xiaoyanguoke** [P0cL4bs/WiFi-Pumpkin-deprecated#244]
## What's the problem (or question)?
![image](https://user-images.githubusercontent.com/15224735/27266236-c5c20428-54d1-11e7-9d62-507aa3d26deb.png)

*answer here*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: 
* Virtual Machine (yes or no and which): 
* Operating System and version:

**Comment by timschumi** [comment]
Please write your question in English, else we probably won't be able to understand what you want.
