### ISSUE TITLE
You are connected with interface wireless, try again with local connection [my card supports SIM]

### ISSUE THREAD

**Issue by 0katz** [P0cL4bs/WiFi-Pumpkin-deprecated#25]
I read that someone had the same issues as me, but the solution was to check if your wireless card supported " 'AP' in the list of "Supported interface modes"" when I run the command `iw list` my external card does support interface modes. But I still get the error message.

**Comment by 0katz** [comment]
@mh4x0f did you read the question before you marked this duplicate?

**Comment by mh4x0f** [comment]
#14
