### ISSUE TITLE
Metasploit Support

### ISSUE THREAD

**Issue by zero77** [P0cL4bs/WiFi-Pumpkin-deprecated#253]
Can you please add support to use this with metasploit, maybe by using the socks4a module because it works on Linux and windows OS.
Although, there may be a better way to achieve this.

https://www.rapid7.com/db/modules/auxiliary/server/socks4a
Thanks

**Comment by mh4x0f** [comment]
![image](http://whatstube.com.br/wp-content/uploads/2016/10/quando-eu-tenho-que-tomar-decisoes.gif)
