### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Akhipbm** [P0cL4bs/WiFi-Pumpkin-deprecated#255]
Respected sir 

when i start the program it show me the below error. i have put the screens shot please check 

im using tenda w311m wireless adapter card

linux is parrot security OS.

I'm using virtual machine VMware 10 workstation.

when i click on start attack .it show me that this message is received because it has bugs. please check the screen shot. And help me .its written under the start attack

*

- 

- 

- 
![screenshot at 2017-07-17 18-39-49](https://user-images.githubusercontent.com/24264386/28281646-ba60036e-6b1f-11e7-9216-708dab76b379.png)

**Comment by usama7628674** [comment]
The version you are using is old.Use new version or clone latest repo and then try again

**Comment by Akhipbm** [comment]
Please send me the link of the new one.

**Comment by usama7628674** [comment]
type this in terminal of your linux
git clone https://github.com/P0cL4bs/WiFi-Pumpkin.git
then this

cd WiFi-Pumpkin
and after that 

./installer.sh --install

**Comment by usama7628674** [comment]
and it will install and after installation type this in terminal
sudo wifi-pumpkin or wifi-pumpkin

**Comment by Akhipbm** [comment]
Respected Sir

I tried the above thing but when i click on start it showed me the
following error. please check the screen shot.
i even tried to uncheck the option under settings - ignore usb wifi adapter
permanently still its not working.

Config

Parrost OS 3
Vm ware 10
 Card wireless adapters name : tenda usb w311m

**Comment by usama7628674** [comment]
please describe error here.I couldn't see properly from image above

**Comment by Akhipbm** [comment]
It says failed AP mode warning interface. Your adaptor does support create
acces point

**Comment by Akhipbm** [comment]
It also shows .The feature access point not supported by the device wlan0.
But my card support s AP.

**Comment by usama7628674** [comment]
Unfortunately your adapter doesn't support rogue AP.Consider buying new adapter like alfa awus036nha or 
tp link wn722

**Comment by usama7628674** [comment]
or you didn't install drivers properly

**Comment by usama7628674** [comment]
try this 
iw dev wlan0 scan replace wlan0 with your interface

**Comment by usama7628674** [comment]
see if it supports monitor mode and packet injection

**Comment by Akhipbm** [comment]
Ok thank you for helping me out. Thank you for Ur response.
