### ISSUE TITLE
failed AP mode: warning interface

### ISSUE THREAD

**Issue by adolfaka** [P0cL4bs/WiFi-Pumpkin-deprecated#258]
## What's the problem (or question)?

*failed AP mode: warning interface, the feature Access Point Mode is Not Supported By This Device ->(wlan0). Your adapter does not support for create Access Point Network*
![2017-07-27 3 16 50](https://user-images.githubusercontent.com/25989971/28647743-109c6536-727a-11e7-98b4-b9c9ac9adb49.png)
![2017-07-27 3 20 05](https://user-images.githubusercontent.com/25989971/28647805-800c9bde-727a-11e7-86cf-e2669f193f92.png)
![2017-07-27 3 21 19](https://user-images.githubusercontent.com/25989971/28647839-acbd0718-727a-11e7-9eee-c3b0978aa38c.png)
#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): Broadcom on Raspberry Pi 3B
* Version used tool: BCM43438
* Virtual Machine (yes or no and which): No
* Operating System and version: Linux kali 4.4.50-v7+ #1 SMP Sun Mar 26 01:04:50 CDT 2017 armv7l GNU/Linux from here https://build.nethunter.com/nexmon-pi-builds/kali-0.1-rpi3-nexmon.img.xz

**Comment by Dhyogotrust** [comment]
Bom dia Pessoal.
Estou com um adaptador wifi usb da tp link archer t2uh ac600. esse tem suporte ao modo AP ?
