### ISSUE TITLE
wifi-pumpkin

### ISSUE THREAD

**Issue by smailyasid** [P0cL4bs/WiFi-Pumpkin-deprecated#262]
please help me... i can't to install wifi-pumkin

Traceback (most recent call last):
  File "wifi-pumpkin.py", line 39, in <module>
    from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 4, in <module>
    from core.main import Initialize
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 32, in <module>
    from core.widgets.tabmodels import (
  File "/usr/share/WiFi-Pumpkin/core/widgets/tabmodels.py", line 7, in <module>
    from core.utility.threads import ThreadPopen
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 19, in <module>
    from core.servers.proxy.http.controller.handler import MasterHandler
  File "/usr/share/WiFi-Pumpkin/core/servers/proxy/http/controller/handler.py", line 1, in <module>
    from plugins.extension import *
  File "/usr/share/WiFi-Pumpkin/plugins/extension/js_inject.py", line 2, in <module>
    from mitmproxy.models import decoded
ImportError: No module named mitmproxy.models

**Comment by rabbauke** [comment]
try this

> I got the same error and fixed it this way.
> 
> sudo apt-get install -y python-pip
> pip install service_identity
> pip install scapy_http
> sudo apt-get install mitmproxy
> sudo ./installer.sh --install

**Comment by erfirojsiddiki** [comment]
> please help me... i can't to install wifi-pumkin
> 
> Traceback (most recent call last):
> File "wifi-pumpkin.py", line 39, in 
> from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
> File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 4, in 
> from core.main import Initialize
> File "/usr/share/WiFi-Pumpkin/core/main.py", line 32, in 
> from core.widgets.tabmodels import (
> File "/usr/share/WiFi-Pumpkin/core/widgets/tabmodels.py", line 7, in 
> from core.utility.threads import ThreadPopen
> File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 19, in 
> from core.servers.proxy.http.controller.handler import MasterHandler
> File "/usr/share/WiFi-Pumpkin/core/servers/proxy/http/controller/handler.py", line 1, in 
> from plugins.extension import *
> File "/usr/share/WiFi-Pumpkin/plugins/extension/js_inject.py", line 2, in 
> from mitmproxy.models import decoded
> ImportError: No module named mitmproxy.models

same error i am also getting.. if i am installing 0.8.5 it is working fine but latest one is giving the above error
