### ISSUE TITLE
Phishing Manager not working

### ISSUE THREAD

**Issue by 999jay999** [P0cL4bs/WiFi-Pumpkin-deprecated#264]
First of all, thanks for sharing Wifi-Pumpkin

I am having an issue with the Phishing Manager. 

My fake AP is working well, I can connect to it with my phone and I am able to use the internet. I then start up the DNS Spoofer, placing my gateaway IP in the 'gateway' box and it redirects to whichever IP I request it to. I also get updates of website I have tried to connect to in the 'DNS::Requests' in the DNS Spoofer.

Now, when I put the same IP address in Phishing Manager, the internet stops working and 'This site can't be reached' appears on any site I try to visit on my phone.

I have tried changing the port but it hasn't made any difference so I put it back to 80. There are no errors appearing in the terminal nor in the phishing manager 'requests' box. I have tried various IP address's and switched between the 'index.html' and 'set directory' options but still no luck.

Can you think of what could be causing this problem and advise on how to fix it?

Thanks in advance,

J

#### Please tell us details about your environment.
Using Alfa AWUS036H
Latest update of Wifi-Pumpkin
Running Kali 2017.1 on Debian 8.x 64bit on VMWare

**Comment by mh4x0f** [comment]
> My fake AP is working well, I can connect to it with my phone and I am able to use the internet. I then start up the DNS Spoofer, placing my gateaway IP in the 'gateway' box and it redirects to whichever IP I request it to. I also get updates of website I have tried to connect to in the 'DNS::Requests' in the DNS Spoofer.

You not need so change the gateway, because the tool already set all for redirect to phishing page. just start the AP and open the DNS Spoofer and Phishing Manager, now start the redirect attack.
