### ISSUE TITLE
Core.Main / Core.loaders / Core.helpers Imports (Kali)

### ISSUE THREAD

**Issue by darqitecht** [P0cL4bs/WiFi-Pumpkin-deprecated#27]
I done a fresh install of Kalix64 on a VM, update the system & installed all the dependencies:
![captura de pantalla de 2016-02-26 14 09 57](https://cloud.githubusercontent.com/assets/17213273/13364241/54ebdb28-dc93-11e5-9d4a-2842cf1c41ae.png)

**Comment by mh4x0f** [comment]
you need to install config module

``` sh
pip install config
```

checkout: https://github.com/P0cL4bs/WiFi-Pumpkin/wiki/Installation#obs
