### ISSUE TITLE
cant connect to x server

### ISSUE THREAD

**Issue by Robiii97** [P0cL4bs/WiFi-Pumpkin-deprecated#271]
## What's the problem (or question)?

after installing pumpkin i tried to run it and it gave me this error 
http://imgur.com/a/AV63O

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: newest
* Virtual Machine (yes or no and which no
* Operating System and version: android kali nethunter

**Comment by mh4x0f** [comment]
![WTF](https://media.tenor.com/images/897df4256b3cd6038bf34aeeedc1365a/tenor.gif)
