### ISSUE TITLE
No device in my list

### ISSUE THREAD

**Issue by bao-legacy** [P0cL4bs/WiFi-Pumpkin-deprecated#276]
## What's the problem (or question)?
I had connect LAN and network adapter hostpost is wlan0.
I run Access Point, my device has connect PumpAP and has internet in my device but it not shown in list "wifi-pumpkin"
#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): ath10k (it has AP supported)
* Version used tool: 0.8.5
* Virtual Machine (yes or no and which): no
* Operating System and version: Kali Linux 2017.1

**Comment by mh4x0f** [comment]
look https://github.com/P0cL4bs/WiFi-Pumpkin/issues/187#issuecomment-280879650
