### ISSUE TITLE
wifi-pumpkin.py: cannot connet to X server :0.0 (Parrot OSx64)

### ISSUE THREAD

**Issue by darqitecht** [P0cL4bs/WiFi-Pumpkin-deprecated#28]
I done a fresh install of Parrot Osx64, update the system & installed all dependences:

`No protocol specified`
`wifi-pumpkin.py: cannot connect to X server :0.0`

**Comment by mh4x0f** [comment]
try this:

``` sh
export DISPLAY=:0.0
sudo ./wifi-pumpkin.py
```

refer [stackoverflow](http://stackoverflow.com/questions/646930/cannot-connect-to-x-server-0-0-with-a-qt-application)
