### ISSUE TITLE
Nothing displayed!!

### ISSUE THREAD

**Issue by kadu247** [P0cL4bs/WiFi-Pumpkin-deprecated#283]
Ubuntu 16.04
I only get a empty windows! What am i missing here?!

![captura de ecra de 2017-09-24 13-56-05](https://user-images.githubusercontent.com/6238576/30782818-2015e3c6-a131-11e7-83fd-511bcc49861b.png)

**Comment by mh4x0f** [comment]
https://github.com/P0cL4bs/WiFi-Pumpkin/issues/53 look
