### ISSUE TITLE
devices wont show in devices list

### ISSUE THREAD

**Issue by gfdac** [P0cL4bs/WiFi-Pumpkin-deprecated#284]
## What's the problem (or question)?

I start and connect with my 2 devices android, and they wont show on the Devices List, the count of devices = 0, but they are connected.....

#### Please tell us details about your environment.
* AWUS036NH
* 0.8.5
* No VM
* KALI 2

**Comment by mh4x0f** [comment]
look https://github.com/P0cL4bs/WiFi-Pumpkin/issues/187#issuecomment-280879650
