### ISSUE TITLE
Access point not visible

### ISSUE THREAD

**Issue by denisprovost** [P0cL4bs/WiFi-Pumpkin-deprecated#29]
Hi,

When I run the Access Point, I get no errors but when I scan the network on my phone, this access point is not visible.
I use your tool on a kali virtual machine with a Hercules wireless card compatible with AP interface mode. Is my config or is there a problem of the software?

Thank's in advance

**Comment by mh4x0f** [comment]
hi, run the tool as root and check out the log in terminal. 

``` sh
sudo ./wifi-pumpkin.py
```

it probably the hostapd show the problem that is happening.

**Comment by denisprovost** [comment]
Thank's for your answer,
I tried to root, same problem. I do not know if I chose the right gateway but if I had a mistake, the access point does not would launch?

**Comment by mh4x0f** [comment]
Apparently, no have problem with gateway. same if is wrong, the access point should be visible. send me a print screen or send me only output the terminal with tool running.

**Comment by denisprovost** [comment]
Ok. I have attached a picture.

http://www.hostingpics.net/viewer.php?id=827108Capture.png

**Comment by mh4x0f** [comment]
the problem is not the tool, not have error. Apparently, the problem can be your card adapter. Do you try to scan another device ?

**Comment by denisprovost** [comment]
I have 2 cards but my second is a ALPHA. I saw on your instructions that this card has not AP interface mode. Very strange ...

**Comment by mh4x0f** [comment]
exist 2 type cards ALPHA checkout -> [adapters-support](http://elinux.org/RPi_USB_Wi-Fi_Adapters)

**Comment by denisprovost** [comment]
My alpha is "Realtek Semiconductor Corp. RTL8187"

**Comment by mh4x0f** [comment]
It doesn't support AP mode.

**Comment by denisprovost** [comment]
Yes for the alpha card, but my hercule card work perfectly with Aircrack :( and 'iw list' said me yes for the AP mode

**Comment by mh4x0f** [comment]
the driver not support checkout -> [RTL8187](http://linuxwireless.org/en/users/Drivers/rtl8187/)

**Comment by denisprovost** [comment]
For the Alpha card, yes, isn't compatible. But this picture is for Hercule Card

Driver/Chipset
rt73usb Guillemot Corp. HWGUSB2-54-LB

Interface modes:
http://hpics.li/50a83d2

Excuse me for my insistence, I really need to understand why such a problem emerged ;)

**Comment by mh4x0f** [comment]
It support AP mode, I don't know what is happening.very strange, maybe you need to try scan AP with another device.

**Comment by denisprovost** [comment]
Same problem with WIn7, mobile scans.

I do not understand either. Thank's for your time ;)

**Comment by rex1997** [comment]
I am also getting same problem and my wireless card  is compatible with AP interface mode
can you resolve or if there is driver problem so how can I install driver for wifi router.
My router is Tenda

**Comment by james43james** [comment]
Same problem here!
with AWUS036NH 
HOTSPOT NOT VISIBLE

**Comment by Scaidernet** [comment]
**Hola, tengo un problema que cuando lo instalé me funcionó correctamente pero luego al volver a usar por segunda vez me muestra este mensaje, aqui dejo el link de la foto donde me muestra el error, que podrá ser mi error?**

https://scontent.fgye1-1.fna.fbcdn.net/v/t34.0-12/15570909_1361233057229573_1894988542_n.png?oh=e0c7a622482b8bdd08f6e10183b10da8&oe=58537D31

**Comment by yanshari** [comment]
H!, Hotspot is visible. I connected my android but the problem is, "it is not showing any device on wifi-pumpkin", im 100% sure that i am connected to the hotspot i made
![screenshot from 2017-11-05 06-41-32](https://user-images.githubusercontent.com/22851479/32410131-667d630a-c1f4-11e7-9615-01675ec3eafc.png)
