### ISSUE TITLE
GLib-GIO-WARNING

### ISSUE THREAD

**Issue by jeretc** [P0cL4bs/WiFi-Pumpkin-deprecated#295]
## What's the problem (or question)?

*
hi just wanted to know if this is a problem/issue?
GLib-GIO-WARNING **: ../../../../gio/gdbusobjectmanagerclient.c:1585: Processing InterfaceRemoved signal for path /org/freedesktop/NetworkManager/AccessPoint/14 but no object proxy exists
*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: 
* Virtual Machine (yes or no and which): 
* Operating System and version:

**Comment by mh4x0f** [comment]
No
