### ISSUE TITLE
Redirect Traffic from all domain doesn't working

### ISSUE THREAD

**Issue by Thenatdead** [P0cL4bs/WiFi-Pumpkin-deprecated#296]
## Redirect Traffic from all domain doesn't working ?
Hi, i use DNS Spoofer with Windows Update Attack Generator.
In  DNS Spoofer i activate "Redirect traffic from all domains" but when on AP Wifi i go on any website i have no connection screen but if i disable "Redirect traffic from all domains" and add manualy "google.com" its working on this and only on this.
Thanks for helping me (screen of my tool config)
![screenshot from 2017-11-02 21-00-40](https://user-images.githubusercontent.com/20757385/32347547-53adceac-c011-11e7-9cf5-bb61732182c0.png)

#### 
* Card wireless adapters name : Don't know the name but working good.
* Version used tool: Last Update
* Virtual Machine : No
* Operating System and version: Kali Linux 2017.2

**Comment by ssrmpc** [comment]
Since 99% of all the issues I had were related to the Wifi-Adapter or better the related driver, I Kindly ask you to provide us the adapter name and chipset. Do you use an external USB Wifi Adapter such as one from e.g. Alfa AWUS036ACH (RTL8812AU)

Was your adapter driver supported  in the Linux Kernel? Did you have to install the driver via apt-get install realtek-rtl88xxdau-dkms?
Does your adapter support monitor mode?
Does your adapter support AP?

Well then... talk to you later

**Comment by Thenatdead** [comment]
Its pw-dn4210D USB.My adapter support monitor and AP.

**Comment by Thenatdead** [comment]
Chipset: Atheros AR9271

**Comment by ssrmpc** [comment]
Good news.... you shouldn't have any issue with this driver (I know... you
told me.... but seeing is believing :-)

*Something for the Pumpking-Specialist:* Can the wlan1 interface be used in
that many processes?

Anyway.... I try to reproduce your error after I had a good sleep

Cheers
-Marc

2017-11-03 0:30 GMT+01:00 Thenatdead <notifications@github.com>:

**Comment by Thenatdead** [comment]
Someone have solution please ?

**Comment by mh4x0f** [comment]
bad news, I'm work for solve this bug, but I see in old report on python dev [issue socketserver](https://bugs.python.org/issue14574)  that problem not  has been  solve. I'm find another way for redirect the client to web page attack without use the iptables. case not to be possible i'll implement another python web server.

**Comment by mh4x0f** [comment]
@Thenatdead  good news... I started new implementation for create the web server using own module **SimpleHTTPServer**. anyway, the python web server is very slow, but will work normally.

**Comment by b3n-j4m1n** [comment]
This issue still appears to exist. I can redirect using a specific domain such as google.com, but redirecting all domains doesn't work.

I'm using an Alfa AWUS051NH.
