### ISSUE TITLE
Unable to find /etc/NetworkManager/NetworkManager.conf

### ISSUE THREAD

**Issue by thehappydinoa** [P0cL4bs/WiFi-Pumpkin-deprecated#297]
## What's the problem (or question)?

I have just installed network-manager-openvpn-gnome and afterwards I receive this error.

```python
Loading GUI...
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 63, in <module>
    if networkcontrol.run():
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 174, in run
    if not self.check_interfaceinNetWorkManager(interface):
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 166, in check_interfaceinNetWorkManager
    if mac in open(self.mn_path,'r').read(): return True
IOError: [Errno 2] No such file or directory: '/etc/NetworkManager/NetworkManager.conf'
```

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): N/A
* Version used tool: v0.8.5+
* Virtual Machine (yes or no and which): no
* Operating System and version: Kali-Linux Rolling

**Comment by mh4x0f** [comment]
try create the file Network-manager.conf and restart the APP.
``` sh
touch /etc/NetworkManager/NetworkManager.conf
```
if doesn't work, try add this content bellow on file NetworkManager.conf, you can use nano command for change the file.
``` sh 
[main]
plugins=ifupdown,keyfile

[ifupdown]
managed=false
```
