### ISSUE TITLE
Card's got disable/off

### ISSUE THREAD

**Issue by dmatija** [P0cL4bs/WiFi-Pumpkin-deprecated#298]
## What's the problem (or question)?
I using some old laptop =\. Pumkin worked fine few time's and all fine. Them my laptop got freez so o force turn it off. And now my ATHEROS USB2.0 and my Qualcomm Atheros AR9485 got disabled. Meaning cant connect on regular wifi. 
Bout card are listed in network adapter [wlan0 and wlan1] in pumkin. same as they are listed in network-manager but says: disabled
I try to restart network-manager and it don't help. reboot also don't help.
ifconfig not showing any  card.
Any words of wisdom ?
*answer here*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): ATHEROS USB2.0 and my Qualcomm Atheros AR9485
* Version used tool: 0.8.5
* Virtual Machine (yes or no and which): no
* Operating System and version: kali 2017

**Comment by mh4x0f** [comment]
#239 look
