### ISSUE TITLE
Can't Connect Victim Device

### ISSUE THREAD

**Issue by joooo32** [P0cL4bs/WiFi-Pumpkin-deprecated#300]
## What's the problem (or question)?
After making the network and the SSID all I've been able to accomplish is just the fake credential page when going to yahoo but what i'm trying to do is still give the device access as if it were on an actual network not just all fake pages and still record. This might be my configuration but I am hoping to get this working for a project for school. 

I'm disabling the enable wifi in kali linux hoping to use the connection just for the pumpkin but I can't get access to the device as if it were on an actual wifi network. I dont know if this is due to me using the built in wifi card on the RP3. I've ordered a panda wireless adapter hoping this helps.

https://www.amazon.com/Panda-300Mbps-Wireless-USB-Adapter/dp/B00EQT0YK2
*answer here*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): Built in Wireless Card for Raspberry Pi 3
* Version used tool: Latest 0.8.5
* Virtual Machine (yes or no and which): None. Using Raspberry Pi 3
* Operating System and version: Kali Linux for RP3

**Comment by Bee1To** [comment]
Do not use the word victim, there is no victim when you pentest.
