### ISSUE TITLE
cryptography & mitmproxy.modules

### ISSUE THREAD

**Issue by redax2882** [P0cL4bs/WiFi-Pumpkin-deprecated#307]
I'm going insane trying to get this to work.  I had WiFi Pumpkin working just fine on Kali 2017.2.  I did a clean install with 2017.3 and now I can't get it to work.

It seems I have issues with _crytography_ and _mitmproxy.modules_

I'm running Kali Linux 2017.3 inside VMWare.

I've installed all dependencies (_pip install -r requirements.txt_) and the actual application (_./installer.sh --install_).  But whenever I run the program, I get the following error for cryptography:

> In file included from /usr/include/openssl/cms.h:16:0,
>                    from build/temp.linux-armv7l-2.7/_openssl.c:532:
>   /usr/include/openssl/x509.h:552:6: note: expected ‘const X509_ALGOR ** {aka const struct X509_algor_st **}’ but argument is of type ‘X509_ALGOR ** {aka struct X509_algor_st **}’
>    void X509_get0_signature(const ASN1_BIT_STRING **psig,
>         ^~~~~~~~~~~~~~~~~~~
>   error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
>   
>   ----------------------------------------
>   Failed building wheel for cryptography
>   Running setup.py clean for cryptography
> Failed to build cryptography
> Installing collected packages: cryptography, construct, editorconfig, jsbeautifier, requests, pyperclip, configargparse, Flask, argh, pathtools, watchdog, mitmproxy
>   Found existing installation: cryptography 2.1.4
>     Uninstalling cryptography-2.1.4:
>       Successfully uninstalled cryptography-2.1.4

**Comment by mh4x0f** [comment]
#306
