### ISSUE TITLE
ImportError: No module named mitmproxy.models

### ISSUE THREAD

**Issue by guilhermebasalia** [P0cL4bs/WiFi-Pumpkin-deprecated#309]
After you run the sudo wifi-pumpkin displays the following error.

Traceback (most recent call last):
  File "wifi-pumpkin.py", line 37, in <module>
    from core.utility.application import ApplicationLoop
  File "/usr/share/WiFi-Pumpkin/core/utility/application.py", line 3, in <module>
    from core.main import version
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 28, in <module>
    from core.widgets.tabmodels import (
  File "/usr/share/WiFi-Pumpkin/core/widgets/tabmodels.py", line 6, in <module>
    from core.utility.threads import ThreadPopen
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 19, in <module>
    from core.servers.proxy.http.controller.handler import MasterHandler
  File "/usr/share/WiFi-Pumpkin/core/servers/proxy/http/controller/handler.py", line 1, in <module>
    from plugins.extension import *
  File "/usr/share/WiFi-Pumpkin/plugins/extension/beef.py", line 1, in <module>
    from mitmproxy.models import decoded
ImportError: No module named mitmproxy.models
* Operating System and version: 

I'm using ParrotOS.

**Comment by LexLinux** [comment]
Same issue here.

**Comment by abdozekaa** [comment]
Same problem with kali nethunter .. waiting

**Comment by wimdecorte** [comment]
Same issue with Kali on Raspberry Pi

**Comment by 7rav6n** [comment]
Same error here... dosen't work on Kali 2017.3 full install, or Raspberry Pi3 (Kali).

**Comment by usama7628674** [comment]
Use these commands and see it that helps for anyone of you
`pip install -U cryptography`
`pip3 install mitmproxy`

**Comment by guilhermebasalia** [comment]
The error persists even after you have installed the packages.

└──╼ $sudo pip install -U cryptograph
Successfully installed asn1crypto-0.23.0 cryptography-2.1.4 idna-2.6 ipaddress-1.0.18
└──╼ $sudo pip3 install mitmproxy
Requirement already satisfied: mitmproxy in /usr/lib/python3/dist-packages

**Comment by usama7628674** [comment]
I'm also getting `no module named mitmproxy.models`.The problem is after updating to kali linux 2017.3 mitmproxy is also updated.Now when you run `pip install mitmproxy` it uses cryptography-1.5.3 version and that fails to build wheels for it.mitmproxy 0.18.2 is the last version that supports both python 2 and 3.So mitmproxy installs successfully for python 3 using this command `pip3 install mitmproxy` but it doesn't install for python 2 using `pip install mitmproxy`.I've spent a day to resolve this problem but couldn't do so.I'm thinking that how can I install different version of cryptography?The problem is cryptography and also wifi-pumpkin supports only python 2.

**Comment by wimdecorte** [comment]
Same as @guilhermebasalia - error persists and mitmproxy is already there.

**Comment by usama7628674** [comment]
It has something to do with openssl,using different versions of openssl throw different errors and warnings.Try updating and downgrading openssl

**Comment by usama7628674** [comment]
Tried mitmproxy==0.17 but still doesn't install.

**Comment by usama7628674** [comment]
Can anyone try installing mitmproxy on kali 2016.2?

**Comment by 7rav6n** [comment]
Tried clean install on Kali 2017.2 on Raspberry Pi3, but still no luck.

**Comment by usama7628674** [comment]
I'll check on kali 2017.3 (live) and report here.

**Comment by drjohannspector** [comment]
Tried on kali 2017.3 on a live boot, does not work. fresh install too.

**Comment by usama7628674** [comment]
Ok.I tried kali 2017.3 on a live boot and now wifi-pumpkin works.

**Comment by 7rav6n** [comment]
It really works on Kali  2017.3 live boot? It didnt work in my case.(live persistent).

**Comment by usama7628674** [comment]
@7rav6n Yes,it really is working for me.Try live without persistence.Just select first choice that says live when booting.Download kali 2017.3 from official site,64-bit one (2.8 GB).

**Comment by usama7628674** [comment]
@7rav6n @drjohannspector @wimdecorte @guilhermebasalia @abdozekaa Ok I resolved the issue.Just live boot kali 2017.3 **(no persistence)** and copy all the items from `/usr/lib/python2.7/dist-packages` and paste into your existing kali (I'm assuming you're using dual boot) same directory `/usr/lib/python2.7/dist-packages`.That's how I resolved this issue.

**Comment by wimdecorte** [comment]
I'll give it a shot but mine is not a dual boot, it's Kali running on a Raspberry Pi.

**Comment by wimdecorte** [comment]
Do we need to install pumpkin on the live boot first, or just grab what's there on a plain vanilla live boot?

**Comment by usama7628674** [comment]
No you don't need to install wifi-pumpkin

**Comment by 7rav6n** [comment]
@usama7628674 Ok, it does work this way on Kali 2017.3, thanks for solution. And is there a way to make it work on Raspberry Pi3 ?

**Comment by drjohannspector** [comment]
Now I am seeing this error when starting. This was the only error during the install: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-IcVFAB/bs4/

Anyone have any ideas for me? It would be greatly appreciated. I am stumpted

Traceback (most recent call last):
  File "wifi-pumpkin.py", line 37, in <module>
    from core.utility.application import ApplicationLoop
  File "/usr/share/WiFi-Pumpkin/core/utility/application.py", line 3, in <module>
    from core.main import version
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 24, in <module>
    from core.utils import (
  File "/usr/share/WiFi-Pumpkin/core/utils.py", line 8, in <module>
    import netifaces
ImportError: No module named netifaces

**Comment by drjohannspector** [comment]
Made sure to copy the entire directory and its contents, with chmod a+x on /dist-packages/

copied with no errors, not sure what I did wrong but this time this is my output.

root@kali:~/WiFi-Pumpkin# sudo wifi-pumpkin
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 35, in <module>
    from core.loaders.checker.depedences import check_dep_pumpkin
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/depedences.py", line 2, in <module>
    from core.utility.collection import SettingsINI
  File "/usr/share/WiFi-Pumpkin/core/utility/collection.py", line 2, in <module>
    from PyQt4.QtCore import QSettings
ImportError: /usr/lib/python2.7/dist-packages/sip.x86_64-linux-gnu.so: file too short

**Comment by usama7628674** [comment]
@7rav6n I don't have raspberry pi so I'm not familiar with arm platform and not sure how many packages it comes preinstalled.Looking at the size of arm of just 0.6GB (official kali site) I think it comes with small number of packages installed.Do what I said above and see if that resolves your problem.

**Comment by usama7628674** [comment]
@drjohannspector just install this and report back
`apt-get install python-sip`
also install these packages to check if they exist in your machine or not
`apt-get install python-qscintilla2 python-qt4 python-qt4-sql python-sip`

if `netifaces`is not installed then do this
`pip install netifaces`

**Comment by 7rav6n** [comment]
Tried diffrent things but still no luck with arm (rp3).I did install diffrent packages, i checked every solution i could find in google. If anyone manages to make it work please post back... i run out of ideas.

**Comment by ghost** [comment]
what happens is a solution. PLEASE..

**Comment by mh4x0f** [comment]
due to large quantity of users can't install the module mitmproxy, I 'll disable the plugin mitmproxy and set another as default. this will solve the problem temporarily. wait ....

**Comment by mockedxe** [comment]
What time

**Comment by ghost** [comment]
I'm crazy when I try to work. In 2017.2, WiFi Pumpkins were working. I made a clean install with 2017.3 and now I will not work.

There seems to be a problem with cryotography and mitmproxy.modules

I'm running Kali Linux 2017.3 in VMWare
Can you help me. Please 😇

**Comment by maxitis92** [comment]
![capture](https://user-images.githubusercontent.com/15869632/34128115-41bb37a6-e448-11e7-9e53-b3cc65189485.PNG)

i have this problem. how can i solve it?

**Comment by Patxe** [comment]
@usama7628674 Ok, it does work this way on Kali 2017.3. 
Thxs for solution.

**Comment by ghost** [comment]
@Patxe 
I'm crazy when I try to work. In 2017.2, WiFi Pumpkins were working. I made a clean install with 2017.3 and now I will not work.

There seems to be a problem with cryotography and mitmproxy.modules

I'm running Kali Linux 2017.3 in VMWare
Can you help me. Please 😇

**Comment by usama7628674** [comment]
@mockedxe Read my post above.It's the only solution right now.

**Comment by ghost** [comment]
@usama7628674
please re-write

**Comment by ghost** [comment]
@usama7628674 this is the solution ? 👍
just install this and report back
apt-get install python-sip
also install these packages to check if they exist in your machine or not
apt-get install python-qscintilla2 python-qt4 python-qt4-sql python-sip

if netifacesis not installed then do this
pip install netifaces

**Comment by usama7628674** [comment]
@mockedxe No,check my 9th post.

**Comment by ghost** [comment]
@usama7628674 Thanks bro.

**Comment by ghost** [comment]
But 
This is /usr/lib/python2.7/dist-packages
where do we copy.

**Comment by usama7628674** [comment]
@mockedxe Are you using dual boot or live boot?

**Comment by ghost** [comment]
@usama7628674 i am using  VMware

**Comment by ghost** [comment]
@usama7628674 
  mitmproxy not download
 Running setup.py bdist_wheel for cryptography ... - gives an error here

**Comment by usama7628674** [comment]
@mockedxe live boot kali (using usb) and install wifi-pumpkin.

**Comment by ghost** [comment]
@usama7628674  wifi pumpkin Why does not VMware work?

**Comment by usama7628674** [comment]
@mockedxe Did it work on live usb?

**Comment by mockedxe** [comment]
@usama7628674 I did not want to try.
because there is no need for just one program

**Comment by ghost** [comment]
@usama7628674  There is no other way?

**Comment by liuli1689** [comment]
@maxitis92  same problem  Have you solved it?

**Comment by ghost** [comment]
@maxitis92 no!!

**Comment by Esser50K** [comment]
My project also uses mitmproxy and I was facing the same issue recently.
My solution was deleteing everything cryptography related and also mitmproxy and then reinstalling it, the needed version is 0.18.2. This and also my project need an update to support python3 in order to use the new mitmproxy. The quick fix I used was:


```
apt-get remove --purge python-cryptography
pip uninstall mitmproxy
pip3 uninstall mitmproxy
pip install -U cryptography
pip install mitmproxy==0.18.2
```

**Comment by ghost** [comment]
@Esser420  VMware using do you?

**Comment by Esser50K** [comment]
@mockedxe

No, Kali linux on bare metal.

**Comment by ghost** [comment]
@Esser420
Kali Linux bare metal how to. which videos have. link to throw you?

**Comment by ghost** [comment]
@Esser420
I'm crazy when I try to work. In 2017.2, WiFi Pumpkins were working. I made a clean install with 2017.3 and now I will not work.

There seems to be a problem with cryotography and mitmproxy.modules

I'm running Kali Linux 2017.3 in VMWare
Can you help me. Please 😇

**Comment by ghost** [comment]
@Esser420
Do you know?

**Comment by Esser50K** [comment]
@mockedxe
Bare metal just means I installed it directly on my machine instead of a VM. I do not recommend this setup however.. No links to show you, just try running those commands I show. The install script will not work anymore, Kali sometimes messes up the repository...

Have you tried running those commands?

```
apt-get remove --purge python-cryptography
pip uninstall mitmproxy
pip3 uninstall mitmproxy
pip install -U cryptography
pip install mitmproxy==0.18.2
```

**Comment by ghost** [comment]
@Esser420
Thanks bro.

**Comment by Esser50K** [comment]
@mockedxe

Did it work though?

**Comment by warriordz** [comment]
why wifi-pumpkin not orking in kali linux 2017.3 and what is soultion

**Comment by ghost** [comment]
@warriordz 
Unfortunately, No one don't know !!

**Comment by warriordz** [comment]
@mockedxe ok can i give me name of your face book to talk about probleme in kali

**Comment by ghost** [comment]
@warriordz
İ don't understand

**Comment by warriordz** [comment]
@mockedxe do you have account facebook

**Comment by ghost** [comment]
@warriordz 
Unfortunately, No

**Comment by ghost** [comment]
@warriordz 
WiFi pumpkin working  Kali linux on bare metal

**Comment by warriordz** [comment]
Do you have any way to communicate maybe we'll benefit each other

**Comment by ghost** [comment]
@warriordz 
Or live usb

**Comment by warriordz** [comment]
@mockedxe Do you have any way to communicate maybe we'll benefit each other

**Comment by ghost** [comment]
@warriordz 
Don't trust

**Comment by ghost** [comment]
@warriordz
You are from?

**Comment by warriordz** [comment]
Oh, you do not trust me. I just wanted to take advantage of each other. good bye

**Comment by warriordz** [comment]
@mockedxe  Algeria

**Comment by ghost** [comment]
@warriordz
This watch https://youtu.be/KV9yzoA77ks

**Comment by ghost** [comment]
@warriordz
WiFi pumpkin just live usb  trying to
Ok

**Comment by mockedxe** [comment]
@warriordz
WiFi pumpkin just live usb  trying to
Ok

**Comment by ghost** [comment]
@warriordz 
واي فاي اليقطين يعيش فقط أوسب في محاولة ل
حسنا
هل تفهم

**Comment by warriordz** [comment]
@mockedxe ok what is your from

**Comment by ghost** [comment]
@warriordz
Türkish

**Comment by ghost** [comment]
@warriordz
Did it work ?

**Comment by ghost** [comment]
@warriordz 
But now I live in Canada

**Comment by warriordz** [comment]
great turkish i love this country .
nice to meet you

**Comment by ghost** [comment]
@warriordz
me too

**Comment by Esser50K** [comment]
Still not working? I'm working on kali and my solution worked. Has anyone tried it?

**Comment by ghost** [comment]
@Esser420
Are you using live usb?

**Comment by inv1sible** [comment]
@Esser420 unfortunately not working (on raspberry pi3 with kali VERSION="2017.3"). it is not installing `pip install mitmproxy==0.18.2`

```
In file included from /usr/include/openssl/cms.h:16:0,
                     from build/temp.linux-armv7l-2.7/_openssl.c:532:
    /usr/include/openssl/x509.h:552:6: note: expected 'const X509_ALGOR ** {aka const struct X509_algor_st **}' but argument is of type 'X509_ALGOR ** {aka struct X509_algor_st **}'
     void X509_get0_signature(const ASN1_BIT_STRING **psig,
          ^~~~~~~~~~~~~~~~~~~
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of cryptography
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-XqbwOk/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6utVHu-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-XqbwOk/cryptography/
root@kali:~/Downloads/WiFi-Pumpkin# sudo wifi-pumpkin
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 37, in <module>
    from core.utility.application import ApplicationLoop
  File "/usr/share/WiFi-Pumpkin/core/utility/application.py", line 3, in <module>
    from core.main import version
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 28, in <module>
    from core.widgets.tabmodels import (
  File "/usr/share/WiFi-Pumpkin/core/widgets/tabmodels.py", line 6, in <module>
    from core.utility.threads import ThreadPopen
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 19, in <module>
    from core.servers.proxy.http.controller.handler import MasterHandler
  File "/usr/share/WiFi-Pumpkin/core/servers/proxy/http/controller/handler.py", line 1, in <module>
    from plugins.extension import *
  File "/usr/share/WiFi-Pumpkin/plugins/extension/stickycookie.py", line 1, in <module>
    from mitmproxy.models import decoded
ImportError: No module named mitmproxy.models

```

**Comment by ghost** [comment]
@Esser420
Are you using live usb?
Please

**Comment by ghost** [comment]
@Esser420
Or dual boot

**Comment by 4rensiker** [comment]
@mockedxe 

@Esser420 already stated 5 days ago that he is using kali on a physical computer (bare metal) not a virtual machine... anyway I do not think this is important as the problem IMHO lies in dependencies struggle with outdated software....

**Comment by inv1sible** [comment]
👍🏼.. Any plans on migrating to python3? 
lots of dependencies seem to respect to more recent versions.....

**Comment by harry3911** [comment]
![screenshot from 2018-02-28 08-02-46](https://user-images.githubusercontent.com/36356737/36776482-d6404040-1c5d-11e8-8500-dd20296b71cc.png)
what to do now its not working???????????????????????????

**Comment by usama7628674** [comment]
@harry3911 Did you run setup and what version of kali are you using?Post the output of setup script.

**Comment by harry3911** [comment]
bro i am currently using kali linux rolling and i have run the setup by
./installer.sh --install and also satisfied all the requirements.
bro please help me
.

**Comment by harry3911** [comment]
![screenshot from 2018-03-01 06-01-21](https://user-images.githubusercontent.com/36356737/36829223-18d10738-1d16-11e8-9b93-cc3c6a46851d.png)
![screenshot from 2018-03-01 06-01-00](https://user-images.githubusercontent.com/36356737/36829224-196cf7ba-1d16-11e8-8e36-66f1e6616689.png)
![screenshot from 2018-03-01 06-00-12](https://user-images.githubusercontent.com/36356737/36829225-1aae1212-1d16-11e8-9cde-e1152d081152.png)

**Comment by harry3911** [comment]
please some one help me i need this wifi pumpkin ready till tomorrow please help me bro please

**Comment by usama7628674** [comment]
@harry3911 Can you do `pip uninstall scapy`  and `pip install scapy`.Make sure you're using kali 2018.1

**Comment by harry3911** [comment]
done bro

**Comment by harry3911** [comment]
not working still

**Comment by usama7628674** [comment]
Now run wifi-pumpkin from it's directory

**Comment by usama7628674** [comment]
Ok do `pip install -U scapy`.run it from directory

**Comment by harry3911** [comment]
ok please be onilne
i will do whatever you will tell

**Comment by harry3911** [comment]
![screenshot from 2018-03-01 08-24-05](https://user-images.githubusercontent.com/36356737/36834179-f56edf86-1d29-11e8-8abd-54ae80abff94.png)
![screenshot from 2018-03-01 08-23-03](https://user-images.githubusercontent.com/36356737/36834180-f64b4d68-1d29-11e8-9262-823857a77506.png)
![screenshot from 2018-03-01 08-24-55](https://user-images.githubusercontent.com/36356737/36834210-0ab40ace-1d2a-11e8-85c0-c7498f7011f5.png)

**Comment by harry3911** [comment]
still not working

**Comment by usama7628674** [comment]
Now do this `apt-get install --reinstall python-scapy`

**Comment by usama7628674** [comment]
and run wifi-pumpkin like this  `python wifi-pumpkin.py`

**Comment by harry3911** [comment]
nope bro not working

**Comment by harry3911** [comment]
still the same error

**Comment by harry3911** [comment]
![screenshot from 2018-03-01 08-29-27](https://user-images.githubusercontent.com/36356737/36834393-b45cba26-1d2a-11e8-800d-a7552247d422.png)

**Comment by usama7628674** [comment]
remove scapy `pip uninstall scapy` and reinstall it

**Comment by harry3911** [comment]
bro i guess you found the error
![screenshot from 2018-03-01 08-32-26](https://user-images.githubusercontent.com/36356737/36834560-2823bd10-1d2b-11e8-9126-1ee855b5ec4f.png)

**Comment by harry3911** [comment]
how to fix this one

**Comment by harry3911** [comment]
i am new to kali linux and hacking both

**Comment by usama7628674** [comment]
No don't use pip3 use `pip uninstall scapy`  and post output.

**Comment by harry3911** [comment]
![screenshot from 2018-03-01 08-34-37](https://user-images.githubusercontent.com/36356737/36834642-6a6ae2de-1d2b-11e8-99b4-4c9ec1671202.png)

**Comment by usama7628674** [comment]
now do `apt-get remove python-scapy` and post here

**Comment by harry3911** [comment]
![screenshot from 2018-03-01 08-37-20](https://user-images.githubusercontent.com/36356737/36834756-c9e3b510-1d2b-11e8-8047-85afd027a607.png)

**Comment by harry3911** [comment]
now ??

**Comment by usama7628674** [comment]
now install it using `pip install --no-cache scapy`

**Comment by harry3911** [comment]
![screenshot from 2018-03-01 08-39-33](https://user-images.githubusercontent.com/36356737/36834851-1b472d10-1d2c-11e8-84e6-512ff6a1a008.png)

**Comment by harry3911** [comment]
done 
next??

**Comment by usama7628674** [comment]
go to wifi-pumpkin directory and execute `pip install -r requirements.txt` and post here

**Comment by harry3911** [comment]
![screenshot from 2018-03-01 08-41-17](https://user-images.githubusercontent.com/36356737/36834912-5a40ef06-1d2c-11e8-84a9-a0928cfbe752.png)
![screenshot from 2018-03-01 08-41-19](https://user-images.githubusercontent.com/36356737/36834916-5b48a646-1d2c-11e8-8af3-79bddd0d448f.png)

**Comment by harry3911** [comment]
still error is there bro!!

**Comment by usama7628674** [comment]
Did you clone it properly?

**Comment by harry3911** [comment]
clone??

**Comment by harry3911** [comment]
ok i will do it again

**Comment by usama7628674** [comment]
Go to wifi-pumpkin github page and execute these commands 
`git clone https://github.com/P0cL4bs/WiFi-Pumpkin.git`
`cd WiFi-Pumpkin`
 `./installer.sh --install`

**Comment by harry3911** [comment]
actually i used to download zip but now i am cloning 
please wait

**Comment by harry3911** [comment]
![screenshot from 2018-03-01 08-48-05](https://user-images.githubusercontent.com/36356737/36835272-95026cfe-1d2d-11e8-9673-a9e89f1bd093.png)
![screenshot from 2018-03-01 08-48-20](https://user-images.githubusercontent.com/36356737/36835274-95de3284-1d2d-11e8-8301-c1cfe1228e75.png)
![screenshot from 2018-03-01 08-48-46](https://user-images.githubusercontent.com/36356737/36835277-974a9afe-1d2d-11e8-8f27-08b0f9cc3d97.png)
![screenshot from 2018-03-01 08-49-05](https://user-images.githubusercontent.com/36356737/36835280-99f3620e-1d2d-11e8-9022-748cf67475f5.png)
![screenshot from 2018-03-01 08-49-07](https://user-images.githubusercontent.com/36356737/36835283-9b80bfea-1d2d-11e8-9a57-6ca6303b41e1.png)
![screenshot from 2018-03-01 08-49-15](https://user-images.githubusercontent.com/36356737/36835285-9ca77634-1d2d-11e8-9f78-9ee19416bc1d.png)

**Comment by harry3911** [comment]
![screenshot from 2018-03-01 08-44-47](https://user-images.githubusercontent.com/36356737/36835319-bad463c4-1d2d-11e8-997c-b6988b022ee2.png)

**Comment by harry3911** [comment]
bro please help me out its not working!!!!!!!

**Comment by usama7628674** [comment]
ok dump the output 
`cat /etc/*release`

**Comment by harry3911** [comment]
![screenshot from 2018-03-01 08-53-28](https://user-images.githubusercontent.com/36356737/36835403-07d2765c-1d2e-11e8-9c3d-fc6b67c93823.png)

**Comment by harry3911** [comment]
now???

**Comment by usama7628674** [comment]
do `apt-get update` and then `apt-get dist-upgrade`

**Comment by harry3911** [comment]
![screenshot from 2018-03-01 08-59-29](https://user-images.githubusercontent.com/36356737/36835706-03485f88-1d2f-11e8-8b61-62ce3fb4f817.png)
![screenshot from 2018-03-01 09-00-22](https://user-images.githubusercontent.com/36356737/36835708-03c52504-1d2f-11e8-9aac-da4bd2d7049a.png)
![screenshot from 2018-03-01 09-01-19](https://user-images.githubusercontent.com/36356737/36835779-3e150120-1d2f-11e8-98d8-a16c935c9d7c.png)

**Comment by harry3911** [comment]
unpacking and preparing is going on a lot of them is going on

**Comment by harry3911** [comment]
still going on

**Comment by harry3911** [comment]
bro can i have your number of might be you mine???????
just for help and when it got completed i can contact you on whatsapp 
and i do know some person from pakisthan

**Comment by harry3911** [comment]
should i give?
because still it is going on
unpacking and preparing

**Comment by usama7628674** [comment]
@harry3911 Where are you from?

**Comment by usama7628674** [comment]
And let it complete then try running again

**Comment by harry3911** [comment]
i am form india

**Comment by harry3911** [comment]
sorry man you might not be liking india

**Comment by usama7628674** [comment]
No I don't mean it.It doesn't matter you live in any country.

**Comment by harry3911** [comment]
![screenshot from 2018-03-01 09-21-44](https://user-images.githubusercontent.com/36356737/36836709-081fb72e-1d32-11e8-906c-59bb7ef39bba.png)

**Comment by usama7628674** [comment]
you can give your whatsapp no and I'll send you a message

**Comment by usama7628674** [comment]
Ok messaging you now and add me

**Comment by harry3911** [comment]
![screenshot from 2018-03-01 09-22-54](https://user-images.githubusercontent.com/36356737/36836757-26835c3e-1d32-11e8-8a79-b9432235671d.png)
it didn't worked plz help bro

**Comment by harry3911** [comment]
bro whats next??

**Comment by usama7628674** [comment]
did you receive my message

**Comment by harry3911** [comment]
ya i did

**Comment by usama7628674** [comment]
go to https://www.kali.org/downloads/ and download kali 64-bit then download and install win32diskimager,plug your usb drive and write it and boot your pc from usb and select first option live and then use wifi-pumpkin

**Comment by harry3911** [comment]
ok

**Comment by usama7628674** [comment]
Are you using laptop

**Comment by harry3911** [comment]
yup

**Comment by usama7628674** [comment]
be sure to download 64 bit

**Comment by harry3911** [comment]
ya i know that

**Comment by usama7628674** [comment]
I'll check back later

**Comment by harry3911** [comment]
how to install it without losing my data?
cause i have only 1 partation

**Comment by usama7628674** [comment]
so you're using windows

**Comment by harry3911** [comment]
if there is no way so i will copy my data in hard disk

**Comment by harry3911** [comment]
nope i am having only one OS thats kali linux

**Comment by usama7628674** [comment]
no you don't need to because we'll use live version

**Comment by usama7628674** [comment]
live means you can run kali without need to make partition or installing it

**Comment by harry3911** [comment]
ok that portable usb will be having that os 
so i can operate it from any pc whicher i like??

**Comment by harry3911** [comment]
its just like portable OS

**Comment by usama7628674** [comment]
yes just plug your usb and you could easily run kali

**Comment by harry3911** [comment]
does that effects the speed of processing??

**Comment by usama7628674** [comment]
no nothing

**Comment by harry3911** [comment]
ok

**Comment by harry3911** [comment]
any other tool which is similar to pumpkin??

**Comment by usama7628674** [comment]
airgeddon,fluxion,wifiphisher

**Comment by harry3911** [comment]
thankx man

**Comment by harry3911** [comment]
are you a hacker??

**Comment by usama7628674** [comment]
Not really but I'm doing mechanical engineering but I like wireless stuff and cracked most of the wifi passwords around my area.

**Comment by harry3911** [comment]
i can do the same thing using airbase-ng

**Comment by harry3911** [comment]
at the place of pumpkin

**Comment by usama7628674** [comment]
No I mean evil-twin method

**Comment by harry3911** [comment]
pumpkin also do evil-twin??
or it only requires one wifi adaptor

**Comment by usama7628674** [comment]
you can create rogue AP and let the victim to connect to your fake AP and wait for them to give their psk.fluxion and airgeddon both are good for that.

**Comment by harry3911** [comment]
ok thankz bye i need to get lunch

**Comment by usama7628674** [comment]
Yes Wifi-pumpkin also

**Comment by usama7628674** [comment]
enjoy your lunch and we'll talk later.

**Comment by usama7628674** [comment]
There is something wrong with scapy so live will eliminate every issue and you can easily run wifi-pumpkin and I can't reproduce this issue so I don't know what's the logic behind this but hopefully you'll run it fine on live version

**Comment by harry3911** [comment]
bro is there any other tool which is 90% similar to wifi-pumpkin

**Comment by harry3911** [comment]
because it also gets me the passwords and other things

**Comment by mehulgondaliya** [comment]
same problem with kali linux

**Comment by indiegos** [comment]
I am installing in Parrot, If you have this problem, try to reinstall like this
Open Terminal
#cd Wifi-Pumpkin
#./installer.sh
#chmod +x ./installer.sh
#sudo ./installer.sh --install

![screenshot at 2018-06-11 06-14-59](https://user-images.githubusercontent.com/26783125/41207363-ccad9316-6d3e-11e8-8509-4b8f5fe1f467.png)

Run Pumpkin
#sudo wifi-pumpkin



Done

**Comment by JeremyWhittaker** [comment]
![image](https://user-images.githubusercontent.com/13750325/51207082-10261300-18c7-11e9-9df3-c3944c52cc96.png)
I'm getting this error on Raspberry Pi. Can someone point me in the right direction?
