### ISSUE TITLE
wifi-pumpkin Installer kali-rolling  problem  ...

### ISSUE THREAD

**Issue by hesamer** [P0cL4bs/WiFi-Pumpkin-deprecated#32]
when install : 

root@kali:/home/kali/3vilTwinAttacker# ./installer.sh --install
[3;J

   =============================
   | wifi-pumpkin Installer|
   =============================
          Version: 0.7.3 
usage: ./installer.sh --install | --uninstall
[3;J

   =============================
   | wifi-pumpkin Installer|
   =============================
          Version: 0.7.3 
usage: ./installer.sh --install | --uninstall
Ign cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02] sana InRelease
Ign cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02] sana Release.gpg  
Ign cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02] sana Release  
Err cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02] sana/non-free amd64 Packages  
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Err cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02] sana/main amd64 Packages  
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Err cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02] sana/contrib amd64 Packages  
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Err cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02] sana/non-free i386 Packages  
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Err cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02] sana/main i386 Packages  
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Err cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02] sana/contrib i386 Packages  
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Ign cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02] sana/contrib Translation-en_US  
Ign cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02] sana/contrib Translation-en  
Ign cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02] sana/main Translation-en_US  
Ign cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02] sana/main Translation-en  
Ign cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02] sana/non-free Translation-en_US  
Ign cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02] sana/non-free Translation-en  
Ign http://download.opensuse.org  InRelease  
Ign http://ftp.de.debian.org wheezy InRelease  
Ign http://dl.google.com stable InRelease  
Hit http://ppa.launchpad.net trusty InRelease  
Get:1 http://download.opensuse.org  Release.gpg [481 B]  
Hit http://ftp.de.debian.org wheezy Release.gpg  
Hit http://dl.google.com stable Release.gpg  
Hit http://download.opensuse.org  Release  
Ign http://download.opensuse.org  Release  
Hit http://ftp.de.debian.org wheezy Release  
Hit http://dl.google.com stable Release  
Ign http://download.opensuse.org  Packages/DiffIndex  
Hit http://dl.google.com stable/main amd64 Packages  
Hit http://ppa.launchpad.net trusty/main Sources  
Get:2 http://http.kali.org kali-rolling InRelease [24.6 kB]  
Hit http://ftp.de.debian.org wheezy/main amd64 Packages  
Hit http://ppa.launchpad.net trusty/main amd64 Packages  
Hit http://ftp.de.debian.org wheezy/main i386 Packages  
Hit http://ppa.launchpad.net trusty/main i386 Packages  
Hit http://ftp.de.debian.org wheezy/main Translation-en  
Hit http://ppa.launchpad.net trusty/main Translation-en  
Get:3 http://http.kali.org kali-rolling/main Sources [10.1 MB]  
Ign http://download.opensuse.org  Translation-en_US  
Ign http://download.opensuse.org  Translation-en  
Hit http://download.opensuse.org  Packages  
93% [3 Sources 3,925 kB/10.1 MB 39%] [Connecting to http.kali.org (192.99.200.1Ign http://http.kali.org kali-rolling/contrib Translation-en_US  
Ign http://http.kali.org kali-rolling/contrib Translation-en  
Get:4 http://http.kali.org kali-rolling/non-free Sources [118 kB]  
Ign http://http.kali.org kali-rolling/main Translation-en_US  
Get:5 http://http.kali.org kali-rolling/contrib Sources [62.9 kB]  
Ign http://http.kali.org kali-rolling/main Translation-en  
Get:6 http://http.kali.org kali-rolling/main amd64 Packages [13.5 MB]  
Ign http://http.kali.org kali-rolling/non-free Translation-en_US  
Ign http://http.kali.org kali-rolling/non-free Translation-en  
Get:7 http://http.kali.org kali-rolling/non-free amd64 Packages [145 kB]  
Get:8 http://http.kali.org kali-rolling/contrib amd64 Packages [93.5 kB]  
Get:9 http://http.kali.org kali-rolling/main i386 Packages [13.5 MB]  
Get:10 http://http.kali.org kali-rolling/non-free i386 Packages [131 kB]  
Get:11 http://http.kali.org kali-rolling/contrib i386 Packages [89.0 kB]  
Fetched 37.7 MB in 12min 26s (50.5 kB/s)  
W: GPG error: http://download.opensuse.org  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A7D1D38BEB6D886
W: Failed to fetch cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02]/dists/sana/non-free/binary-amd64/Packages  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs

W: Failed to fetch cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02]/dists/sana/main/binary-amd64/Packages  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs

W: Failed to fetch cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02]/dists/sana/contrib/binary-amd64/Packages  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs

W: Failed to fetch cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02]/dists/sana/non-free/binary-i386/Packages  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs

W: Failed to fetch cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02]/dists/sana/main/binary-i386/Packages  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs

W: Failed to fetch cdrom://[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot amd64 LIVE/INSTALL Binary 20150811-08:02]/dists/sana/contrib/binary-i386/Packages  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs

W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree  
Reading state information... Done
hostapd is already the newest version.
php5-cli is already the newest version.
python-qt4 is already the newest version.
python-scapy is already the newest version.
rfkill is already the newest version.
The following packages were automatically installed and are no longer required:
  dctrl-tools devscripts distro-info-data dput freemind-doc javahelp2
  javahelper libaldmb1 libclass-inspector-perl libconvert-binhex-perl
  libdistro-info-perl libdumb1 libecj-java libecj-java-gcj
  libexporter-lite-perl libgcj-bc libgcj14-dev libgcj15-dev libgetopt-java
  libglib2.0-0:i386 libgnu-regexp-java libgsoap5
  libgstreamer-plugins-base0.10-0:i386 libgstreamer0.10-0:i386
  libguichan-0.8.1-1 libguichan-allegro-0.8.1-1 libio-sessiondata-perl
  libjgoodies-common-java libkmahjongglib4 libmime-tools-perl
  libossp-uuid-perl libossp-uuid16 libparse-debcontrol-perl libphysfs1
  libsdl-gfx1.2-5 libsoap-lite-perl libvncserver0 libwine-gecko-2.21
  libxmlrpc-lite-perl python3-magic simplyhtml strace
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 2709 not upgraded.
/usr/lib/python2.7/dist-packages/cffi/model.py:526: UserWarning: 'point_conversion_form_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
Requirement already satisfied (use --upgrade to upgrade): Twisted in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): scapy in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): BeautifulSoup in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): python-nmap in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): netaddr in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): config in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): dnspython in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): isc-dhcp-leases in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Downloading/unpacking netifaces (from -r requirements.txt (line 9))
  Downloading netifaces-0.10.4.tar.gz
  Running setup.py (path:/tmp/pip-build-xGyUBl/netifaces/setup.py) egg_info for package netifaces

Installing collected packages: netifaces
  Running setup.py install for netifaces
    checking for getifaddrs...not found.
    checking for getnameinfo...not found.
    checking for socket IOCTLs...not found.
    checking for optional header files...netash/ash.h netatalk/at.h netax25/ax25.h neteconet/ec.h netipx/ipx.h netpacket/packet.h linux/irda.h linux/atm.h linux/llc.h linux/tipc.h linux/dn.h.
    checking whether struct sockaddr has a length field...no.
    checking which sockaddr_xxx structs are defined...none!
    checking for routing socket support...no.
    checking for sysctl(CTL_NET...) support...no.
    checking for netlink support...no.
    building 'netifaces' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DNETIFACES_VERSION=0.10.4 -DHAVE_NETASH_ASH_H=1 -DHAVE_NETATALK_AT_H=1 -DHAVE_NETAX25_AX25_H=1 -DHAVE_NETECONET_EC_H=1 -DHAVE_NETIPX_IPX_H=1 -DHAVE_NETPACKET_PACKET_H=1 -DHAVE_LINUX_IRDA_H=1 -DHAVE_LINUX_ATM_H=1 -DHAVE_LINUX_LLC_H=1 -DHAVE_LINUX_TIPC_H=1 -DHAVE_LINUX_DN_H=1 -I/usr/include/python2.7 -c netifaces.c -o build/temp.linux-x86_64-2.7/netifaces.o
    netifaces.c:185:6: error: #error You need to add code for your platform.
     #    error You need to add code for your platform.
          ^
    netifaces.c: In function ‘gateways’:
    netifaces.c:1213:22: warning: unused variable ‘defaults’ [-Wunused-variable]
       PyObject *result, *defaults;
                          ^
    netifaces.c: At top level:
    netifaces.c:316:1: warning: ‘string_from_sockaddr’ defined but not used [-Wunused-function]
     string_from_sockaddr (struct sockaddr *addr,
     ^
    netifaces.c:446:1: warning: ‘add_to_family’ defined but not used [-Wunused-function]
     add_to_family (PyObject *result, int family, PyObject *obj)
     ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip-build-xGyUBl/netifaces/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-XzZV4v-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_ext

checking for getifaddrs...not found.

checking for getnameinfo...not found.

checking for socket IOCTLs...not found.

checking for optional header files...netash/ash.h netatalk/at.h netax25/ax25.h neteconet/ec.h netipx/ipx.h netpacket/packet.h linux/irda.h linux/atm.h linux/llc.h linux/tipc.h linux/dn.h.

checking whether struct sockaddr has a length field...no.

checking which sockaddr_xxx structs are defined...none!

checking for routing socket support...no.

checking for sysctl(CTL_NET...) support...no.

checking for netlink support...no.

building 'netifaces' extension

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DNETIFACES_VERSION=0.10.4 -DHAVE_NETASH_ASH_H=1 -DHAVE_NETATALK_AT_H=1 -DHAVE_NETAX25_AX25_H=1 -DHAVE_NETECONET_EC_H=1 -DHAVE_NETIPX_IPX_H=1 -DHAVE_NETPACKET_PACKET_H=1 -DHAVE_LINUX_IRDA_H=1 -DHAVE_LINUX_ATM_H=1 -DHAVE_LINUX_LLC_H=1 -DHAVE_LINUX_TIPC_H=1 -DHAVE_LINUX_DN_H=1 -I/usr/include/python2.7 -c netifaces.c -o build/temp.linux-x86_64-2.7/netifaces.o

netifaces.c:185:6: error: #error You need to add code for your platform.

 #    error You need to add code for your platform.

```
  ^
```

netifaces.c: In function ‘gateways’:

netifaces.c:1213:22: warning: unused variable ‘defaults’ [-Wunused-variable]

   PyObject *result, *defaults;

```
                  ^
```

netifaces.c: At top level:

netifaces.c:316:1: warning: ‘string_from_sockaddr’ defined but not used [-Wunused-function]

 string_from_sockaddr (struct sockaddr *addr,

 ^

netifaces.c:446:1: warning: ‘add_to_family’ defined but not used [-Wunused-function]

 add_to_family (PyObject *result, int family, PyObject *obj)

 ^

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

---

Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip-build-xGyUBl/netifaces/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-XzZV4v-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-xGyUBl/netifaces
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/**init**.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
## UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 29: ordinal not in range(128)

[=] checking dependencies  
----[✔]----[+] hostapd Installed
----[✔]----[+] dhcpd Installed
## ----[✔]----[+] php Installed

[+] Distribution Name: Kali

---

[=]  Install WiFi-Pumpkin 
[✔] wifi-pumpkin installed with success
[✔] execute  wifi-pumpkin in terminal
[+] P0cL4bs Team CopyRight 2015
[+] Enjoy

after  install  : 

**# root@kali:/home/kali/3vilTwinAttacker#** sudo ./wifi-pumpkin.py
Traceback (most recent call last):
  File "./wifi-pumpkin.py", line 5, in <module>
    from Core.Main import Initialize
  File "/home/kali/3vilTwinAttacker/Core/Main.py", line 3, in <module>
    from Proxy import *
  File "/home/kali/3vilTwinAttacker/Proxy/Plugin.py", line 2, in <module>
    from Core.Utils import setup_logger
  File "/home/kali/3vilTwinAttacker/Core/Utils.py", line 15, in <module>
    import netifaces
ImportError: No module named netifaces

**Comment by mh4x0f** [comment]
try this:

``` sh
$ sudo apt-get install python-dev
$ sudo pip install netifaces
```

if you got this message

```
Successfully installed netifaces
Cleaning up...
```

now you can to run WiFi-Pumpkin.

``` sh
$ sudo ./wifi-pumpkin.py
```

**Comment by djtroby** [comment]
Please if you can help to resolve this error.

root@kali:~# sudo pip install netifaces
Collecting netifaces
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 837, in _validate_conn
    conn.connect()
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py", line 330, in connect
    cert = self.sock.getpeercert()
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
    'subjectAltName': get_subj_alt_name(x509)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
    ext = cert.extensions.get_extension_for_class(
AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'
