### ISSUE TITLE
mitmproxy==0.18.2 Installed but, the Gui says "Not Satisfied"

### ISSUE THREAD

**Issue by gitxmax** [P0cL4bs/WiFi-Pumpkin-deprecated#321]
Hello, 
I did s fresh install of Pumpkin and it went smooth, to the very end, installer showed no errors.
But, when I go to Pumpkin-Proxy tab of the gui, it says  "the package requirement mitmproxy==0.18.2 is not satisfied"
I tried reinstalling mitmproxy==0.18.2 with pip and pip2, but it had no effect.
Running on PI B3+ with the latest Kali, if that helps.

**Comment by yudevan** [comment]
can you try to execute mitmproxy from command shell, if your mitmproxy is okay then you will be displayed clean window with blue bar on the bottom, otherwise, please paste the error log

**Comment by gitxmax** [comment]
Thanks, that helped, the issue was with the UTF-8 encoding. Can close the ticket.

**Comment by rentandleave** [comment]
Just reopening this . Since i Still have the problem with :mitmproxy==0.18.2 Not Satisfied " on the WiFi-Pumpkin GUI. . How did the issue with UTF-8 encoding solved the problem.It will be very helpful.

Thanks in Advance

**Comment by alifa2try** [comment]
I am having the same issue on Kali 2019.
