### ISSUE TITLE
Wifi card is broken after using tool

### ISSUE THREAD

**Issue by yellowstarburst** [P0cL4bs/WiFi-Pumpkin-deprecated#329]
## What's the problem (or question)?
After running the tool for the first time and then exiting; the laptops WiFi interface becomes unusable. My WiFi indicates that there is no WiFi connections around. THis makes it so I can't run the tool again with WiFi because i have only one AP(external card). PLEASE HELP! 

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): Card on multiple labtops
* Version used tool: newest
* Virtual Machine (yes or no and which):  Hell No
* Operating System and version: kali 2017.3

**Comment by toinopt** [comment]
Hello i have the same problem did you managed to fix it.

**Comment by argum77** [comment]
No i havnt been able too

**Comment by toinopt** [comment]
For the moment i have given up about the kali in dual boot, currently downloading kali linux for the virtual box and i will try to use brigde mode for the internet connection and the usb adapter for the AP

**Comment by Darzl** [comment]
'sudo service network-manager restart' worked for me

**Comment by frostKn** [comment]
even after restarting my network manager my wifi card is still down.....help
