### ISSUE TITLE
No module named netifaces

### ISSUE THREAD

**Issue by SvipRookie** [P0cL4bs/WiFi-Pumpkin-deprecated#33]
Parrot OS

┌─[root@parrot]─[~/Desktop/WiFi-Pumpkin]
└──╼ #./wifi-pumpkin.py 
Traceback (most recent call last):
  File "./wifi-pumpkin.py", line 5, in <module>
    from Core.Main import Initialize
  File "/root/Desktop/WiFi-Pumpkin/Core/Main.py", line 21, in <module>
    from Core.Utils import (
  File "/root/Desktop/WiFi-Pumpkin/Core/Utils.py", line 15, in <module>
    import netifaces
ImportError: No module named netifaces

According to

 `mh4x0f commented 14 days ago

try this:

$ sudo apt-get install python-dev
$ sudo pip install netifaces

if you got this message

Successfully installed netifaces
Cleaning up...

now you can to run WiFi-Pumpkin.

$ sudo ./wifi-pumpkin.py`   

Unable to solve  

help me please

**Comment by mh4x0f** [comment]
try this:

``` sh
easy_install netifaces
```

**Comment by AlBurns-MSFT** [comment]
This is the exact error I get when trying to install on kubuntu. 
Basically each time I got an error I would use pip to install until no more errors and the GUI opened. 

The following commands were used until the GUI opened: 
    sudo apt-get install python-setuptools
    sudo easy_install netifaces
    sudo apt-get install python-dev (doesn't seem necessary)
    sudo easy_install pip
    sudo pip install --upgrade virtualenv
    sudo apt-get install python-netifaces <<this one seemed to resolve the netifaces issue
    sudo pip install configparser
    sudo pip install pygtail
    sudo pip install BeautifulSoup
    sudo pip install netaddr
    sudo pip install config
    sudo pip install isc_dhcp_leases

I had some warnings when installing some of the above: 

"The directory '/home/alex/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/alex/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag."

After all of that, I can run wifi-pumpkin and get the GUI to open. Here is the output:   

alex@alex-VirtualBox:~/WiFi-Pumpkin$ sudo ./wifi-pumpkin.py
Loading GUI...
WiFi-Pumpkin Running!
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: No such file or directory
QFileSystemWatcher: failed to add paths: /home/alex/.config/ibus/bus
Bus::open: Can not get ibus-daemon's address. 
IBusInputContext::createInputContext: no connection to ibus-daemon 

To fix this I used the following commands:
    sudo apt-get install ibus
    ibus-daemon -d

I'll keep playing with it and will edit this when I learn more. It looks like you need to update the install script for kubuntu.

**Comment by brandontict** [comment]
I just started receiving this same error. When attempting to install **netifaces** .

` pip install netifaces
Collecting netifaces
  Downloading netifaces-0.10.5.tar.gz
Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/usr/share/python-wheels/setuptools-32.3.1-py2.py3-none-any.whl/setuptools/__init__.py", line 10, in <module>
    from setuptools.extern.six.moves import filter, filterfalse, map
  File "/usr/share/python-wheels/setuptools-32.3.1-py2.py3-none-any.whl/setuptools/extern/__init__.py", line 1, in <module>
    from pkg_resources.extern import VendorImporter
ImportError: No module named 'pkg_resources.extern'
`
I've tried a new virtualenv, same error. 

`pip list` 
states **setuptools (34.2.0)** is installed. 

Alot of Googling has got me no where.. Any Ideas? 

Thanks for sharing this project :-D
