### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by harry3911** [P0cL4bs/WiFi-Pumpkin-deprecated#339]
i am using latest version of wifi-pumpkin
* Operating System and version: kali linux rolling
i have succesfully installed wifi pumpkin 
but the problem is when ever i am typing wifi-pumpkin it doesn't starts and show this 
![screenshot from 2018-02-28 08-02-46](https://user-images.githubusercontent.com/36356737/36776967-83cdc06a-1c5f-11e8-97a8-4a53f986d20c.png)
how to solve this please help 
and i am not using live 
i have installed kali linux rolling in my pc 
and having wlan0
plz help me!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ghost** [comment]
This is hapening to me too
