### ISSUE TITLE
traceroute question

### ISSUE THREAD

**Issue by AlBurns-MSFT** [P0cL4bs/WiFi-Pumpkin-deprecated#34]
Is it possible to run traceroute on a device connected to WiFi-Pumpkin? How does WiFi-Pumpkin alter ttl values?

When I run traceroute (contained within busybox on cyanogenmod) on a Nexus 4 connected to WiFi-Pumpkin with default options, I see 10.0.0.1 as hop 1, 10.0.2.2 as hop 2, and then everything times out. I would expect to see 10.0.2.2 before 10.0.0.1, as 10.0.0.1 is the router. Could you explain what's going on here?

**Comment by mh4x0f** [comment]
hi, what's going on here is simple, to WiFi-Pumpkin sniff the packets he need configure new dhcp with address 10.0.0.1 (router). the 10.0.2.2 is your gateway(router). all packets data should pass first 10.0.0.1(Machine Attacker) ,after that  router(10.0.2.2) this is MITM attack, but  without ARP poison.

**Comment by AlBurns-MSFT** [comment]
Thanks! This is what was happening: I was running Kali in VirtualBox. The network settings were the default: https://i.imgur.com/nVwYdga.jpg

This allows TCP/IP Traffic and Ping but doesn't appear to work with UDP or ICMP. Switching to Bridged mode instead of NAT now allows traceroute through WiFi-Pumpkin.

edit: SHOULD allow traceroute to work through WiFi-Pumpkin, if I can get WiFi-Pumpkin to work again...
