### ISSUE TITLE
hostapd is not installed

### ISSUE THREAD

**Issue by lorragammer** [P0cL4bs/WiFi-Pumpkin-deprecated#340]
## What's the problem (or question)?

*answer here*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: 
* Virtual Machine (yes or no and which): 
* Operating System and version:

**Comment by lorragammer** [comment]
how to fix it???

**Comment by usama7628674** [comment]
Assuming you're using kali type in `apt-get install hostapd` in terminal and it will install if for you.

**Comment by lorragammer** [comment]
dear it is also not working
plzzz... help

**Comment by usama7628674** [comment]
What did it say?post the output of above command.Which os are you using?

**Comment by usama7628674** [comment]
Fill the template issue

**Comment by lorragammer** [comment]
dear it is also not working
plzzz... help
