### ISSUE TITLE
Devices can't connect to AP

### ISSUE THREAD

**Issue by holao09** [P0cL4bs/WiFi-Pumpkin-deprecated#344]
Devices can't connect to AP

I setup all things seem OK. 
But, no devices can connect AP.
My cellphone say wrong password although no security password on AP.
My notebook can connect but no ip received and it's disconnected after.
![image](https://user-images.githubusercontent.com/5210783/36975342-5ea14f90-20ac-11e8-9efd-a09777ec38f2.png)

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): BCM43438 on Raspberry Pi3 mode B+ 
* Version used tool: **0.8.5**
* Virtual Machine (yes or no and which): No
* Operating System and version: Kali Rolling 2018.1

**Comment by poxyran** [comment]
I have the same problem. I have an up to date Pi3, WP starts without any apparent problem on the terminal but I cannot connect with my Android device or PC (Windows).

**Comment by remixdance** [comment]
same problem here #344
