### ISSUE TITLE
No network support faild

### ISSUE THREAD

**Issue by vequeemnhe** [P0cL4bs/WiFi-Pumpkin-deprecated#348]
i have installed but i get error this message 

> 
faild AP mode :warning interface. The feature access point mode is not support by this device -> wlan0
Your adapter don't support for create access point network

pls, can help me ?

**Comment by mh4x0f** [comment]
![gif-giphy-12173907945322](https://user-images.githubusercontent.com/6795613/37555873-2434bcf0-29cd-11e8-879c-bf327fe5d22d.gif)
