### ISSUE TITLE
Deauth attack module error

### ISSUE THREAD

**Issue by mikeoxlarge** [P0cL4bs/WiFi-Pumpkin-deprecated#35]
When I try and run the deauth  attack it fails to start, I am using an ALFA card on wlan1, the following error is shown in the console

Traceback (most recent call last):
  File "/root/tools/WiFi-Pumpkin/Modules/wireless/WirelessDeauth.py", line 210, in SettingsScan
    self.interface = str(set_monitor_mode(self.get_placa.currentText()).setEnable())
NameError: global name 'set_monitor_mode' is not defined

**Comment by mh4x0f** [comment]
Thanks for reporting the issue.
