### ISSUE TITLE
No protocol specified, cannot connect to X

### ISSUE THREAD

**Issue by sundowndev** [P0cL4bs/WiFi-Pumpkin-deprecated#352]
## What's the problem (or question)?

`./wifi-pumpkin`

~~~
No protocol specified
wifi-pumpkin.py: cannot connect to X server :0.0
~~~

#203 and #28 does not help

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): Network controller: Intel Corporation Wireless 8265 / 8275 (rev 78)
* Version used tool: 0.8.5
* Virtual Machine (yes or no and which): no
* Operating System and version: Ubuntu 17.10

net card does support AP mode

~~~
Supported interface modes (for network card):
		 * IBSS
		 * managed
		 * AP
		 * AP/VLAN
		 * monitor
		 * P2P-client
		 * P2P-GO
		 * P2P-device
~~~

**Comment by SundownDEV** [comment]
~~~
Supported interface modes (for network card):
		 * IBSS
		 * managed
		 * AP
		 * AP/VLAN
		 * monitor
		 * P2P-client
		 * P2P-GO
		 * P2P-device
~~~
