### ISSUE TITLE
Could not import setuptools which is required to install from a source distribution. Please install setuptools.

### ISSUE THREAD

**Issue by unnbreak** [P0cL4bs/WiFi-Pumpkin-deprecated#353]
## What's the problem (or question)?
The program(GUI) and script both doesn't work.

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):  description: Wireless interface
       product: QCA9565 / AR9565 Wireless Network Adapter
       vendor: Qualcomm Atheros

* Version used tool: latest
* Virtual Machine (yes or no and which): no
* Operating System and version: cinnamon 3.6.7  64bit
![pumkin](https://user-images.githubusercontent.com/38285508/38616651-6488b6d2-3db2-11e8-84e5-48a9549b35a3.png)
![pumpkin error](https://user-images.githubusercontent.com/38285508/38616652-64ea9668-3db2-11e8-8789-5ae8a09a544b.png)
![pumpkin setuptool](https://user-images.githubusercontent.com/38285508/38616653-6535aad6-3db2-11e8-95ad-2975141a2e65.png)

**Comment by usama7628674** [comment]
`pip install setuptools`
