### ISSUE TITLE
New Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [P0cL4bs/WiFi-Pumpkin-deprecated#355]
Hello Sir. I'm a UI/UX and Graphics Designer. I want propose a new logo for you. Would you mind if I propose new logo for your application as my Open Source Contribution?  Thanks before.

**Comment by mh4x0f** [comment]
hi, would be nice, great.

**Comment by anharismail** [comment]
@mh4x0f are you the repositories owner? 

I'll post my logo design proposal here as soon as possible

**Comment by mh4x0f** [comment]
yes, I'm main coder. wait...

**Comment by anharismail** [comment]
Hello Sir @mh4x0f, this are my logo design proposals for your app. I'll provide all editable files and all sizes you needed.

Thanks before and hope you like it.

Version 1.
![wifi pumpkin ver 1](https://user-images.githubusercontent.com/37614260/38973409-d5dee7a2-43cf-11e8-9657-17ce401d8dc2.png)

Version 2.
![wifi pumpkin ver 2](https://user-images.githubusercontent.com/37614260/38973441-084fbfb8-43d0-11e8-98c7-39db32e82eed.png)

**Comment by mh4x0f** [comment]
I don't like it, I don't know if i have change the logo again. I'll leave the current logo. thanks

**Comment by anharismail** [comment]
I think u can give any comment for me to revise the logo. But If you think like that, It's no problem for me. Maybe next time, we could collaborate each other for open source contribution.
