### ISSUE TITLE
Using a VPN - No internet connection on the client

### ISSUE THREAD

**Issue by ghost** [P0cL4bs/WiFi-Pumpkin-deprecated#359]
## What's the problem (or question)?
Hello,
If i don't use a VPN the AP work properly, the client have internet,

If i use a VPN, the client can't connect to internet,
He have a DHCP, but no acces,
the client can connect to the AP, and get an IP,
But he can't connect to internet, no ping work,
i tried PPTP protocole and OpenVPN, the issus is the same, 

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
AWUS1900
* Version used tool: 
0.8.5
* Virtual Machine (yes or no and which): 
no
* Operating System and version: 
Kali linux 2018

**Comment by mh4x0f** [comment]
this is a problem with openVPn is blocking the service to share access internet, search on google about "vpn iptables masquerade" exist a lot tutorial to solve this.
