### ISSUE TITLE
GUI error the package requirement mitmproxy==0.18.2 

### ISSUE THREAD

**Issue by fovdj** [P0cL4bs/WiFi-Pumpkin-deprecated#362]
## What's the problem (or question)?
I have installed wifi-pumpkin but when I run it at the GUI tab Pumpkin-Proxy it is said 

Package requirement

The package requirement mitm==0.18.2 is not satisfied

I have run mitmproxy at terminal and it run well..

Please give me advise to solve this problem.. thanks..

**Comment by noobkid2000** [comment]
is your problem solved? i hav also the same issue
