### ISSUE TITLE
Raspberry -  [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by brunolopes446** [P0cL4bs/WiFi-Pumpkin-deprecated#364]
I have two Wifi cards (Raspberry's internal and external: D-Link DWA-127), and in none of them I'm able to start the Pump AP.

The error that pops-out on a window when clicking "Start" button is:

**Error nmcli
 [Errno 2] No such file or directory**

---------------------------------------------

_Raspberry Pi 3 B+
WiFi-Pumpkin 0.8.5 (installed from latest git sources)
OS: Raspbian Desktop (latest version - April 2018)_

---------------------------------------------

```
pi@raspberrypi:~ $ iw list | grep "Supported interface modes" -A 10
	Supported interface modes:
		 * managed
		 * monitor
	Band 1:
		Capabilities: 0x17e
			HT20/HT40
			SM Power Save disabled
			RX Greenfield
			RX HT20 SGI
			RX HT40 SGI
			RX STBC 1-stream
--
	Supported interface modes:
		 * IBSS
		 * managed
		 * AP
		 * P2P-client
		 * P2P-GO
		 * P2P-device
	Band 1:
		Capabilities: 0x1062
			HT20/HT40
			Static SM Power Save

```

There are no complaints in terminal:

```
root@raspberrypi:/home/pi/Downloads/WiFi-Pumpkin/core# wifi-pumpkin Loading GUI...
WiFi-Pumpkin Running!

[*] Loading debugging mode
[*] Current Session::ID [NDEyNzI=]
[*] Configuring hostapd...

```

Already tried several solutions found out there, but none of them worked.

Any help is appreciated

**Comment by brunolopes446** [comment]
Any clues on that?

**Comment by mh4x0f** [comment]
need install nmcli

**Comment by brunolopes446** [comment]
solved. cheers
