### ISSUE TITLE
Update new Version 0.8.7

### ISSUE THREAD

**Issue by mh4x0f** [P0cL4bs/WiFi-Pumpkin-deprecated#367]
I'm work in a new version more moduled with @yudevan. 
@yudevan list the features bellow:

**Comment by jonyvx** [comment]
hi..thanks for creating this great tool...i used virtualbox but victim cant connect and if he connected not internet..and if he get internet it only available for like 30 seconds then connection become limited no internet access ...how to fix ?

**Comment by tuxutku** [comment]
is this project dead?
