### ISSUE TITLE
Wireless deauthentication attack not showing anything

### ISSUE THREAD

**Issue by mi0987** [P0cL4bs/WiFi-Pumpkin-deprecated#368]
## What's the problem (or question)?

When I try to use the Wireless deauthentication attack, and click on start scan with the correct network adapter wlan0, after more than 10 minutes it doesn't show anything. I tried to reinstall but it's not working.

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): alfa awus036nha
* Version used tool: 0.8.5
* Virtual Machine (yes or no and which): Virtualbox, and also without virtual machine
* Operating System and version: Kali Linux 2018.2

**Comment by mh4x0f** [comment]
go to settings and change to airodump-ng scanner.
