### ISSUE TITLE
AP mode not supported (error)

### ISSUE THREAD

**Issue by anikaliboi** [P0cL4bs/WiFi-Pumpkin-deprecated#374]
I get failed "ap mode: warning interface" error, my wifi adaptor is supposed to support ap mode, but I can't seem to get it to work.

*answer here*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): TL-WN722N
* Version used tool: WiFi-Pumpkin v0.8.5
* Virtual Machine (yes or no and which): yes, VirtualBox
* Operating System and version: Kali Linux v2018.1

**Comment by Lukecarter0096** [comment]
If you get the “AP mode not supported” error from Connectify Hotspot in your windows 10, that usually means your wireless adapter does not support Hosted Network. Actually, Connectify Hotspot is a software app which assists you to turn your Windows PC or Laptop device into a virtual router and share an Internet connection with all your devices. Thus, it uses the Windows networking features to create it easier for you. Whereas, Hosted Network is a Microsoft Windows feature that is used by Connectify to create access point mode Hotspots. Make sure that Connectify is the only Windows hotspot software to support the Microsoft Surface tablets. If you are running Windows 10, Connectify can create a hotspot using a Surface tablet by using Wi-Fi direct. However, often “Hosted network” adapter does not support AP mode and not work with Connectify Hotspot, as a result you get the error. Then don’t worry about it. Here, the blog will describe you very easy solutions to Fix the “AP Mode Not Supported” Error. So just follow the troubleshooting steps to resolve “WI-FI Adapter Does Not Support AP Mode Error Permanently: Connectify Hotspot”.

Solutions to Fix the AP Mode Not Supported Error

Solutions to Fix the “AP Mode Not Supported” Error:-
In the occasion that your adapter does not support AP mode, then there are some possible solutions to fix it.

Solution 1:- Check For Driver Updates
You should do to check for driver updates. Many times checking for driver updates may include support for Hosted Networks (or AP mode). You can verify for driver updates by either visiting the computer manufacturer’s website or the wireless adapter manufacturer’s website. After updating your wireless driver check your driver information again.

**Continue Reading-**[ap mode not supported error in windows](https://www.microsoftwindowssupportnumber.com/blog/fix-ap-mode-not-supported-error-windows-10/)
