### ISSUE TITLE
Failed AP Mode.

### ISSUE THREAD

**Issue by blvckbeard** [P0cL4bs/WiFi-Pumpkin-deprecated#378]
## It's a bug or my card dosnt support?

AP mode failed! Should I Change WiFi Adapter or Install any drivers, help me.

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):intel(r) centrino(r) ultimate-n 6300 agn
* Version used tool: v0.8.5
* Virtual Machine (yes or no and which): No
* Operating System and version: Kali Linux 2018.2

**Comment by codegax** [comment]
Can you please show the output of `iw list`
