### ISSUE TITLE
Device not showing in "stations" after Update.

### ISSUE THREAD

**Issue by jeretc** [P0cL4bs/WiFi-Pumpkin-deprecated#380]
## What's the problem (or question)?

*there are no devices shown under stations after recent updates*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):tplink 722N
* Version used tool: 0.8.5
* Virtual Machine (yes or no and which): no
* Operating System and version: Parrot GNU/Linux 3.11

**Comment by mh4x0f** [comment]
no log, no possibility to check.
