### ISSUE TITLE
can not create fake AP [VirtualBox]

### ISSUE THREAD

**Issue by rdbox** [P0cL4bs/WiFi-Pumpkin-deprecated#389]
## What's the problem (or question)?

the problem is I'm running WiFi-Pumpkin I'm pushing start a new AP is being created but I can not connect to it.

I can not connect if I put a password or without a password anyway the connection on the device resets the error of the proxy with authentication.

I tried to connect via wifi laptop is not working
I tried to connect through the phone androyd does not work
Error with identical authorization problems

I also tried changing the DHCP settings to specify different ip subnets.
This also did not help
 
#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: 
* Virtual Machine (yes or no and which): 
* Operating System and version: 

1. **I'm working in Virtualbox guest system**
2. **v 0.8.5** 
3. **OS Kali** 
4.  **wifi-driver** 

```phy0	wlan0		rt2800usb	D-Link Corp. DWA-125 Wireless N 150 Adapter(rev.A3) [Ralink RT5370]```

![image](https://user-images.githubusercontent.com/18515862/42983679-98e272e0-8c1a-11e8-9503-f6c18abfc029.png)

**here is my log file during the launch of WiFi-Pumpkin**
```
You do not have a working installation of the service_identity module: 'cannot import name opentype'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Loading GUI...
WiFi-Pumpkin Running!

[*] Loading debugging mode
[*] Current Session::ID [MjU5MzQ=]
[*] Configuring hostapd...
[*] Enable forwarding in iptables...
[*] Configuring dhcpd...
[*] Sharing Internet Connections with NAT...
[New Thread 3471 (hostapd)]
[New Thread 3473 (DHCP)]
[*] Pumpkin-Proxy running on port:8080 


[*] TCPProxy running on port 80/8080:

TCPProxy::ftp               status:On
TCPProxy::hexdump           status:On
TCPProxy::kerberos          status:On
TCPProxy::summary           status:On
TCPProxy::imageCap          status:On
TCPProxy::httpCap           status:On
TCPProxy::emails            status:On


-------------------------------
AP::[PumpAP] Running...
AP::BSSID::[bc:f6:85:79:77:38] CH 6
```

**Comment by mh4x0f** [comment]
> I'm working in Virtualbox guest system

hi, this is a problem from VirtualBox machine, I don't find any solution and  what's happening for WP in  virtualbox. for the time the solution is use another software for create virtual machine as Vmware etc...

**Comment by rdbox** [comment]
Are you sure exactly? I will add notes from myself my wifi adapter is connected via usb and then I transferred it to the guest VirtualBox

maybe there is a solution? other than how to use vmware it requires a lot of resources is bad

**Comment by mh4x0f** [comment]
#43 look this issue, a lot people have problem only bridge mode in virtualbox.
