### ISSUE TITLE
Adding support for Windows

### ISSUE THREAD

**Issue by hsluoyz** [P0cL4bs/WiFi-Pumpkin-deprecated#39]
Hi,

I'm the author of [Npcap](https://github.com/nmap/npcap), a packet sniffer software from Nmap for Windows based on WinPcap. It supports raw 802.11 packet capture. Please look at the [README](https://github.com/nmap/npcap) and the [docs](https://htmlpreview.github.io/?https://github.com/nmap/npcap/blob/master/docs/npcap-guide-wrapper.html) for details.

I hope it could help you build the Windows version WiFi-Pumpkin tool. If you have any questions or issues about Npcap, please tell me using https://github.com/nmap/nmap/issues or email me (hsluoyz@gmail.com). Thanks!

Cheers,
Yang

**Comment by matheuschimelli** [comment]
+1

**Comment by mh4x0f** [comment]
Hi, nice project Npcap, but we don't intend to build the Windows version WiFi-Pumpkin,  for many reasons, some plugins only work on Linux, implementation of attack MITM without ARP Poison,DHCP-server not work fine,many modules python not support Windows and among others.
