### ISSUE TITLE
Can´t connect to AP from lap or cellphone no internet

### ISSUE THREAD

**Issue by remixdance** [P0cL4bs/WiFi-Pumpkin-deprecated#400]
## What's the problem (or question)?
i have a problem to connect to access point on my android phone tells authentification error and on other lap simple cant connect

*answer here*

#### Please tell us details about your environment.
* Card wireless adapters name (alfa awus036h realink 3072):
* Version used tool: wifipumpkin
* Virtual Machine (yes kalilinux 2018.2): 
* Operating System and version: debian x64 kernek 4.17

**Comment by mh4x0f** [comment]
your card adapter not have support !
