### ISSUE TITLE
AttributeError: class Queue has no attribute 'Queue'

### ISSUE THREAD

**Issue by AntonyChiossi** [P0cL4bs/WiFi-Pumpkin-deprecated#403]
I've seen that the problem as been submitted yet but it still persists (at least with my version of python)

> ➜  ~ sudo wifi-pumpkin
Loading GUI...
WiFi-Pumpkin Running!
Starting Thread:Thread Scanner AP::scapy
2.7.12 (default, Dec  4 2017, 14:50:18)  <--- I modified your code to print what version was used
[GCC 5.4.0 20160609]
Traceback (most recent call last):
  File "/usr/share/WiFi-Pumpkin/core/packets/wireless.py", line 38, in run
    self.LoopScanmer()
  File "/usr/share/WiFi-Pumpkin/core/packets/wireless.py", line 51, in LoopScanmer
    q = Queue.Queue()
AttributeError: class Queue has no attribute 'Queue'

#### Environment.
* Card wireless adapters name (please check if support AP/mode): Built in and also with my Alpha
* Version used tool: Last one (just cloned the project and manually installed it)
* Virtual Machine (yes or no and which):  None
* Operating System and version: Ubuntu 16.04.5

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

I have tried everything: unistalling it - reinstalling it, unistall and reinstall python; tried the .deb
An interesting fact is that if I run the same code from terminal it works.

> ➜  ~ python   
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> import queue as Queue
\>\>\> q = Queue.Queue()
\>\>\> import sys
\>\>\> sys.version
'2.7.12 (default, Dec  4 2017, 14:50:18) \n[GCC 5.4.0 20160609]'

Process to replicate this bug:
1. sudo wifi-pumpkin
2. try the deauth
3. trigger a scan

Thanks in advance!

**Comment by mh4x0f** [comment]
Nice report, brown I'll check this coming soon, but the deauth module need to update.

**Comment by mh4x0f** [comment]
@ntnychss did you try update  python version  to 2.7.14 ?. because I'm try to solve this problem, but a don't understand anything any more. apperently this is a bug from python 2.7.12.

**Comment by AntonyChiossi** [comment]
@mh4x0f I remember that I tried to install a different version of python < than my current one, but unfortunately I don't remember which one. You can use a  Ubuntu 16.04 VM and try to install and use it there. In my distro I only installed required updates so it should be enough to replicate the bug environment.

**Comment by mh4x0f** [comment]
@ntnychss ok nice, I'll check this. there are a option for use airodump-ng on settings if you want to use the feature.

**Comment by mh4x0f** [comment]
@ntnychss try to update the python to 2.7.14, this is the solution for now. thank's

**Comment by yckai** [comment]
Hi, i have a bug with Wifi Pumpkin, when i start arp poisoner i have this error : 

`Loading GUI...
WiFi-Pumpkin Running!
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Starting Thread:Packets SpoofStarting Thread:Arp Poison:: [gateway]
 
Starting Thread:Arp::Poison => [target]
Traceback (most recent call last):
  File "/usr/share/WiFi-Pumpkin/core/packets/network.py", line 134, in run
    self.sniff()
  File "/usr/share/WiFi-Pumpkin/core/packets/network.py", line 158, in sniff
    q = Queue.Queue()
AttributeError: class Queue has no attribute 'Queue'
`
**Environment**
- Python 2.7.15+
- wifi-pumpkin is up to date
- Kali linux  last version
- Vmware workstation
- Network adaptateur bridge 

Thanks in advance!
