### ISSUE TITLE
python using one cpu core 100% when using TCP proxy plugin

### ISSUE THREAD

**Issue by switchgard** [P0cL4bs/WiFi-Pumpkin-deprecated#409]
## What's the problem (or question)?

when started wifi pumkkin causes python to use 100% of a cpu core when TCP proxy plugin is active

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):  N/A
* Version used tool: V0.8.5
* Virtual Machine (yes or no and which): no
* Operating System and version: kali rolling

**Comment by mh4x0f** [comment]
hi, tell me if the terminal is print the log come from tcpdump ?
