### ISSUE TITLE
I think this is a bug with print log 

### ISSUE THREAD

**Issue by AllanChen** [P0cL4bs/WiFi-Pumpkin-deprecated#41]
https://github.com/AllanChen/WorkSample/blob/master/OpenGL%20%E8%B5%84%E6%96%99/bug.jpg

when i click open many link , this error will show on the log.

**Comment by mh4x0f** [comment]
try raising the open file limit:

``` sh
ulimit -n 2048
```

**Comment by mh4x0f** [comment]
thanks for report :D
