### ISSUE TITLE
Captive portal without internet output

### ISSUE THREAD

**Issue by hackituria** [P0cL4bs/WiFi-Pumpkin-deprecated#411]
I'm using Wifi-Pumpkin v0.8.5 on Kali Linux 2018.4.

I created a captive portal using DNS Spoofer and Phishing Manager, but when the victims insert the credentials,do not have access to the Internet.

How can I get this connection?

Thank you!

**Comment by mh4x0f** [comment]
look this #341, the WiFi-Pumpkin is not implement this feature by default.

**Comment by jeretc** [comment]
i use this with wifi-pumpkin.
https://github.com/jeretc/cfp
