### ISSUE TITLE
running setup.py bdist_wheel for lxml -> forever

### ISSUE THREAD

**Issue by Antimorph** [P0cL4bs/WiFi-Pumpkin-deprecated#412]
Hello everyone,

I had no problem installing Wifi Pumpkin in Kali when the OS was installed on the hard drive. Then I tried installing Wifi pumpkin on a properly set up live USB persistence and just in live mode several times. I used different images and tools to create the bootable USB stick (DD, ISO, Rufus, Unetbootin ... etc etc) to check if that is causing it but I'm running into the same problem every time.
When it's installing no error messages appear, but as soon as it hits "running setup.py bdist_wheel for lxml" it won't proceed. In fact the screen will be stuck and I can't do anything! If I move the cursor it won't change position for a few minutes and suddenly it it will move but gets stuck again. I thought it might just be really slow but i've let it run over night and the next morning it didn't change at all.

I've used following commands:

pip install service-identity --force --upgrade (Not used in every try)
git clone https://github.com/P0cL4bs/WiFi-Pumpkin.git
cd WiFi-Pumpkin
./installer.sh --install

I also tried using the deb file with the same outcome:
sudo dpkg -i wifi-pumpkin_0.8.5_all.deb

If I could i'd post the terminal output here, but as stated, I'm not able to do anything if this occura.

I'm using Kali linux 2018.3a with the current Wifi Pumpkin version. The system should be fully compatible since i used Wifi pumpkin before but on a hard drive installation.

Greetings,
 Anti

**Comment by mh4x0f** [comment]
it not a problem with WP, lxml is a dependency the mitmproxy module. if you read the FAQ problem in any module it not solve by me. my tip is if you need to use the WP remove the dependency the mitmproxy removing this line [remove mitmproxy dep](https://github.com/P0cL4bs/WiFi-Pumpkin/blob/master/installer.sh#L62)

**Comment by flipflip99** [comment]
Sorry for the stupid question, but how do you remove the lxml dependency for MITMProxy?
