### ISSUE TITLE
wlan0 busy.

### ISSUE THREAD

**Issue by mdhz** [P0cL4bs/WiFi-Pumpkin-deprecated#42]
Hello,

Whenever i try to start AP it's throwing "An connection with wlan0 has detected:device or resource busy". Is there any solution ?

Thanks.

**Comment by AlBurns-MSFT** [comment]
Not sure if this will help, but make sure you disable the AP before trying to use wifi-pumpkin. e.g., in kali once you confirm the AP is connected, you go to the top right and make sure to disable it, so you can no longer use the USB AP to connect to the internet. It is then ready to be used in wifi-pumpkin.
