### ISSUE TITLE
website design model

### ISSUE THREAD

**Issue by mh4x0f** [P0cL4bs/WiFi-Pumpkin-deprecated#423]
hi all dev front-end user, I want to create an website for WiFi-Pumpkin doc. please send me suggestions. 
colors: based on WiFi-Pumpkin 
style: bootstrap
build: github pages

**Comment by minhducsun2002** [comment]
1. Isn't GitHub Wiki enough?
2. 
```
index.html
|-docs
  |-Getting started
  |-Installation
  |-PumpkinProxy
  |-

**Comment by minhducsun2002** [comment]
1. Isn't GitHub Wiki enough?
2. 
```
index.html
|-docs
  |-Getting started
  |-Installation
  |-PumpkinProxy
  |-TCPProxy
|-FAQs
```
3. About docs, it should be possible that the underlying logic be explained? Like, the reason feature A doesn't work when feature B is active, for example.

**Comment by mh4x0f** [comment]
> Isn't GitHub Wiki enough?

No, website is more impactful

> index.html
|-docs
  |-Getting started
  |-Installation
  |-PumpkinProxy
  |-TCPProxy
|-FAQs

yes, follow the wiki

> About docs, it should be possible that the underlying logic be explained? Like, the reason feature A doesn't work when feature B is active, for example.

I do not understand, tell me an example.

**Comment by minhducsun2002** [comment]
> I do not understand, tell me an example.

I mean, something like "If `NetworkManager` shows that Wi-Fi isn't managed even when WiFi-Pumpkin is not active, try `systemctl restart NetworkManager` and see if it works for you. That is because behind the scenes WiFi-Pumpkin uses `hostapd` which may conflict with `NetworkManager`.". Like tips and FAQs, but where necessary.

**Comment by mh4x0f** [comment]
ok, cool

**Comment by m1sf1t42** [comment]
Hey there @mh4x0f , 
Do you already got any suggestions?
If not, I would send you one the next days, got nothing to do and I'd like to support the project.

**Comment by mh4x0f** [comment]
> Do you already got any suggestions?

No, not yet

**Comment by jeretc** [comment]
> hi all dev front-end user, I want to create an website for WiFi-Pumpkin doc. please send me suggestions.
> colors: based on WiFi-Pumpkin
> style: bootstrap
> build: github pages

hi i think for documentation, you could use this https://readthedocs.org/
check out some of the sample projects.
