### ISSUE TITLE
Doesn't work in VirtualBox when in bridged mode

### ISSUE THREAD

**Issue by AlBurns-MSFT** [P0cL4bs/WiFi-Pumpkin-deprecated#43]
When using VirtualBox/Kali, if I use the default NAT networking mode I can run wifi-pumpkin without problem. However, I need to use ping and traceroute so I need to use bridged mode. If I switch to bridged mode I have an internet connection, but when I turn wifi-pumpkin on and connect to it I don't have an internet connection. Let me know what info you need or log files to help troubleshoot. Thanks!

If there is a specific hypervisor program or network setting needed please let me know.

**Comment by AlBurns-MSFT** [comment]
An update: I have no idea why, but 0.7.3 works and provides an upstream connection using virtualbox in NAT network mode, but the newest version does not. However, in the newest version I don't get error messages like I do when I start 0.7.3.

Of course if you need more details just let me know, I'm eager to help resolve this. 

Here is the output when using 0.7.3: https://gist.github.com/aeb5005/795f3ee3d9bc5ecb5b03de3f9052f073

Here is the output when using 0.7.5 using bridged mode: https://gist.github.com/aeb5005/c6889e9f1ed2b5b3712d33ee08146deb

^ in that output I would start the access point, then connect with my phone and try to load a random website. It would fail to load, and after trying a few more times I would stop access point and then start access point. 

Here is the output when using 0.7.5 using NAT: https://gist.github.com/aeb5005/36e52f0c569c1995bff0277df8bcfc6a

Notice in this output there isn't much to see. I didn't do anything after starting it besides connect to with my phone and attempt to browse the internet. 

Output when using 0.7.5 using Bridged. In this, I turn on the access point, connect with my phone, and tried to browse to a few websites. I then hit stop and then turned it back on again. I tried to connect with my phone and still couldn't load anything. As you can see, quite a few text outputs were displayed once I started the AP for a second time. https://gist.github.com/aeb5005/678bc77dc1772a7752dccdebc4d95e40

**Comment by AlBurns-MSFT** [comment]
Also, in the GUI under the Home tab my network adapter is wlan0. I've noticed if I go to modules -> settings and then to the advanced tab, the interface monitor defaults to wlan1. Should I be changing this to match the Network Adapter on the home tab?

**Comment by mh4x0f** [comment]
do this settings of plugins and run access point. check if it work with bridged  mode.

![snapshot19](https://cloud.githubusercontent.com/assets/6795613/15400007/3f681690-1dc0-11e6-9edc-d6bc8e63f0f5.png)

**Comment by AlBurns-MSFT** [comment]
Still doesn't work. In the below screenshot, i started the AP, connected with my phone and attempted to connect to a few websites. I stopped it and started it again and tried again, still didn't work. No upstream connection.

![capture](https://cloud.githubusercontent.com/assets/6195567/15403325/6ffd853c-1dc6-11e6-9f2b-ac101a1860fc.PNG)

The same thing happens if I switch to NAT instead of Bridged in the virtualbox network settings before starting the VM. 

Maybe I simply have something wrong in my settings? Although, 0.7.3 and NAT mode is working for me with the same settings and hardware. I'm not sure why 0.7.5 isn't working for me at all anymore.

**Comment by AlBurns-MSFT** [comment]
I was looking through the changelog and noticed you wrote:

+- added support to start AP with wireless connection
-    \* Kali Linux (Apparently not work, need some tests) :(
-    \* support kubuntu 15.10
-    \* support wifislax - 4.11.1
-    \* support parrot - 2.0.5

I'm using Kali, I'll try some of the other recommended operating systems and see if I can get it to work. I tried to use ubuntu (not in a VM, installed to a partion on an HDD) and it had errors, I assume because I wasn't using a VM.

**Comment by AlBurns-MSFT** [comment]
Kubuntu: I can get it to run after manually installing some things but I do not get an upstream connection when in bridged mode. Also, it seems I get a message related to ibus-daemon. 

Terminal copy+paste:
alex@alex-VirtualBox:~/WiFi-Pumpkin$ sudo ./wifi-pumpkin.py
[sudo] password for alex: 
Loading GUI...
WiFi-Pumpkin Running!
Bus::open: Can not get ibus-daemon's address. 
IBusInputContext::createInputContext: no connection to ibus-daemon 
alex@alex-VirtualBox:~/WiFi-Pumpkin$ ibus-daemon -d
alex@alex-VirtualBox:~/WiFi-Pumpkin$ sudo ./wifi-pumpkin.py
Loading GUI...
WiFi-Pumpkin Running!
Starting Thread:hostapd
Starting Thread:DHCP
Starting Thread:Net-Creds
Stop thread:hostapd
Stop thread:DHCP
Stop thread:Net-Creds
Starting Thread:hostapd
Starting Thread:DHCP
Starting Thread:Net-Creds
Stop thread:hostapd
Stop thread:DHCP
Stop thread:Net-Creds
alex@alex-VirtualBox:~/WiFi-Pumpkin$

![capture](https://cloud.githubusercontent.com/assets/6195567/15415011/81c6144a-1e0d-11e6-9b84-4425d6146dff.PNG)

**Comment by mh4x0f** [comment]
No, you not need the VM using this systems recommended in changelog. I have an Kubuntu 15.10 ( installed to a partion on an HDD) it work same connected with my Wireless, you can see on this [screenshot](https://github.com/P0cL4bs/WiFi-Pumpkin/wiki/Screenshots). also I run the tool on VMware in bridged mode and get an upstream connection normally.
![snapshot21](https://cloud.githubusercontent.com/assets/6795613/15415098/a4ec8e1e-1e16-11e6-8bb2-bffa48daf742.png)

 I'll try in VirtualBox comming soon

**Comment by AlBurns-MSFT** [comment]
That's great news that you can get it to work in bridged mode!

So, it should work on Ubuntu locally installed? I'll try again and post details if it fails.

I would try in VMware but I wasn't able to figure out how to get VMware to recognize the Alfa device. Could you give instructions? I'll keep playing around and will edit this if I get the Alfa to be recognized in VMware.

**Comment by mh4x0f** [comment]
this is simple [check this](https://www.vmware.com/support/ws55/doc/ws_devices_usb_connect.html) or follow this image:

![](https://ittechnologist.files.wordpress.com/2015/11/capture.jpg)

**Comment by AlBurns-MSFT** [comment]
That doesn't work for me. My Alfa device is connected to my host OS when VMware starts. I then follow the above and select connect. Now the device is connected. Oddly, it's listed as "Atheros UB91C", not the same as yours. 

If you type "iw list" or "iwconfig", do you see a connected device? That's the problem I'm having, I can apparently connect the device to VMware but it doesn't actually then allow me to connect to the internet with it or even show it's connected at all via those commands. 

I can confirm it's connected:
root@kali:~# lsusb
Bus 001 Device 002: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n

I'm using the Alfa AWUS036NHA

**Comment by AlBurns-MSFT** [comment]
To get the Alfa device to work in Virtualbox I have to do very specific steps:
1) restart computer
2) eject device from "connected device settings" in Windows 10 (host OS)
3) unplug
4) add the following filter to the virtualbox settings: 
![capture](https://cloud.githubusercontent.com/assets/6195567/15415725/b76b77f2-1e12-11e6-8e69-6d598f7101e9.PNG)
5) start virtualbox
6) once the OS is loaded in the VM, plug in the device
Then it's successfully recognized by virtualbox. If I deviate from this at all, I usually have to restart the computer.

**Comment by mh4x0f** [comment]
No, not need show same as me,he show  just the driver your card USB, you need connect with OS on VM. check the video I show you how to connect the USB wireless card the first minutes . [video](https://www.youtube.com/watch?v=jFjOANWz4us)

maybe your problem is in Router, because your gateway is "10.0.0.1" the Wifi-pumpkin mount dhcp-server with same gateway "10.0.0.1"  when the  tool add the rules of iptables to share internet. this maybe is blocking the connection.

**Comment by AlBurns-MSFT** [comment]
I followed that video, it seemed exactly like I did before but this time it worked, so I can get VMware to recognize the Alfa USB device. Excellent. Unfortunately I am still not getting an internet connection when starting WiFi-Pumpkin, it looks like I'm having the same problem. 

I can get wifi-pumpkin to work using Virtualbox/NAT/0.7.3, so I looked at those settings. On the home tab, I have gateway set to 10.0.2.2. I tried switching to that and it didn't work in Virtualbox/Bridged/0.7.5

I started looking through the settings to compare and noticed this difference: 
![capture](https://cloud.githubusercontent.com/assets/6195567/15416880/f68b3340-1e1d-11e6-8b54-648f24ba074a.PNG)

![capture](https://cloud.githubusercontent.com/assets/6195567/15416934/7d6a05a8-1e1e-11e6-8d83-fa6c8b4ff21a.PNG)

Maybe I should use the settings in 0.7.3? edit: weird, now that I'm in VMware I can see that the iptables are the same as my 0.7.3 screenshot, yet I am in 0.7.5

I'm not sure what else I should try to change.

**Comment by AlBurns-MSFT** [comment]
As you can see in this screenshot, no matter what I change that gateway field to (10.0.0.1, 10.0.2.2, 192.168.0.1) I don't get an upstream connection like you are. 

![capture](https://cloud.githubusercontent.com/assets/6195567/15417332/a949c90c-1e22-11e6-9da5-b07c19400240.PNG)

Maybe changing the value in the Gateway field on the home tab doesn't actually change the value? I noticed when I restart the program it always goes back to 10.0.0.1

The thing I find perplexing is these default settings worked on 0.7.3/NAT, so why would they not work now? Maybe you changed something ?

**Comment by mh4x0f** [comment]
"Maybe changing the value in the Gateway field on the home tab doesn't actually change the value?"
Yes, you not can change in the Gateway field , this settings you need change your Router.

"I started looking through the settings to compare and noticed this difference"
different this settings because on V0.7.5 the plugins not is checked. It does not interfere with anything on the internet sharing.

"Maybe you changed something ?"
I don't changed the Core of version 0.7.3 to 0.7.5

it very strange, maybe your problem is in Router really,it conflict with the WiFi-pumpkin settings.

**Comment by mh4x0f** [comment]
I did some test on my Lab with same gateway and I do not get an upstream connection. I change the gateway on the tool and work for me. change this settings on **Pumpkin-Settings** Tab and try starting the WiFi-Pumpkin. this  should solve you problem.

![snapshot23](https://cloud.githubusercontent.com/assets/6795613/15432330/30a2a610-1e84-11e6-8f20-24df883fb22f.png)

after that click in **"save settings"**. 
OBS: no change Gateway field, just open the GUI and change this settings above  and run WiFi-Pumpkin

**Comment by AlBurns-MSFT** [comment]
I tried your recommended Pump-Settings, unfortunately it still isn't working. 

I jumped back into Virtualbox/NAT/0.7.3 to make sure it still works. It does. Here is some output:

terminal output when I start wifi-pumpkin, connect with android phone, and browse to facebook: 
https://gist.github.com/aeb5005/415a36be088730611b519854f42f8c1b

main screen: 
![capture](https://cloud.githubusercontent.com/assets/6195567/15434793/b2edd80e-1e86-11e6-9dcf-1e737c6cfb0d.PNG)

Pump-Settings: 
![capture](https://cloud.githubusercontent.com/assets/6195567/15434810/c5e29238-1e86-11e6-9bba-b93ffd28f2f2.PNG)

I tried using Virtualbox/NAT/0.7.5 with default pump-settings, your suggestion, and what worked for me in 0.7.3 and nothing provided an internet connection. 

How strange. I'd really like to get this working in bridged mode for a project i'm working on. That's so perplexing that it works for you and not for me, and that I can get it to work using NAT/0.7.3/default settings only. Maybe there is something I could check for you in the terminal, like run some commands for you to see my settings?

Are there any other settings or things I could try to change? If you need more data from me to help troubleshoot just let me know!

**Comment by AlBurns-MSFT** [comment]
I tried getting it to work in Ubuntu installed to a partition (so no VM). Here is a screenshot. I was able to connect to the AP but again, no internet connection. I followed your recommended Pump-Settings:
![screenshot from 2016-05-22 01 27 46](https://cloud.githubusercontent.com/assets/6195567/15452398/6aae95ba-1fbc-11e6-8f1c-f5ce6f696ed9.png)

Some unique messages: when I start the access point, i get "Error: Object 'radio' is unknown, try 'nmcli help'." and the GUI goes dark while starting. After a few minutes +, the [*] Using interface: wlan0 and below is outputted. 

Screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/6195567/15452391/3bffd436-1fbc-11e6-8e24-5b7393126d65.png)

I tried again in Virtualbox/Bridged/0.7.5 using Kali and got this message (still no internet connection):
![wtf](https://cloud.githubusercontent.com/assets/6195567/15452884/19f4aeb0-1fcc-11e6-94d7-3d337a7e4316.PNG)

**Comment by AlBurns-MSFT** [comment]
for what its worth, i just cloned the repo again and i still have the same issue where the program starts fine but i never get an internet connection to work. i tried all the new dhcp settings, none worked. I'm out of ideas for troubleshooting this but would be willing to give you output/logs if you want
