### ISSUE TITLE
DNSSpoof Server not found

### ISSUE THREAD

**Issue by hdawg12** [P0cL4bs/WiFi-Pumpkin-deprecated#433]
Before opening a new issue, please read this [wiki](https://github.com/P0cL4bs/WiFi-Pumpkin/wiki/Bug-reporting)

## What's the problem (or question)?

I installed the new version of wifi-pumpkin, v0.8.7.
I see that under settings>DNS, the "DNSSpoof server not found" is greyed out.  How can I fix?

*answer here*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): I have an internal NIC(Intel Corporation Dual Band Wireless-AC 3168NGW [Stone Peak] (rev 10)) and a Panda usb
* Version used tool:  0.8.7
* Virtual Machine (yes or no and which): nope
* Operating System and version:  Kali linux 2018 Rolling

**Comment by mh4x0f** [comment]
this feature is locked because not has been implemented.

**Comment by hdawg12** [comment]
ah ok.  Is .8.7 a beta version?
