### ISSUE TITLE
Missing Python module : mitmproxy

### ISSUE THREAD

**Issue by minhducsun2002** [P0cL4bs/WiFi-Pumpkin-deprecated#440]
## What's the problem (or question)?

Wifi-Pumpkin failed to start. Invoking `wifi-pumpkin` in terminal shows that `mitmproxy` isn't installed; however, `pip install mitmproxy` fails with a compilation error from `gcc`, which was then resolved to `cryptography` - a dependency of `mitmproxy` not being built due to unsupported OpenSSL version (1.1.0).

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): Qualcomm Atheros AR9285, bundled in AR5B195 card. Support all 802.11 modes.
* Version used tool: 0.8.7
* Virtual Machine (yes or no and which): No
* Operating System and version: `Debian GNU/Linux buster/sid`, kernel `4.18.0-19.3-liquorix-amd64`

**Comment by minhducsun2002** [comment]
Problem fixed **on Debian**: installing [`mitmproxy=0.18.2-6`](https://packages.debian.org/stretch/mitmproxy) using `sudo aptitude install mitmproxy=0.18.2-6` works. `sudo pip install mitmproxy` fails nevertheless.

**Comment by mh4x0f** [comment]
> a dependency of mitmproxy not being built due to unsupported OpenSSL version (1.1.0)

yes, I solved this making a downgrade the version openSSL to 1.0 in Kali Linux, because another Debian distro like ubuntu is working fine.


Your solution work for all Debian ?

**Comment by minhducsun2002** [comment]
I am not sure if it works on Kali Linux because I cannot find version `0.18.2-6` or any newer **version that was written in Python 2** in [Kali's repository](http://http.kali.org/kali/pool/main/m/mitmproxy/).

However it works on Debian because `stretch` has [it](http://ftp.debian.org/debian/pool/main/m/mitmproxy/) (note that `buster` and `sid` don't have a Python 2 version, they only have `4.0.4` which was written in Python 3.

Theoretically it should work on all Debian-based distro that provides OpenSSL 1.0.x - although I cannot confirm that due to me having a mixed dependency network (using a lot of repositories for Ubuntu and Debian Buster/Sid mixed).

Will report that later when I can get a clean Stretch install.

**Comment by minhducsun2002** [comment]
Tested this on a new `deboostrap`ped Stretch environment.
It builds after `pip` got installed and `apt install libxml2 libxslt` has been run.

About Kali, it seems the desired version isn't present: [Kali's `mitmproxy` repository](http://git.kali.org/gitweb/?p=packages/mitmproxy.git;a=summary) doesn't even have `0.18.2`!

I guess the only way now is to use `gdebi` and install the Debian version.

**Comment by mh4x0f** [comment]
nice brow, I 'll check this.

**Comment by mh4x0f** [comment]
@minhducsun2002 using the gdebi is possible install mitmproxy 0.18.2 in kali without problems ?

**Comment by minhducsun2002** [comment]
@mh4x0f Yes. Confirmed with Kali 2018.4.

Actually, if you want something usable immediately, you can use a combination of `dpkg -i` and `apt install -f` (because, well, `mitmproxy` does depend on a **lot** of packages, and `gdebi` solves the dependency but not `dpkg`).

_Looks like at the time I'm writing this (Jan 8, 22:16 UTC+7) `packages.debian.org` cannot be accessible from my side, so I cannot send you a log or a screenshot to confirm this (if you really wish) though. Nevertheless, I tried [this](https://launchpad.net/ubuntu/zesty/amd64/mitmproxy/0.18.2-1) and it also works._

_Because the problem is at the compilation of `mitmproxy` (or to be specific, the compilation of `cryptography`) and not the dependencies or the module itself, it seems that any package that provides a **compiled** version should work, whether they're for Ubuntu, Debian or any derivatives._

**Comment by mh4x0f** [comment]
@minhducsun2002 you can try to create a .sh script and create a pull request if necessary.

**Comment by anjasnewbie** [comment]
Hi ,
im failed to run the app because mitmproxy not exist.
im try to : sudo aptitude install mitmproxy=0.18.2-6 
![image](https://user-images.githubusercontent.com/7954261/51073454-95c97900-16a3-11e9-9f8a-e92e9ea8efdc.png)

**Comment by anjasnewbie** [comment]
already success install mitmproxy 
pip2 install mitmproxy==0.18.2

**Comment by minhducsun2002** [comment]
@anjasnewbie `pip2` succeeds? Then you no longer need the `apt`/`apt-get`/`aptitude` method.

It's meant to be a replacement for systems that can no longer compile the appropriate version of `cryptography`, so, if `pip2 install` succeeds, why would you do that again?

**Comment by anjasnewbie** [comment]
> Hi ,
> im failed to run the app because mitmproxy not exist.
> im try to : sudo aptitude install mitmproxy=0.18.2-6
> ![image](https://user-images.githubusercontent.com/7954261/51073454-95c97900-16a3-11e9-9f8a-e92e9ea8efdc.png)

post above is before I run pip2 install mitmproxy==0.18.2 
 after I run pip2 install mitmproxy==0.18.2 Im succes to run Wifi Pumkin

**Comment by minhducsun2002** [comment]
> after I run pip2 install mitmproxy==0.18.2 Im succes to run Wifi Pumkin

Then your problem is solved.

**Comment by anjasnewbie** [comment]
yes, my problem is solved.
