### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by srix007** [P0cL4bs/WiFi-Pumpkin-deprecated#447]
Before opening a new issue, please read this [wiki](https://github.com/P0cL4bs/WiFi-Pumpkin/wiki/Bug-reporting)

## What's the problem (or question)?
when I run wifi pumpkin this appears

Traceback (most recent call last):
  File "wifi-pumpkin.py", line 36, in <module>
    from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 2, in <module>
    from core.utils import Refactor
  File "/usr/share/WiFi-Pumpkin/core/utils.py", line 9, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
    f=open(filename, errors='ignore')
TypeError: 'errors' is an invalid keyword argument for this function

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): panda wirelesse
* Version used tool: Wifi-Pumpkin 0.8.7
* Virtual Machine (yes or no and which): nope
* Operating System and version: Kali linux 2018 Rolling

**Comment by felix-schultz** [comment]
Same problem. Tried it with parrot (no vm and not live) and kali (vm) both giving this error

**Comment by dalektardis** [comment]
Same here

**Comment by mh4x0f** [comment]
solution: 
1 - open new tab in your browser
2 - type google.com
3 - type this  "TypeError: 'errors' is an invalid keyword argument for this function"
4 - well come to google response, the most way to find any solution

**Comment by felix-schultz** [comment]
xD I guess you can't really expect help here. I am having a Ton of errors when using your pumpkin. Resolved them in like 2 days but still a apt Update will kill it again. You will need to Release a Update instead of closing every problem

**Comment by dalektardis** [comment]
After testing on Kali last version and Os Parrot Last version, i know it's a buggy tool unfortunately.
