### ISSUE TITLE
there is a problem

### ISSUE THREAD

**Issue by hexhunter404** [P0cL4bs/WiFi-Pumpkin-deprecated#449]
Before opening a new issue, please read this [wiki](https://github.com/P0cL4bs/WiFi-Pumpkin/wiki/Bug-reporting)

## What's the problem (or question)?

Traceback (most recent call last):
  File "/usr/share/WiFi-Pumpkin/core/servers/proxy/package/TCP-Proxy.py", line 222, in run
    self.main()
  File "/usr/share/WiFi-Pumpkin/core/servers/proxy/package/TCP-Proxy.py", line 265, in main
    q = Queue.Queue()
AttributeError: class Queue has no attribute 'Queue'
[*] Pumpkin-Proxy running on port:8080 

nothing appears at monitor screen 
![screenshot from 2019-01-03 22-48-17](https://user-images.githubusercontent.com/46364340/50673096-c0337c00-0fa9-11e9-87a7-ed89774e5ef7.png)

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): yes
* Version used tool: latest 
* Virtual Machine (yes or no and which): yes virtual box 6
* Operating System and version: Kali linux latest ver

**Comment by mh4x0f** [comment]
nice, report I'll check this coming soon

**Comment by m1sf1t42** [comment]
Hey there, 
found this on the python doc: https://docs.python.org/2/library/queue.html

In Python3 the Queue lib was renamed to 'queue'. I think the problem can be solved with the 2to3 Python converter. Works for me at least, running on a Lenovo ThinkPad L540, with the newest kali dist.

**Comment by hdawg12** [comment]
Did you ever get a solution to this problem?  I also have the same error.  It works , but I don't see my AP, I created,  on the network.
This is my error:

![wifipumpkin_error](https://user-images.githubusercontent.com/45344753/71314068-b64b9880-2407-11ea-9551-7ff379103a05.png)
