### ISSUE TITLE
Failure during install on raspberry pi 3+

### ISSUE THREAD

**Issue by jorgeguerron** [P0cL4bs/WiFi-Pumpkin-deprecated#454]
Before opening a new issue, please read this [wiki](https://github.com/P0cL4bs/WiFi-Pumpkin/wiki/Bug-reporting)

##Failure with lxml==3.6.0 and cryptography=1.5.3 What's the problem (or question)?
Not build wheel for lxml and cryptography, so this generate warnings because many methods have warnings and deprecated.

I intent downgrade the package but this not function.

I use kali-linux-2018.4a-rpi3-nexmon-64.img.xz image with raspberry pi 3 b+ and 64 gb sd card

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: 0.8.7
* Virtual Machine (yes or no and which): no, 
* Operating System and version: Kali Linux 2019.1

**Comment by mh4x0f** [comment]
this is a problem with mitmproxy plugin, I'm trying to find a solution #440

**Comment by jorgeguerron** [comment]
Dear Marcos, do you have any idea to update this? I use Wifi-pumpkin in
Debian on my laptop and don't have problem, and a month ago I use the tool
on my raspberry

**Comment by mh4x0f** [comment]
@jorgeguerron  you need to reinstall the tool for install the version correct the mitmproxy
