### ISSUE TITLE
ImportError: No module named netifaces

### ISSUE THREAD

**Issue by MrSwordan** [P0cL4bs/WiFi-Pumpkin-deprecated#46]
Might just be me but I will try and describe the best I can.

Installed Kali on to a microsd for the Raspberry Pi 3. Once loaded up I opened the terminal and used the command "apt-get update && apt-get upgrade -y" waited for it to finish and then rebooted. Then opened terminal once again and used the following 

git clone https://github.com/P0cL4bs/WiFi-Pumpkin.git
cd WiFi-Pumpkin
chmod +x installer.sh
./installer.sh --install

All worked perfect with no errors.
Then I used the command sudo ./wifi-pumpkin.py and then it gave me the following errors.

root@kali:~/WiFi-Pumpkin# sudo ./wifi-pumpkin.py
Traceback (most recent call last):
   File "./wifi-pumpkin.py", line 39, in <module>
      from Core.Main import Initialize
   File "/root/WiFi-Pumpkin/Core/Main.py", line 25, in <module>
      from Core.Utils import (
   File "/root/WiFi-Pumpkin/Core/utils.py", line 9, in <module>
      import netifaces
ImportError: No module named netifcaces
root@kali:~/WiFi-Pumpkin#

Im currently using the ALFA AWUS036NHA if thats any help.

**Comment by mh4x0f** [comment]
https://github.com/P0cL4bs/WiFi-Pumpkin#faq
