### ISSUE TITLE
WIFI Pumpkin Bug | Insert html code into js and css files

### ISSUE THREAD

**Issue by ghost** [P0cL4bs/WiFi-Pumpkin-deprecated#463]
Hi. i see bug.
Wifi-Pumpkin insert html code to all javascript and css files who has not secured (https).
I using beef file "hook.js" to inject, but this probe issue any other js files.
Example (SS):
https://imgur.com/a/Xb0KiaQ
https://imgur.com/a/cfPJgXT
https://imgur.com/a/xI88HOl
https://imgur.com/a/smeW6A0
What is solution for this ?

**Comment by mh4x0f** [comment]
which plugin do you using to inject this code ?

**Comment by ghost** [comment]
I using "js_inject" plugin in "Pumpkin Proxy" tab.

**Comment by mh4x0f** [comment]
@lukaszone0 thank's for report, I now the plugin is working fine.
