### ISSUE TITLE
Building Wheel Lxml - freezes install

### ISSUE THREAD

**Issue by flipflip99** [P0cL4bs/WiFi-Pumpkin-deprecated#468]
How do you remove the lxml dependency for mitmproxy 0.18.2?

#### Please tell us details about your environment.
* Version used tool: Latest
* Virtual Machine (yes or no and which): no
* Operating System and version: kali 18.4

**Comment by mh4x0f** [comment]
not possible I think. I'll find a way to add the new proxy to remove the dependencies the mitmproxy
