### ISSUE TITLE
DHCP settings unchangeable after first starting

### ISSUE THREAD

**Issue by minhducsun2002** [P0cL4bs/WiFi-Pumpkin-deprecated#471]
It is no longer possible to change DHCP settings once the AP has been started **at least once** . The only way is to restart.

![image](https://user-images.githubusercontent.com/32769878/52911635-07b36480-32d9-11e9-92ad-6aefa7dfb977.png)

System details :
- Debian Stretch
- Kernel version `4.20.0-8.2-liquorix-amd64`
- Running bare-metal (no virtualization)
- Network card:
  * `wlan0` (Qualcomm Atheros AR9285 bundled with internal AR5B195) for Internet connection
  * `wlan1` (TP-Link TL-WN722Nv2 with RTL8188EUS, driver [here](https://github.com/kimocoder/rtl8188eus)) hosts the AP.

**Comment by jepunband** [comment]
same. no internet on client once connected.

**Comment by jepunband** [comment]
didn't solve still the same.
