### ISSUE TITLE
network interface not found

### ISSUE THREAD

**Issue by Sheikhlipu123** [P0cL4bs/WiFi-Pumpkin-deprecated#477]
when i run wifi pumpkin it show 
You do not have a working installation of the service_identity module: 'cannot import name opentype'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Loading GUI...
WiFi-Pumpkin Running!
_----------------------_
and then when i try to start wifi pumpkin it says "NETWORK INTERFACE NOT FOUND"

**Comment by ROHITkumaw** [comment]
same error tell me what to do
