### ISSUE TITLE
installer.sh not executable- permission denied

### ISSUE THREAD

**Issue by TelnetHavoc** [P0cL4bs/WiFi-Pumpkin-deprecated#495]
Hello, so after I type cd WiFi-Pumpkin and then type ./installer.sh —install it says “bash: ./installer.sh: Permission Denied. 
Please help

**Comment by BBgoesMAC** [comment]
just use:
bash installer.sh --install

worked for me, I guess this must be adjusted in the readme

**Comment by kodkirurg** [comment]
You should set it to be runnable.
sudo chmod +x installer.sh

**Comment by TelnetHavoc** [comment]
Thanks Guys yeah i had to run a sudo command with it
