### ISSUE TITLE
Editing Templates doesn't change Capital Portal view

### ISSUE THREAD

**Issue by rcc147** [P0cL4bs/WiFi-Pumpkin-deprecated#501]
Hi - I'm trying to edit one of the existing captive portal templates to remove the user ID section so only the password is required when someone tries to connect through the fake AP, but after editing the file (in an HTML editor it looks how I want it) it doesn't change how the portal appears. I even deleted the template and the corresponding python file (plugins/loginpage.py), but when running wifi pumpkin, the portal still runs and looks the same. I don't understand how this is possible. Deleting the files that generate a portal should cause an error? Could someone help me understand? Thank you!

**Comment by mh4x0f** [comment]
hi, look if you change the file in folder the WiFi-Pumpkin, you have to execute the sudo ./wifi-pumpkin.py, probably will be work fine
