### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by CryptoSage** [P0cL4bs/WiFi-Pumpkin-deprecated#507]
I'm Connected to the Internet With A USB-Modem, But WP shows none in connection status

**Desktop (please complete the following information):**
* Version used tool: Version 0.8.8 
* Virtual Machine (yes or no and which): No
* Operating System and version: Kali 2019.2 gnome 3.30
![Screenshot from 2019-06-19 13-36-11](https://user-images.githubusercontent.com/34539938/59766065-4d883580-9297-11e9-88a9-aa837255a14e.png)

**Comment by mh4x0f** [comment]
USB-Modem is not supported
