### ISSUE TITLE
CaptivePortal not showing apple devices in credmonitor 

### ISSUE THREAD

**Issue by iBoy112** [P0cL4bs/WiFi-Pumpkin-deprecated#510]
**Description of the bug or feature request**

When iOS users connect to the fake AP, they get captured and see the portal. After "logging in" their credentials list in the captiveportal logger but not in the list from the credmonitor. Android/windows users do not have the same issue. There is no noticeable difference in de logging from captiveportal

EDIT: this problem doesn't only occur with apple devices.

**To Reproduce**
1. Activate the CaptivePortal as plugin
2. Launch WiFi-Pumpkin
3. Try to log on with apple device
4. See error in WiFi-Pumpkin in tab "Monitor Activity"

**Expected behavior**
Credentials from these devices also showing up in de credmonitor.

**Desktop (please complete the following information):**
* Version used tool: v0.8.8
* Virtual Machine (yes or no and which): No, raspberry pi 3B
* Operating System and version: raspbian buster desktop

**Comment by mh4x0f** [comment]
great report, but it is not possible to fix. the captiveportal logger was been created for solve this.
