### ISSUE TITLE
No redirection with Facebook/google on android browser

### ISSUE THREAD

**Issue by Devjavax** [P0cL4bs/WiFi-Pumpkin-deprecated#513]
**Description of the bug or feature request**

**To Reproduce**
1. Activate dnsspoof plugin in the pumpkin proxy.
2. Activate Python DHCP server + Activate PyDns server
3. Enable Server Proxy (and activate TCP proxy+pumpkin proxy)
2. Configure the plugin dnsspoof to redirect "facebook.com"(same for google.com) to ip x.x.x.x
4. activate the wifi AP.

**Expected behavior**
This should redirect the page launched from my client to x.x.x.x

**Desktop (please complete the following information):**
* Version used tool: v0.8.8
* Virtual Machine (yes or no and which):  yes VMware pro 15
* Operating System and version: Kali 2019.2
* Client used: Chrome on Android Pie (Android 9).

PS: I tried other website redirection (teste.com-> x.x.x.x): works fine.
* x.x.x.x: My internal ip address with SET framework

I believe facebook + google have some kind of spoofDNS protection ? Not sure.

What should I do ?

Regards,

** INCOMPLETE REPORT WILL BE CLOSED **

**Comment by mh4x0f** [comment]
yes, most website have protection. There's nothing to do.
