### ISSUE TITLE
WiFi-Pumpkin GUI got hang while start 

### ISSUE THREAD

**Issue by fatmeat** [P0cL4bs/WiFi-Pumpkin-deprecated#531]
![image](https://user-images.githubusercontent.com/58129877/69490504-1102da80-0ec4-11ea-81b4-e2fbc349a9d1.png)

Hi guys, i'm using Raspberry Pi 4 and got WiFi-Pumpkin installed, when i start and i got stuck in "Enable forwarding in ip tables", please help me

**Comment by autoscaled** [comment]
this was reported in https://github.com/P0cL4bs/WiFi-Pumpkin/issues/526 and offers possible solution. Personally I cloned a previous version to get it working

**Comment by fatmeat** [comment]
Thanks etnies, however i try to configure a way to fix.
1) get full version of Kali
2) apt-get dist-upgrade

iptables is resolved and pumpkin work.
