### ISSUE TITLE
an connection with wlan0 has been detected : devise or resource busy

### ISSUE THREAD

**Issue by Doktor28** [P0cL4bs/WiFi-Pumpkin-deprecated#54]
i have problem with WiFi-Pumpkin
i use kali linux 2.0 in vmawre workation 11.0.0 when i satrt server and i want to hack pc with my connection and click start access point i show always this erreur 
an connection with wlan0 has been detected : devise or resource busy
wlan0     IEEE 802.11bgn  ESSID:"DJAWEB_3B69"
i have wirless adaper tplink-wn722 Atheros please help me
![capture](https://cloud.githubusercontent.com/assets/19843893/15942281/aa87eba0-2e7b-11e6-8d1e-d8dbaaaa3f18.PNG)

**Comment by AlBurns-MSFT** [comment]
Try to disable the wifi, then start wifi-pumpkin. also type iw list or iwconfig and make sure you can grep for AP. The issue could be related to your tplink device not being suitable. 

edit: this is what I mean when I say disable the wifi in kali 2.0: 

![capture](https://cloud.githubusercontent.com/assets/6195567/15950414/a62f72de-2e7c-11e6-8845-5f9ea99a1df8.PNG)

**Comment by Doktor28** [comment]
i am sorry i was worked in windows update attack for this reason I saw 'devise or resource busy' this is problem when i stopped the widows update attack it work correctly.
but i have another problem with windows update attack when i click server start it start normaly but when i go google chrome  or any browser i don't found the fake page  But I see only in 192.168.1.15:80
what is the solution i want to show the fake page in all websites

**Comment by Doktor28** [comment]
the problem is corect but i have another problem the dns spoof not work because when i active dns with update fake page i don't show the fake page in browser i try wlan0 and eth0
what is the problem please 
![capture](https://cloud.githubusercontent.com/assets/19843893/15968486/ff10489a-2f23-11e6-8118-1b2fdbaff23b.PNG)

**Comment by mh4x0f** [comment]
please, you need to create another issue for this question only dns spoof.
