### ISSUE TITLE
problem with dns spoof 

### ISSUE THREAD

**Issue by Doktor28** [P0cL4bs/WiFi-Pumpkin-deprecated#55]
i have problem the dns spoof not work because when i active dns with update fake page i don't show the fake page in browser i try wlan0 and eth0
what is the problem please 
![capture](https://cloud.githubusercontent.com/assets/19843893/15968486/ff10489a-2f23-11e6-8118-1b2fdbaff23b.PNG)

**Comment by mh4x0f** [comment]
do you trying to start the AP (Access point) and run DNS spoof correct?

**Comment by Doktor28** [comment]
no but dns spoof work withowt AP i showed your video tutorial 
but when i active AP What is the benefit dns spoof 
what is the problem i don't understand i try in wi xp and 8 don't success
can you help me

**Comment by mh4x0f** [comment]
i don't understand what you want, send me output the terminal.
