### ISSUE TITLE
Can't Save anything on "Preference" option

### ISSUE THREAD

**Issue by the-maux** [P0cL4bs/WiFi-Pumpkin-deprecated#58]
Traceback (most recent call last):
     File "WiFi-Pumpkin/Core/utility/settings.py", line 72, in save_settings
             self.Settings.set_setting('accesspoint','interface',str(self.interface.text()))
AttributeError: 'frm_Settings' object has no attribute 'interface'

Can't Save anything on "Preference" option.

**Comment by mh4x0f** [comment]
thanks for report
