### ISSUE TITLE
Error Advanced Mode::monitor crashed application

### ISSUE THREAD

**Issue by Disc0nect** [P0cL4bs/WiFi-Pumpkin-deprecated#60]
I ran through the install several times; however, when I launch the application I receive the following error "libpng warning: iCCP: known incorrect sRGB profile."

![image](https://cloud.githubusercontent.com/assets/20251680/16541695/e8bd0b60-4057-11e6-9be4-1f916cbbaff6.png)

After launching the application, I receive and error and the AP does not broadcast.

![capture](https://cloud.githubusercontent.com/assets/20251680/16541726/0690787e-4059-11e6-8154-a7066df4c179.PNG)

Hardware /Software:
Windows 10 box running Virtual box
Kali 2016 image
All updates and upgrades applied
Wifi Antenna -  AWUS036NH

**Comment by mh4x0f** [comment]
it's a warning and not an error, just ignore. the kali 2016 not have support the tool, some dependency not work fine.

**Comment by Disc0nect** [comment]
The error prevents the application from broadcasting an SSID. Any recommendations?

**Comment by mh4x0f** [comment]
no, not error that prevented. use kali 2.0 or check  OS listed on wiki instalation

**Comment by mh4x0f** [comment]
thanks for report :D

**Comment by Disc0nect** [comment]
Anytime, it's really a great tool.  I tested the changes on both Kali Sana & rolling.  The new changes fixed the crash issue on both distros.  Everything appears to work correctly now, with the exception or the credential portion.  This section no longer grabs credentials, nor generates an error to notate.

Thanks again for the quick fixes.. it's much appreciated.
