### ISSUE TITLE
Having problem access the spoofed pages on the victim PC

### ISSUE THREAD

**Issue by Cosmic4x2** [P0cL4bs/WiFi-Pumpkin-deprecated#62]
Hello.. I have been trying to get you program working for a while its seem so be an awesome program

I start the sever it creates the Fake AP I connect to the AP but it does not route to any pages. I have set to windows update spoof with payload  but the only way I can get to it is by 10.0.0.1 in the browser. Please let 
me know if I am doing something wrong or how to fix this..

Thx

**Comment by mh4x0f** [comment]
hi, You need to run  Fake AP without plugin Proxy server, to work. In latest release was been added in plugins an option "No Proxy". for create the Fake AP with DNS or ARP spoof this option "No Proxy" should be marked.

**Comment by mh4x0f** [comment]
check this screenshot:
![export](https://cloud.githubusercontent.com/assets/6795613/16900914/ad08d5a0-4c09-11e6-8ccc-b2ec4f58d6e4.png)

**Comment by Cosmic4x2** [comment]
Hello I do not have that option. Is there an updated version?.... Also I
appreciate the help let me know where I can send  donations....

[image: Inline image 1]

**Comment by Cosmic4x2** [comment]
AHHH Its Works.... Fantastic.... Let me know about the donations.... Much
Thanks Good Work..............

**Comment by mh4x0f** [comment]
about the donations, I'll add this options coming soon... thanks for report.

**Comment by Cosmic4x2** [comment]
Cool... Please keep me posted on any other projects you may have...

Thx

**Comment by mh4x0f** [comment]
added donate :D https://github.com/P0cL4bs/WiFi-Pumpkin#donate

**Comment by Cosmic4x2** [comment]
can you add a link for paypal...

**Comment by Cosmic4x2** [comment]
Hey found the link sent you a donation... Keep me in mind for any up coming
projects...

Thx

**Comment by mh4x0f** [comment]
thanks for donation :+1:

**Comment by Cosmic4x2** [comment]
Hello On Pumpkin when target PC is connected to the rogue AP is it possible
to route all traffic back to the spoofed page or is it possible to
spoof only 1 page but with target PC still able to browse the web.

Thx
