### ISSUE TITLE
DSN Spoof Not Working

### ISSUE THREAD

**Issue by Cosmic4x2** [P0cL4bs/WiFi-Pumpkin-deprecated#64]
Hello... I cannot seem to get the DNS Spoof Working... Please check the video and let ma know what I am doing wrong.

Thx

https://www.youtube.com/watch?v=GzGclKzashI

**Comment by mh4x0f** [comment]
https://github.com/P0cL4bs/WiFi-Pumpkin/issues/62#issuecomment-233155999
