### ISSUE TITLE
DNS Spoof with Rougue AP

### ISSUE THREAD

**Issue by Cosmic4x2** [P0cL4bs/WiFi-Pumpkin-deprecated#65]
Is it possible to route all HTTP to the spoofed update page when AP is enabled.

**Comment by mh4x0f** [comment]
yes, when you start dns spoof attack with AP is enabled all client connected the AP are redirected to page spoofed. for this you need to clear all hosts added on DNS spoof Module.
check this screenshot:
![screenshot_kali133](https://cloud.githubusercontent.com/assets/6795613/17113832/c3ea1340-5282-11e6-99bd-bda030435650.png)

**Comment by Cosmic4x2** [comment]
Cool it works...

Thx

**Comment by mh4x0f** [comment]
@Cosmic4x2  I'll fix Dns spoof module coming soon for as you said "possible to
spoof only 1 page but with target PC still able to browse the web". 
thanks for suggestion

**Comment by mh4x0f** [comment]
:D check the video demo
https://www.youtube.com/watch?v=SDBVgqYw0OE

**Comment by Cosmic4x2** [comment]
Nice working good now...

Thx

**Comment by CamelToeJoe** [comment]
When I add hosts it will redirect them to the spoof page.  However when I clear all hosts, then nothing gets redirected to the spoof page.

I am trying to redirect all traffic to a certain page.  

Thanks

**Comment by Cosmic4x2** [comment]
make sure you are choosing no Proxy on plugins

**Comment by CamelToeJoe** [comment]
I did.  I can spoof all the  single pages I want.   Works fine.   I just want to redirect it all.

**Comment by mh4x0f** [comment]
@CamelToeJoe create an new for this question. I'll check coming soon...

**Comment by mh4x0f** [comment]
@CamelToeJoe It is no longer necessary create new issue. I fixed this bug... thanks

**Comment by Cosmic4x2** [comment]
Great how did you fix it?

**Comment by mh4x0f** [comment]
@Cosmic4x2 I did somes test in my lab, for redirect all HTTP page now you need "clear all" hosts in module DNS spoof as I showed in [screenshot](https://github.com/P0cL4bs/WiFi-Pumpkin/issues/65#issuecomment-235054677)  above.
