### ISSUE TITLE
Beef Injection

### ISSUE THREAD

**Issue by Cosmic4x2** [P0cL4bs/WiFi-Pumpkin-deprecated#66]
Hello again I hate to keep bugging you but I have another question. When trying to use beef hook injection it does not seem to be working for me. I have  sergio-proxy selected set hook url http://192.168.1.87:3000/hook.js  it shows that I have several injection but is not showing up in beef. I have tried using http://10.0.0.1:3000/hook.js did not work either strangest thing is it did work a few times  I followed the same steps as when I was able to connect. Also from time to time it seems to kill my apache.

**Comment by mh4x0f** [comment]
I'll do some test for this bug coming soon

**Comment by mh4x0f** [comment]
I did not have problem with beef hook, all works fine. maybe, the website that you are testing is not to be injected. check this 
![screenshot_kali143](https://cloud.githubusercontent.com/assets/6795613/17194594/2352a13c-542f-11e6-9d1a-99e37ed32102.png)

**Comment by Cosmic4x2** [comment]
Actually I think the problem is I'm getting a two many files open error Beef is connecting but after the target machine browses a couple of pages I get that error then cannot browse anymore machine still shows connected  to Rouge AP but it looses web and beef connection.

**Comment by mh4x0f** [comment]
read this paper about this error "Too many open files".
[https://easyengine.io/tutorials/linux/increase-open-files-limit/](url)

**Comment by Cosmic4x2** [comment]
Yea that did work still having a problem hooking beef may be a problem on my end.. I will check it out. Thanks for the quick response.
