### ISSUE TITLE
Ettercap module

### ISSUE THREAD

**Issue by gnomeragan** [P0cL4bs/WiFi-Pumpkin-deprecated#67]
Hi,

I'm running WiFi-Pumpkin on a Raspberry Pi.
I was able to use the NetCreds module without problem.
However, I am not able to use the ettercap module.
Here is what happens when I click on Tools -> Activate Ettercap :

http://imgur.com/a/J0Qcl

And so I just can't use it at all.
Any ideas ?

Edit : the problem is exactly the same when trying to click Tools -> Activate Driftnet

Thanks !

**Comment by mh4x0f** [comment]
thank's for report...

**Comment by gnomeragan** [comment]
Thanks. Solved my prob. (had to install xterm as well as default Kali Pi release doesn't have it).
