### ISSUE TITLE
Device or resource busy

### ISSUE THREAD

**Issue by linuggx** [P0cL4bs/WiFi-Pumpkin-deprecated#71]
In reference to the issue #54 

Hello, I have the same problem of the issue 54: 
I use Kali Linux and when I click start access point WiFi-Pumpkin shows me always this error:
an connection with wlan0 has been detected : device or resource busy
wlan0 IEEE 802.11bgn ESSID:"name_wifi".
I have tried to do what he said @aeb5005 but nothing. I have a Dell XPS15.

thanks in advance.

**Comment by linuggx** [comment]
Hello, thanks for the answer.
I tried to log off from my WiFi network and after I tried to start the tool, but does not work.
If I'm not connected to a WiFi network WiFi-Pumpkin shows me another error: not find internet connection.
If I start the tool without connection and after i tryed to connect to wifi network WiFi-Pumpkin shows me always this error: an connection with wlan0 has been detected : device or resource busy.

**Comment by linuggx** [comment]
Hello thanks for the reply.
If Wi-Fi Pumpkins show me this error: an connection with wlan0 has been detected : device or resource busy it means that I will never use the tool with wifi network but only with ethernet? 
why does this happen?
@mh4x0f 
Thanks

**Comment by mh4x0f** [comment]
if you had a minimum knowledge of wireless networks, you will notice that it is not possible to use a  interface/wireless two ways at the same time.  you got this error because you didn't read the wiki page, please if you not user linux we recommend to use on Virtual Machine. 
thank's

**Comment by 0xsanjaydas** [comment]
Same problem is happening with me

**Comment by malwareoverflow** [comment]
I had the same problem , I was using 4G device then I connected the device with laptop using it data cable (In case of router use ethernet) then turned off the laptop wifi so that the I was able to connect with internet using ethernet and built in wifi was free , just then closed the wifi pumpkin and restart run perfectly
