### ISSUE TITLE
Fake Access Point Detection in Andriod 

### ISSUE THREAD

**Issue by sidjad** [P0cL4bs/WiFi-Pumpkin-deprecated#73]
recently I used wifi-pumpkin , When I try to connect with  Android mobile phone without any anti-virus (Cm-cleaner ,360AV) , It was working very good , But I move forward to Different Android which by default install anti-virus which is no going to connect my rough-ap . 
It's clear indicate that wifi-pumpkin AP detect by android anti-virus . 
I Hope detection rate will be decrease .

**Comment by mh4x0f** [comment]
there are a couple of ways of detecting rogue APs, by this is much more complicated make it undetectable. but i'll added somes improvements coming soon...
