### ISSUE TITLE
Problem install Debian Jessie

### ISSUE THREAD

**Issue by lgcambero** [P0cL4bs/WiFi-Pumpkin-deprecated#74]
![1](https://cloud.githubusercontent.com/assets/11602705/17640461/4aa44de0-60d6-11e6-9def-43a32288793f.png)

**Comment by jonatanrdsantos** [comment]
WiFi-Pumpkin needs an X screen interface

**Comment by lgcambero** [comment]
Thanks for answering. You could give me a little more information on how to fix it? Greetings.

**Comment by lgcambero** [comment]
And solve it, I think temporarily with "xhost +". Thank you.
