### ISSUE TITLE
[Feature Request] Request Rogue AP, Deauth Attack and Probe Request

### ISSUE THREAD

**Issue by zero77** [P0cL4bs/WiFi-Pumpkin-deprecated#76]
WiFi-Pumpkin is a really great tool with some great features, but to make it even more powerful can you use the Rogue AP, Deauth Attack and the Probe Request together.

For example, the Probe Request picks up an AP name and then the Rogue AP creates an AP with that name and then the Deauth Attack attacks the real AP, but this is all dune automatically when a new Probe Request is captured.

Thanks

**Comment by mh4x0f** [comment]
@zero77 i think that this feature does not fit in this project proposal. look this project  [wifiphisher](https://github.com/sophron/wifiphisher) , I think it would fit better... thanks

**Comment by zero77** [comment]
Perhaps, but WiFi-Pumpkin is a better peas of software and it would improve it even more to automate what’s already built in.
