### ISSUE TITLE
[Feature Request] Probe Request Enhancements

### ISSUE THREAD

**Issue by zero77** [P0cL4bs/WiFi-Pumpkin-deprecated#80]
Can you add a column that shows the channel of the AP from the probe request.

Can you also add a clone option that creates a rogue AP that is identical to a selected probe request.

**Comment by mh4x0f** [comment]
```
Can you add a column that shows the channel of the AP from the probe request.
```

please, search on  how to  work probe request frame.
![maxresdefault](https://cloud.githubusercontent.com/assets/6795613/18029805/fffc271e-6c78-11e6-8d0a-96dc928afe53.jpg)

```
Can you also add a clone option that creates a rogue AP that is identical to a selected probe request.
```

 Nope, does not fit in this project proposal. WiFi-Pumpkin not make EvilTwinAttack not anymore...
