### ISSUE TITLE
Devices Table Improvement

### ISSUE THREAD

**Issue by zero77** [P0cL4bs/WiFi-Pumpkin-deprecated#81]
Can you add a refresh Butten or an in built auto refresh that updates the devices table, so you can tell when a device has disconnected from the AP.

**Comment by mh4x0f** [comment]
it already been implemented when added table, but  Kali linux/ not work beacause the process Hostapd, not return in real time the ouput the Qprocess. this is very strange. you can try with OS: parrot 3.1(tested)/Ubuntu 15.10(tested) or wifislax.
