### ISSUE TITLE
Is it possible to use bettercap with fake ap enabled?

### ISSUE THREAD

**Issue by Cosmic4x2** [P0cL4bs/WiFi-Pumpkin-deprecated#84]
## What's the problem (or question)?

Is it possible to use bettercap with fake ap enabled?

_answer here_
#### Please tell us details about your environment.
- Card wireless adapters name (support AP/monitor mode):
- Version used tool: 
- Virtual Machine (yes or no and which): 
- Operating System and version:

**Comment by mh4x0f** [comment]
yes, it's possible. just open new terminal and run bettercap (using -I options ) with same  the interface (wlanX) that you set for mount AP in **WiFi-Pumpkin**. 
ex: 
if you are using interface (wlan1) for mount AP in WiFi-Pumpkin then you need to specify this interface in **bettercap** check-out ...

>  sudo bettercap -I wlan1 -X

**Comment by Cosmic4x2** [comment]
Works Great Thx...

**Comment by mh4x0f** [comment]
#106 look
