### ISSUE TITLE
Facebook\Gmail problem with capture NetCreds

### ISSUE THREAD

**Issue by aviran86** [P0cL4bs/WiFi-Pumpkin-deprecated#85]
hey
i used the Wifi-pumpkin v0.8.1

everything work OK.

i can capture user name and password from  website
but when i  try capture the Facebook user name and password or Gmail user and password

i not see nothing

what the problem?

**Comment by jonatanrdsantos** [comment]
You are using the default fake template or and customized one?

**Comment by aviran86** [comment]
hey Jonatan

thx about the quicqly response 

i used the defult template , only download this software and play start

also i can capture only website then not with https

some website like gmail , github , facebook i cant capture the password

**Comment by mh4x0f** [comment]
bypass HSTS not does work in all web browsers.
