### ISSUE TITLE
AWUS036H

### ISSUE THREAD

**Issue by mehranexpert** [P0cL4bs/WiFi-Pumpkin-deprecated#9]
hi dear , is it work on AWUS036H ? i not see Access point .

**Comment by mh4x0f** [comment]
hi, AWUS036H not working yet AP mode, see https://wireless.wiki.kernel.org/en/users/Drivers/rtl8187

**Comment by mehranexpert** [comment]
it Support on airbase-ng .

**Comment by mh4x0f** [comment]
you can to change to airbase-ng on Modules->Settings, access point -> airbase-ng.

**Comment by Highpressure** [comment]
its not selectable, is it because we need to stick to the old version of aircrack suite ?

**Comment by kiang70** [comment]
airbase-ng,it's not selectable.I start AP, but i can't find it with other phone or computer.kali2.0

**Comment by wikijm** [comment]
Hi everyone,

Has anyone managed to run this model with latest WiFi-Pumpkin version?
I did not find "airbase-ng on Modules->Settings, access point -> airbase-ng" parameter.

**Comment by wikijm** [comment]
OK, never mind, the answer is here: https://github.com/P0cL4bs/WiFi-Pumpkin/issues/94
