### ISSUE TITLE
PhishingManager SetEnv path not working with dnsspoof module

### ISSUE THREAD

**Issue by userdsp** [P0cL4bs/WiFi-Pumpkin-deprecated#90]
loading pages just stop. Im using SetEnv path
- Card wireless adapters name (support AP/monitor mode): TL-WN722N
- Version used tool: 0.8.1
- Virtual Machine (yes or no and which): yes
- Operating System and version: Kali Linux 4.6.0-kali1-686-pae

**Comment by mh4x0f** [comment]
I'll add a commit coming soon for fix this bug. thanks for report

**Comment by mh4x0f** [comment]
@userdsp try now...

**Comment by userdsp** [comment]
Still not working... If I start DnsSpoof then all pages stop loading at clients side and there is no redirecting to the phished page.
Do you need more information and can I contact you on skype, fb...etc?

**Comment by mh4x0f** [comment]
send me printscreen the dnsspoof window.

**Comment by mh4x0f** [comment]
@userdsp for Dnsspoof work with Access Point, you need to set plugin for "No Proxy". as can see in screenshot.
![](https://cloud.githubusercontent.com/assets/6795613/16900914/ad08d5a0-4c09-11e6-8ccc-b2ec4f58d6e4.png)

**Comment by userdsp** [comment]
If I stop proxy then all pages has loaded except the spoofed one. 
![wifi](https://cloud.githubusercontent.com/assets/7585552/18957317/a525b2ec-862c-11e6-9102-bc065014f012.jpg)

**Comment by mh4x0f** [comment]
It's not working  because facebook is using HTTPS. dnsspoof only work for HTTP trafic.
