### ISSUE TITLE
The function airbase-ng doesn't active in script

### ISSUE THREAD

**Issue by mrkill121** [P0cL4bs/WiFi-Pumpkin-deprecated#95]
Why airbase-ng doesn't active in options?

[![Captura de Tela 2016-10-05 às 16.49.59.png](https://s18.postimg.org/rmgwmf1tl/Captura_de_Tela_2016_10_05_a_s_16_49_59.png)](https://postimg.org/image/l8rtj5wxh/)

**Comment by mh4x0f** [comment]
#92
