### ISSUE TITLE
FakeAP problems

### ISSUE THREAD

**Issue by Buff3r** [P0cL4bs/WiFi-Pumpkin-deprecated#97]
## What's the problem (or question)?

When I try to start FakeAP it doesn't start.

Logs:
WiFi-Pumpkin Report Logger
Report Generated at::Thu Oct 13 10:19:56 2016
-[ hostapd Logger ]-
SessionID[OTEyNzg=] 2016-10-13 09:49:49,590 : Configuration file: Settings/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started

SessionID[OTEyNzg=] 2016-10-13 09:50:32,828 : Configuration file: Settings/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started

SessionID[MjA2NDQ=] 2016-10-13 09:50:32,828 : Configuration file: Settings/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started

SessionID[OTEyNzg=] 2016-10-13 09:53:57,905 : Configuration file: Settings/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started

SessionID[MjA2NDQ=] 2016-10-13 09:53:57,905 : Configuration file: Settings/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started

SessionID[NzEyNzA=] 2016-10-13 09:53:57,905 : Configuration file: Settings/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started

SessionID[NDc4MDg=] 2016-10-13 10:05:23,914 : Configuration file: Settings/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started

SessionID[NDc4MDg=] 2016-10-13 10:08:43,112 : Configuration file: Settings/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started

SessionID[ODQ0NA==] 2016-10-13 10:08:43,112 : Configuration file: Settings/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started

SessionID[NDc4MDg=] 2016-10-13 10:09:36,716 : Configuration file: Settings/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started

SessionID[ODQ0NA==] 2016-10-13 10:09:36,716 : Configuration file: Settings/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started

SessionID[NzA2MzA=] 2016-10-13 10:09:36,716 : Configuration file: Settings/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started

SessionID[MTE0MDg=] 2016-10-13 10:17:27,601 : Configuration file: Settings/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started

-[ dhcp Logger ]-
SessionID[OTEyNzg=] 2016-10-13 09:49:43,563 : ---[ Start DHCP Thu Oct 13 09:49:43 2016]---
SessionID[OTEyNzg=] 2016-10-13 09:49:43,654 : Internet Systems Consortium DHCP Server 4.3.5b1
SessionID[OTEyNzg=] 2016-10-13 09:49:43,655 : Copyright 2004-2016 Internet Systems Consortium.
SessionID[OTEyNzg=] 2016-10-13 09:49:43,655 : All rights reserved.
SessionID[OTEyNzg=] 2016-10-13 09:49:43,655 : For info, please visit https://www.isc.org/software/dhcp/
SessionID[OTEyNzg=] 2016-10-13 09:49:43,680 : Config file: /etc/dhcp/dhcpd.conf
SessionID[OTEyNzg=] 2016-10-13 09:49:43,681 : Database file: /var/lib/dhcp/dhcpd.leases
SessionID[OTEyNzg=] 2016-10-13 09:49:43,681 : PID file: /var/run/dhcpd.pid
SessionID[OTEyNzg=] 2016-10-13 09:49:43,682 : Wrote 0 leases to leases file.
SessionID[OTEyNzg=] 2016-10-13 09:49:43,718 : Listening on LPF/wlan0/90:f6:52:cc:14:8e/10.0.0.0/8
SessionID[OTEyNzg=] 2016-10-13 09:49:43,718 : Sending on   LPF/wlan0/90:f6:52:cc:14:8e/10.0.0.0/8
SessionID[OTEyNzg=] 2016-10-13 09:49:43,718 : Sending on   Socket/fallback/fallback-net
SessionID[OTEyNzg=] 2016-10-13 09:49:43,719 : Server starting service.
SessionID[OTEyNzg=] 2016-10-13 09:50:26,798 : ---[ Start DHCP Thu Oct 13 09:50:26 2016]---
SessionID[MjA2NDQ=] 2016-10-13 09:50:26,798 : ---[ Start DHCP Thu Oct 13 09:50:26 2016]---
SessionID[OTEyNzg=] 2016-10-13 09:50:26,801 : Internet Systems Consortium DHCP Server 4.3.5b1
SessionID[MjA2NDQ=] 2016-10-13 09:50:26,801 : Internet Systems Consortium DHCP Server 4.3.5b1
SessionID[OTEyNzg=] 2016-10-13 09:50:26,801 : Copyright 2004-2016 Internet Systems Consortium.
SessionID[MjA2NDQ=] 2016-10-13 09:50:26,801 : Copyright 2004-2016 Internet Systems Consortium.
SessionID[OTEyNzg=] 2016-10-13 09:50:26,801 : All rights reserved.
SessionID[MjA2NDQ=] 2016-10-13 09:50:26,801 : All rights reserved.
SessionID[OTEyNzg=] 2016-10-13 09:50:26,802 : For info, please visit https://www.isc.org/software/dhcp/
SessionID[MjA2NDQ=] 2016-10-13 09:50:26,802 : For info, please visit https://www.isc.org/software/dhcp/
SessionID[OTEyNzg=] 2016-10-13 09:50:26,815 : Config file: /etc/dhcp/dhcpd.conf
SessionID[MjA2NDQ=] 2016-10-13 09:50:26,815 : Config file: /etc/dhcp/dhcpd.conf
SessionID[OTEyNzg=] 2016-10-13 09:50:26,816 : Database file: /var/lib/dhcp/dhcpd.leases
SessionID[MjA2NDQ=] 2016-10-13 09:50:26,816 : Database file: /var/lib/dhcp/dhcpd.leases
SessionID[OTEyNzg=] 2016-10-13 09:50:26,816 : PID file: /var/run/dhcpd.pid
SessionID[MjA2NDQ=] 2016-10-13 09:50:26,816 : PID file: /var/run/dhcpd.pid
SessionID[OTEyNzg=] 2016-10-13 09:50:26,817 : Wrote 0 leases to leases file.
SessionID[MjA2NDQ=] 2016-10-13 09:50:26,817 : Wrote 0 leases to leases file.
SessionID[OTEyNzg=] 2016-10-13 09:50:26,854 : Listening on LPF/wlan0/90:f6:52:cc:14:8e/10.0.0.0/8
SessionID[MjA2NDQ=] 2016-10-13 09:50:26,854 : Listening on LPF/wlan0/90:f6:52:cc:14:8e/10.0.0.0/8
SessionID[OTEyNzg=] 2016-10-13 09:50:26,854 : Sending on   LPF/wlan0/90:f6:52:cc:14:8e/10.0.0.0/8
SessionID[MjA2NDQ=] 2016-10-13 09:50:26,854 : Sending on   LPF/wlan0/90:f6:52:cc:14:8e/10.0.0.0/8
SessionID[OTEyNzg=] 2016-10-13 09:50:26,855 : Sending on   Socket/fallback/fallback-net
SessionID[MjA2NDQ=] 2016-10-13 09:50:26,855 : Sending on   Socket/fallback/fallback-net
SessionID[OTEyNzg=] 2016-10-13 09:50:26,855 : Server starting service.
SessionID[MjA2NDQ=] 2016-10-13 09:50:26,855 : Server starting service.
SessionID[OTEyNzg=] 2016-10-13 09:53:51,883 : ---[ Start DHCP Thu Oct 13 09:53:51 2016]---
SessionID[MjA2NDQ=] 2016-10-13 09:53:51,883 : ---[ Start DHCP Thu Oct 13 09:53:51 2016]---
SessionID[NzEyNzA=] 2016-10-13 09:53:51,883 : ---[ Start DHCP Thu Oct 13 09:53:51 2016]---
SessionID[OTEyNzg=] 2016-10-13 09:53:51,886 : Internet Systems Consortium DHCP Server 4.3.5b1
SessionID[MjA2NDQ=] 2016-10-13 09:53:51,886 : Internet Systems Consortium DHCP Server 4.3.5b1
SessionID[NzEyNzA=] 2016-10-13 09:53:51,886 : Internet Systems Consortium DHCP Server 4.3.5b1
SessionID[OTEyNzg=] 2016-10-13 09:53:51,886 : Copyright 2004-2016 Internet Systems Consortium.
SessionID[MjA2NDQ=] 2016-10-13 09:53:51,886 : Copyright 2004-2016 Internet Systems Consortium.
SessionID[NzEyNzA=] 2016-10-13 09:53:51,886 : Copyright 2004-2016 Internet Systems Consortium.
SessionID[OTEyNzg=] 2016-10-13 09:53:51,886 : All rights reserved.
SessionID[MjA2NDQ=] 2016-10-13 09:53:51,886 : All rights reserved.
SessionID[NzEyNzA=] 2016-10-13 09:53:51,886 : All rights reserved.
SessionID[OTEyNzg=] 2016-10-13 09:53:51,887 : For info, please visit https://www.isc.org/software/dhcp/
SessionID[MjA2NDQ=] 2016-10-13 09:53:51,887 : For info, please visit https://www.isc.org/software/dhcp/
SessionID[NzEyNzA=] 2016-10-13 09:53:51,887 : For info, please visit https://www.isc.org/software/dhcp/
SessionID[OTEyNzg=] 2016-10-13 09:53:51,900 : Config file: /etc/dhcp/dhcpd.conf
SessionID[MjA2NDQ=] 2016-10-13 09:53:51,900 : Config file: /etc/dhcp/dhcpd.conf
SessionID[NzEyNzA=] 2016-10-13 09:53:51,900 : Config file: /etc/dhcp/dhcpd.conf
SessionID[OTEyNzg=] 2016-10-13 09:53:51,900 : Database file: /var/lib/dhcp/dhcpd.leases
SessionID[MjA2NDQ=] 2016-10-13 09:53:51,900 : Database file: /var/lib/dhcp/dhcpd.leases
SessionID[NzEyNzA=] 2016-10-13 09:53:51,900 : Database file: /var/lib/dhcp/dhcpd.leases
SessionID[OTEyNzg=] 2016-10-13 09:53:51,900 : PID file: /var/run/dhcpd.pid
SessionID[MjA2NDQ=] 2016-10-13 09:53:51,900 : PID file: /var/run/dhcpd.pid
SessionID[NzEyNzA=] 2016-10-13 09:53:51,900 : PID file: /var/run/dhcpd.pid
SessionID[OTEyNzg=] 2016-10-13 09:53:51,901 : Wrote 0 leases to leases file.
SessionID[MjA2NDQ=] 2016-10-13 09:53:51,901 : Wrote 0 leases to leases file.
SessionID[NzEyNzA=] 2016-10-13 09:53:51,901 : Wrote 0 leases to leases file.
SessionID[OTEyNzg=] 2016-10-13 09:53:51,938 : Listening on LPF/wlan0/90:f6:52:cc:14:8e/10.0.0.0/8
SessionID[MjA2NDQ=] 2016-10-13 09:53:51,938 : Listening on LPF/wlan0/90:f6:52:cc:14:8e/10.0.0.0/8
SessionID[NzEyNzA=] 2016-10-13 09:53:51,938 : Listening on LPF/wlan0/90:f6:52:cc:14:8e/10.0.0.0/8
SessionID[OTEyNzg=] 2016-10-13 09:53:51,938 : Sending on   LPF/wlan0/90:f6:52:cc:14:8e/10.0.0.0/8
SessionID[MjA2NDQ=] 2016-10-13 09:53:51,938 : Sending on   LPF/wlan0/90:f6:52:cc:14:8e/10.0.0.0/8
SessionID[NzEyNzA=] 2016-10-13 09:53:51,938 : Sending on   LPF/wlan0/90:f6:52:cc:14:8e/10.0.0.0/8
SessionID[OTEyNzg=] 2016-10-13 09:53:51,939 : Sending on   Socket/fallback/fallback-net
SessionID[MjA2NDQ=] 2016-10-13 09:53:51,939 : Sending on   Socket/fallback/fallback-net
SessionID[NzEyNzA=] 2016-10-13 09:53:51,939 : Sending on   Socket/fallback/fallback-net
SessionID[OTEyNzg=] 2016-10-13 09:53:51,939 : Server starting service.
SessionID[MjA2NDQ=] 2016-10-13 09:53:51,939 : Server starting service.
SessionID[NzEyNzA=] 2016-10-13 09:53:51,939 : Server starting service.
SessionID[NDc4MDg=] 2016-10-13 10:05:17,897 : ---[ Start DHCP Thu Oct 13 10:05:17 2016]---
SessionID[NDc4MDg=] 2016-10-13 10:05:18,012 : Internet Systems Consortium DHCP Server 4.3.5b1
SessionID[NDc4MDg=] 2016-10-13 10:05:18,012 : Copyright 2004-2016 Internet Systems Consortium.
SessionID[NDc4MDg=] 2016-10-13 10:05:18,012 : All rights reserved.
SessionID[NDc4MDg=] 2016-10-13 10:05:18,012 : For info, please visit https://www.isc.org/software/dhcp/
SessionID[NDc4MDg=] 2016-10-13 10:05:18,027 : Config file: /etc/dhcp/dhcpd.conf
SessionID[NDc4MDg=] 2016-10-13 10:05:18,027 : Database file: /var/lib/dhcp/dhcpd.leases
SessionID[NDc4MDg=] 2016-10-13 10:05:18,027 : PID file: /var/run/dhcpd.pid
SessionID[NDc4MDg=] 2016-10-13 10:05:18,028 : Wrote 0 leases to leases file.
SessionID[NDc4MDg=] 2016-10-13 10:05:18,066 : Listening on LPF/wlan0/90:f6:52:cc:14:8e/10.0.0.0/8
SessionID[NDc4MDg=] 2016-10-13 10:05:18,066 : Sending on   LPF/wlan0/90:f6:52:cc:14:8e/10.0.0.0/8
SessionID[NDc4MDg=] 2016-10-13 10:05:18,066 : Sending on   Socket/fallback/fallback-net
SessionID[NDc4MDg=] 2016-10-13 10:05:18,067 : Server starting service.
SessionID[NDc4MDg=] 2016-10-13 10:08:37,095 : ---[ Start DHCP Thu Oct 13 10:08:37 2016]---
SessionID[ODQ0NA==] 2016-10-13 10:08:37,095 : ---[ Start DHCP Thu Oct 13 10:08:37 2016]---
SessionID[NDc4MDg=] 2016-10-13 10:08:37,098 : Internet Systems Consortium DHCP Server 4.3.5b1
SessionID[ODQ0NA==] 2016-10-13 10:08:37,098 : Internet Systems Consortium DHCP Server 4.3.5b1
SessionID[NDc4MDg=] 2016-10-13 10:08:37,102 : Copyright 2004-2016 Internet Systems Consortium.
SessionID[ODQ0NA==] 2016-10-13 10:08:37,102 : Copyright 2004-2016 Internet Systems Consortium.
SessionID[NDc4MDg=] 2016-10-13 10:08:37,102 : All rights reserved.
SessionID[ODQ0NA==] 2016-10-13 10:08:37,102 : All rights reserved.
SessionID[NDc4MDg=] 2016-10-13 10:08:37,102 : For info, please visit https://www.isc.org/software/dhcp/
SessionID[ODQ0NA==] 2016-10-13 10:08:37,102 : For info, please visit https://www.isc.org/software/dhcp/
SessionID[NDc4MDg=] 2016-10-13 10:08:37,111 : Config file: /etc/dhcp/dhcpd.conf
SessionID[ODQ0NA==] 2016-10-13 10:08:37,111 : Config file: /etc/dhcp/dhcpd.conf
SessionID[NDc4MDg=] 2016-10-13 10:08:37,112 : Database file: /var/lib/dhcp/dhcpd.leases
SessionID[ODQ0NA==] 2016-10-13 10:08:37,112 : Database file: /var/lib/dhcp/dhcpd.leases
SessionID[NDc4MDg=] 2016-10-13 10:08:37,113 : PID file: /var/run/dhcpd.pid
SessionID[ODQ0NA==] 2016-10-13 10:08:37,113 : PID file: /var/run/dhcpd.pid
SessionID[NDc4MDg=] 2016-10-13 10:08:37,113 : Wrote 0 leases to leases file.
SessionID[ODQ0NA==] 2016-10-13 10:08:37,113 : Wrote 0 leases to leases file.
SessionID[NDc4MDg=] 2016-10-13 10:08:37,146 : Listening on LPF/wlan0/90:f6:52:cc:14:8e/172.16.0.0/12
SessionID[ODQ0NA==] 2016-10-13 10:08:37,146 : Listening on LPF/wlan0/90:f6:52:cc:14:8e/172.16.0.0/12
SessionID[NDc4MDg=] 2016-10-13 10:08:37,146 : Sending on   LPF/wlan0/90:f6:52:cc:14:8e/172.16.0.0/12
SessionID[ODQ0NA==] 2016-10-13 10:08:37,146 : Sending on   LPF/wlan0/90:f6:52:cc:14:8e/172.16.0.0/12
SessionID[NDc4MDg=] 2016-10-13 10:08:37,147 : Sending on   Socket/fallback/fallback-net
SessionID[ODQ0NA==] 2016-10-13 10:08:37,147 : Sending on   Socket/fallback/fallback-net
SessionID[NDc4MDg=] 2016-10-13 10:08:37,147 : Server starting service.
SessionID[ODQ0NA==] 2016-10-13 10:08:37,147 : Server starting service.
SessionID[NDc4MDg=] 2016-10-13 10:09:30,691 : ---[ Start DHCP Thu Oct 13 10:09:30 2016]---
SessionID[ODQ0NA==] 2016-10-13 10:09:30,691 : ---[ Start DHCP Thu Oct 13 10:09:30 2016]---
SessionID[NzA2MzA=] 2016-10-13 10:09:30,691 : ---[ Start DHCP Thu Oct 13 10:09:30 2016]---
SessionID[NDc4MDg=] 2016-10-13 10:09:30,695 : Internet Systems Consortium DHCP Server 4.3.5b1
SessionID[ODQ0NA==] 2016-10-13 10:09:30,695 : Internet Systems Consortium DHCP Server 4.3.5b1
SessionID[NzA2MzA=] 2016-10-13 10:09:30,695 : Internet Systems Consortium DHCP Server 4.3.5b1
SessionID[NDc4MDg=] 2016-10-13 10:09:30,696 : Copyright 2004-2016 Internet Systems Consortium.
SessionID[ODQ0NA==] 2016-10-13 10:09:30,696 : Copyright 2004-2016 Internet Systems Consortium.
SessionID[NzA2MzA=] 2016-10-13 10:09:30,696 : Copyright 2004-2016 Internet Systems Consortium.
SessionID[NDc4MDg=] 2016-10-13 10:09:30,696 : All rights reserved.
SessionID[ODQ0NA==] 2016-10-13 10:09:30,696 : All rights reserved.
SessionID[NzA2MzA=] 2016-10-13 10:09:30,696 : All rights reserved.
SessionID[NDc4MDg=] 2016-10-13 10:09:30,696 : For info, please visit https://www.isc.org/software/dhcp/
SessionID[ODQ0NA==] 2016-10-13 10:09:30,696 : For info, please visit https://www.isc.org/software/dhcp/
SessionID[NzA2MzA=] 2016-10-13 10:09:30,696 : For info, please visit https://www.isc.org/software/dhcp/
SessionID[NDc4MDg=] 2016-10-13 10:09:30,707 : Config file: /etc/dhcp/dhcpd.conf
SessionID[ODQ0NA==] 2016-10-13 10:09:30,707 : Config file: /etc/dhcp/dhcpd.conf
SessionID[NzA2MzA=] 2016-10-13 10:09:30,707 : Config file: /etc/dhcp/dhcpd.conf
SessionID[NDc4MDg=] 2016-10-13 10:09:30,708 : Database file: /var/lib/dhcp/dhcpd.leases
SessionID[ODQ0NA==] 2016-10-13 10:09:30,708 : Database file: /var/lib/dhcp/dhcpd.leases
SessionID[NzA2MzA=] 2016-10-13 10:09:30,708 : Database file: /var/lib/dhcp/dhcpd.leases
SessionID[NDc4MDg=] 2016-10-13 10:09:30,708 : PID file: /var/run/dhcpd.pid
SessionID[ODQ0NA==] 2016-10-13 10:09:30,708 : PID file: /var/run/dhcpd.pid
SessionID[NzA2MzA=] 2016-10-13 10:09:30,708 : PID file: /var/run/dhcpd.pid
SessionID[NDc4MDg=] 2016-10-13 10:09:30,709 : Wrote 0 leases to leases file.
SessionID[ODQ0NA==] 2016-10-13 10:09:30,709 : Wrote 0 leases to leases file.
SessionID[NzA2MzA=] 2016-10-13 10:09:30,709 : Wrote 0 leases to leases file.
SessionID[NDc4MDg=] 2016-10-13 10:09:30,742 : Listening on LPF/wlan0/90:f6:52:cc:14:8e/192.168.0.0/24
SessionID[ODQ0NA==] 2016-10-13 10:09:30,742 : Listening on LPF/wlan0/90:f6:52:cc:14:8e/192.168.0.0/24
SessionID[NzA2MzA=] 2016-10-13 10:09:30,742 : Listening on LPF/wlan0/90:f6:52:cc:14:8e/192.168.0.0/24
SessionID[NDc4MDg=] 2016-10-13 10:09:30,742 : Sending on   LPF/wlan0/90:f6:52:cc:14:8e/192.168.0.0/24
SessionID[ODQ0NA==] 2016-10-13 10:09:30,742 : Sending on   LPF/wlan0/90:f6:52:cc:14:8e/192.168.0.0/24
SessionID[NzA2MzA=] 2016-10-13 10:09:30,742 : Sending on   LPF/wlan0/90:f6:52:cc:14:8e/192.168.0.0/24
SessionID[NDc4MDg=] 2016-10-13 10:09:30,743 : Sending on   Socket/fallback/fallback-net
SessionID[ODQ0NA==] 2016-10-13 10:09:30,743 : Sending on   Socket/fallback/fallback-net
SessionID[NzA2MzA=] 2016-10-13 10:09:30,743 : Sending on   Socket/fallback/fallback-net
SessionID[NDc4MDg=] 2016-10-13 10:09:30,743 : Server starting service.
SessionID[ODQ0NA==] 2016-10-13 10:09:30,743 : Server starting service.
SessionID[NzA2MzA=] 2016-10-13 10:09:30,743 : Server starting service.
SessionID[MTE0MDg=] 2016-10-13 10:17:21,572 : ---[ Start DHCP Thu Oct 13 10:17:21 2016]---
SessionID[MTE0MDg=] 2016-10-13 10:17:21,575 : Internet Systems Consortium DHCP Server 4.3.5b1
SessionID[MTE0MDg=] 2016-10-13 10:17:21,575 : Copyright 2004-2016 Internet Systems Consortium.
SessionID[MTE0MDg=] 2016-10-13 10:17:21,578 : All rights reserved.
SessionID[MTE0MDg=] 2016-10-13 10:17:21,578 : For info, please visit https://www.isc.org/software/dhcp/
SessionID[MTE0MDg=] 2016-10-13 10:17:21,588 : Config file: /etc/dhcp/dhcpd.conf
SessionID[MTE0MDg=] 2016-10-13 10:17:21,588 : Database file: /var/lib/dhcp/dhcpd.leases
SessionID[MTE0MDg=] 2016-10-13 10:17:21,589 : PID file: /var/run/dhcpd.pid
SessionID[MTE0MDg=] 2016-10-13 10:17:21,589 : There's already a DHCP server running.
SessionID[MTE0MDg=] 2016-10-13 10:17:21,589 : 
SessionID[MTE0MDg=] 2016-10-13 10:17:21,589 : If you think you have received this message due to a bug rather
SessionID[MTE0MDg=] 2016-10-13 10:17:21,589 : than a configuration issue please read the section on submitting
SessionID[MTE0MDg=] 2016-10-13 10:17:21,590 : bugs on either our web page at www.isc.org or in the README file
SessionID[MTE0MDg=] 2016-10-13 10:17:21,591 : before submitting a bug.  These pages explain the proper
SessionID[MTE0MDg=] 2016-10-13 10:17:21,591 : process and the information we find helpful for debugging..
SessionID[MTE0MDg=] 2016-10-13 10:17:21,591 : 
SessionID[MTE0MDg=] 2016-10-13 10:17:21,591 : exiting.
#### Please tell us details about your environment.
- Card wireless adapters name (please check if support AP/mode): TL-WN722N
- Version used tool: last
- Virtual Machine (yes or no and which): no
- Operating System and version: Kali Linux 2016.2 (Rolling)

**Comment by mh4x0f** [comment]
the tool don't was tested in Kali Rolling.

**Comment by mh4x0f** [comment]
@Buff3r you can try to exclude card the network-manager and check if work. [here tutorial](https://github.com/P0cL4bs/WiFi-Pumpkin/issues/69#issuecomment-245456151)

**Comment by Buff3r** [comment]
Thanks!

```
  Da: Marcos Nesster <notifications@github.com>
```

 A: P0cL4bs/WiFi-Pumpkin WiFi-Pumpkin@noreply.github.com 
Cc: Buff3r frizzo75@yahoo.it; Mention mention@noreply.github.com
 Inviato: Giovedì 13 Ottobre 2016 17:18
 Oggetto: Re: [P0cL4bs/WiFi-Pumpkin] FakeAP problems (#97)

@Buff3r you can try to exclude card the network-manager and check if work. here tutorial—
