### ISSUE TITLE
Fake AP Doesnt lunch on ubuntt 16 when using 2 wireless cards

### ISSUE THREAD

**Issue by ceromee** [P0cL4bs/WiFi-Pumpkin-deprecated#98]
## What's the problem (or question)?

I have installed ubuntu 16, and I connect one wireless card to the internet, and I launch the fake ap using an usb wireless card, and I got not errors, but the ap does not get launch, thx for this tool guys, good job!
#### Please tell us details about your environment.
- Card wireless adapters name (please check if support AP/mode):
  I am using:
  *Atheros AR3012(supports monitor mode)
  *AWUS036H(supports monitor mode)
- Version used tool: 0.8.1
- Virtual Machine (yes or no and which): no
- Operating System and version: Ubuntu 16.04

**Comment by mh4x0f** [comment]
@ceromee you need to update tool....
you have that exclude wifi card adapter the Network-manager for do this, open WiFI-Pumpkin and go to  menu Modules->Settings. now you have to check this option and save as can see in screenshot bellow. after that, you need to **start** AP again, if doesn't work just click in **stop** and start again AP. 

OBS: the first start AP is to add the exclude interface, when start again the AP is mounted with success. I'll fixed this bug coming soon.

![screenshot_kali32](https://cloud.githubusercontent.com/assets/6795613/19413711/8c7602e2-930b-11e6-99ce-060c5872587e.png)

**Comment by mh4x0f** [comment]
this card  AWUS036H not have support AP mode
